### ISSUE TITLE
PHP warning in documentation output

### ISSUE THREAD

**Issue by krzysiekpiasecki** [facebook/php-webdriver#162]
There is php warning at the bootom of page  http://facebook.github.io/php-webdriver/namespaces/default.html

"Documentation is powered by phpDocumentor and authored on Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/whhone/github/php-webdriver/vendor/twig/twig/lib/Twig/Extension/Core.php on line 89 July 12th, 2014 at 03:34."

**Comment by gfosco** [comment]
Removed this warning from that page... At some point we'll rebuild all of them and make sure it's not there across everything.  Thanks.
