### ISSUE TITLE
File Upload - Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by ssfinney** [facebook/php-webdriver#170]
I'm using Codeception with the Facebook WebDriver module, Selenium 2, and PhantomJS on a Jenkins server that runs builds for me. The errors only occur on the Jenkins server (an Ubuntu box), not on my local Mac OS X machine.

I'm getting ```Invalid argument supplied for foreach()```. Here's the stack trace:
```
#1  /var/lib/jenkins/workspace/project-name-feature__/vendor/facebook/webdriver/lib/WebDriverKeys.php:104
#2  /var/lib/jenkins/workspace/project-name-feature__/vendor/facebook/webdriver/lib/remote/RemoteWebElement.php:266
#3  /var/lib/jenkins/workspace/project-name-feature__/app/tests/acceptance/AcceptanceTester.php:1427
#4  /var/lib/jenkins/workspace/project-name-feature__/app/tests/acceptance/FooBarCest.php:54
```

I'm using the ```attachFile``` method in Codeception, which simply passes a CSS selector and a file path.

I've traced this back as far as it will go. The problem originates when the WebDriver sends the "sendFile" command inside ```webdriver/lib/remote/HttpCommandExecutor.php``` , which sends a POST through curl to ```/session/<session_id>/file```, but the response returns with a value and session_id of null.

The null value gets passed back up to the ```upload``` method in ```webdriver/lib/remote/RemoteWebElement.php```. Those values get passed back to the ```sendKeys``` method in the same file, which calls ```WebDriverKeys::encode```. In the ```encode``` method, the foreach fails because of null values.

I've been chasing this bug for days. Do you have any ideas?

Here's the JSON response of the curl POST.
```
Array
(
    [value] =>
    [info] => Array
    (
        [url] => http://127.0.0.1:4444/wd/hub/session/8cbe52b0-5887-11e4-b0cf-8dd06ef908a2/file
        [content_type] => text/plain
        [http_code] => 405
        [header_size] => 100
        [request_size] => 213
        [filetime] => -1
        [ssl_verify_result] => 0
        [redirect_count] => 0
        [total_time] => 2.004951
        [namelookup_time] => 2.5E-5
        [connect_time] => 0.000275
        [pretransfer_time] => 0.000276
        [size_upload] => 3614
        [size_download] => 4215
        [speed_download] => 2102
        [speed_upload] => 1802
        [download_content_length] => 4215
        [upload_content_length] => 3614
        [starttransfer_time] => 2.002198
        [redirect_time] => 0
        [certinfo] => Array
        (
        )

        [primary_ip] => 127.0.0.1
        [primary_port] => 4444
        [local_ip] => 127.0.0.1
        [local_port] => 57884
        [redirect_url] =>
    )
    [sessionId] =>
)
```

**Comment by gfosco** [comment]
Closing this as it is over 6 months old.  If it is still an issue, please create a new issue with as much current reproduction information as possible.  Thanks.

**Comment by ssfinney** [comment]
With the newest versions of Selenium, PhantomJS, and the webdriver module in Codeception, this issue seems to have been fixed along the way.
