### ISSUE TITLE
Official documentation missing concrete examples

### ISSUE THREAD

**Issue by samtuke** [facebook/php-webdriver#179]
How does one use ``WebDriverBy`` for example? Usage has changed, and scattered blogs with examples are often out of date with examples that no longer function. [These docs](https://facebook.github.io/php-webdriver/) are too detailed to be useful for new users.

Please add some examples e.g. looking for element values on GitHub pages to give a brief intro. Even 3 more lines would help here.

**Comment by gfosco** [comment]
Closing this as it is over 6 months old.  If you have specific improvements beyond what exists in example.php, please open a new issue or pull request.  Thanks.
