### ISSUE TITLE
Thoughts about coding style - PSR2?

### ISSUE THREAD

**Issue by OndraM** [facebook/php-webdriver#190]
Hi, as a following of PR #187, I'd like to ask about codingstyle of php-webdriver.

Current coding style is kind of weird, and does not resemble any other PHP coding style. Especially indenting (2 spaces are more usual for javascript and really unusual for PHP), variables $naming_in_underscores (while usual is $camelCase), brace placement and so on. Sometimes it is not even unified. 

This makes readability of the webdriver worse (during tests writing we often study the php-webdriver sourcecode to know how things work), also complicates contributing (almost nobody would have IDE set to current coding style).

I would suggest switching to [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md), as it is the most used and common coding style in current PHP world, it is default for various IDEs and most of new code in most used frameworks and libraries (Symfony, Zend Framework 2, Composer etc.) is in compliance with it, making it de-facto industry standard.

With tools like [code style fixer](http://cs.sensiolabs.org/) the transition is really easy and if you would agree, I'd be glad to participate on it. 

What are your opinions?

**Comment by Tjoosten** [comment]
+1

**Comment by gfosco** [comment]
Closing.. Please see #212
