### ISSUE TITLE
findElements does not throw exception when none found

### ISSUE THREAD

**Issue by jameshd** [facebook/php-webdriver#202]
Using findElement you get an exception, shouldn't findElements throw the same exception [here](https://github.com/facebook/php-webdriver/blob/master/lib/remote/RemoteWebDriver.php#L155-L159) and not leave it to calling code?

**Comment by whhone** [comment]
By design, findElements returns an empty array when there is no element found. 

This is also the trick to check the existence of an element without throwing exception. 

For example, 
```
function hasElement($driver, $by) {
  return count($driver->findElements($by)) > 0;
}
```

**Comment by jameshd** [comment]
Thanks, yeah I'd done something similar in my code, I was just unsure as to why no exception was being thrown. 

Thanks for clarifying

**Comment by omeraslam-vteams** [comment]
well i use this way 
<pre>/**
     * Function :  assertElementNotFound
     * ASSERT ELEMENT NOT FOUND
     * params $by       instance of WebDriverByElement
     * params $element  name of the element used to show in the error message
     */
    protected function assertElementNotFound($by, $element)
    {
        $errorSnaps = '';
        if (!$this->driver->findElements($by)) {
            $errorSnaps = $this->TakeScreenshot();
            $this->fail("The $element was not found on the page" . $this->driver->getCurrentURL());
        }
        // increment assertion counter
        $this->assertTrue(true);
    }</pre>
