### ISSUE TITLE
Issue with firefox 36

### ISSUE THREAD

**Issue by rjacobsen2012** [facebook/php-webdriver#203]
I am trying to use this with selenium 2.45 and firefox 36, and am having all kinds of errors such as:

    Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary    FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows:

    (process:3090): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
    Error: no display specified

    (process:3098): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
    Error: no display specified

I have also tried to use chrome with the following errors:

    org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally

Please advise on what I may be doing wrong? My usage looks as follows:

Chrome:

        $host = 'http://127.0.0.1:4444/wd/hub';

        /** @var WebDriver $driver */
        $driver = RemoteWebDriver::create($host, DesiredCapabilities::chrome());
        $driver->get("https://www.google.com");

        echo $driver->getPageSource();

Firefox:

        $host = 'http://127.0.0.1:4444/wd/hub';

        /** @var WebDriver $driver */
        $driver = RemoteWebDriver::create($host, DesiredCapabilities::firefox());
        $driver->get("https://www.google.com");

        echo $driver->getPageSource();

**Comment by bertramakers** [comment]
To use Selenium with Chrome you need to install [ChromeDriver](https://code.google.com/p/selenium/wiki/ChromeDriver).

Some recent versions of Firefox (I think 35, 36, ...) have a bug that causes WebDriver compatibility to break in Firefox. (See https://code.google.com/p/selenium/issues/detail?id=8399, and there are more)

Downgrading Firefox to a lower version seems to fix the issue. I'm using Firefox 33 right now for exactly this reason.

**Comment by whhone** [comment]
@rjacobsen2012 I think @bertramakers answered all the errors you saw. Closing the issue.
