### ISSUE TITLE
Arrow Down Context Menu

### ISSUE THREAD

**Issue by kjenney** [facebook/php-webdriver#206]
I'm attempting to replicate the Right Click functionality via contextClick along with sendKeys('ARROW_DOWN').

SendKeys requires an element but the element is recoginized by moveMouse. sendKeys is not a function of RemoteMouse. 

How do I pass the sendKeys to the context Menu once it's up?

**Comment by whhone** [comment]
Try using the action builder? `` For example, 
```
$driver->action()
       ->contextClick($element)
       ->sendKeys(WebDriverKeys::ARROW_DOWN)
       ->perform();
```
There are more actions in the class WebDriverActions you can use. https://github.com/facebook/php-webdriver/blob/master/lib/interactions/WebDriverActions.php

**Comment by kjenney** [comment]
I tried using $driver->action() and got this error:

    PHP Catchable fatal error:  Argument 1 passed to WebDriverActions::sendKeys() must implement interface WebDriverElement, string given,

This is my code:

     $element = $driver->findElement(WebDriverBy::CssSelector('img:first-child'));
     var_dump($element->getAttribute('alt'));     // Outputs as expected
     $drive->action()->contextClick($element)->sendKeys(WebDriverKeys::ARROW_DOWN)->perform();

**Comment by kjenney** [comment]
I tried passing $element as the firrst argument of sendKeys but that causes a click action on the image for some reason:

     $drive->action()->contextClick($element)->sendKeys($element,WebDriverKeys::ARROW_DOWN)->perform();

**Comment by kjenney** [comment]
I see an example in Java that uses findElement on the context menu. Would that work in this case, has this been carried over to php-webdriver?

     Actions oAction = new Actions(driver);
     oAction.moveToElement(Webelement);
     oAction.contextClick(Webelement).build().perform();  /* this will perform right click */
     WebElement elementOpen = driver.findElement(By.linkText("Open")); /*This will select menu after right click */
     elementOpen.click();

**Comment by kjenney** [comment]
I figured it out finally by looking over the code. $element is optional but there are two parameters. So to pass sendkeys without specifying an element you need to pass NULL as the first parameter:

      $drive->action()->contextClick($element)->sendKeys(NULL,WebDriverKeys::ARROW_DOWN)->perform();

Sorry for adding a separate question in this thread, I'm still interested in specifying the Context Menu item directly rather than keying down. I'll open up a new issue for this.

**Comment by whhone** [comment]
@kjenney  Cool! Sorry for the missing `NULL` in my example.
