### ISSUE TITLE
Specifying Item in Context Menu

### ISSUE THREAD

**Issue by kjenney** [facebook/php-webdriver#207]
I see an example in Java that uses findElement on the context menu. Is this possible in php-webdriver with Firefox?

     Actions oAction = new Actions(driver);
     oAction.moveToElement(Webelement);
     oAction.contextClick(Webelement).build().perform();  /* this will perform right click */
     WebElement elementOpen = driver.findElement(By.linkText("Open")); /*This will select menu after right click */
     elementOpen.click();

**Comment by gfosco** [comment]
The code seems pretty much the same:

```
$oAction = new WebDriverActions($driver);
$oAction->moveToElement($element);
$oAction->contextClick($element)->perform();
$elementOpen = $driver->findElement(WebDriverBy::linkText('Open'));
$elementOpen->click();
```

Give that a shot and let me know if you have any issues.
