### ISSUE TITLE
assertNotContains reports wrong message

### ISSUE THREAD

**Issue by php-denken** [facebook/php-webdriver#208]
assertNotContains reports "[haystack] does not contain [needle]" as error message if haystack contains needle. It should report something like "[haystack] does contain [needle] and should not". It is a problem with wrong usage of the negation array. Its a negation of a negation.

**Comment by whhone** [comment]
@php-denken Are you using PHPUnit? `assertNotContains` is not a method provided by `php-webdriver`. Try https://github.com/sebastianbergmann/phpunit.

**Comment by php-denken** [comment]
You are right my fault
