### ISSUE TITLE
mousemove and hover not working with firefox

### ISSUE THREAD

**Issue by erwandf** [facebook/php-webdriver#211]
Using firefox 37.0.2 and the following code :
    $element = $this->driver->findElement(WebDriverBy::cssSelector($element));
    $this->driver->getMouse()->mouseMove( $element->getCoordinates() );
    $elementToBeDisplayed = $this->driver->findElement(WebDriverBy::cssSelector(".displayed"));
    $this->assertTrue($elementToBeDisplayed->isDisplayed());

The mouse doesn't move and the element is not displayed on the hover action.

If I'm changing the browser, and using chrome (42.0.2311.135 (64-bit)), the action is well executed, and the element I want to be displayed is visible, and I can click on it.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gfosco** [comment]
Closing this as there hasn't been any engagement.  This does sound more like a webdriver issue as opposed to an SDK bug.  If you have any further information or feel this should be re-opened, go ahead.  Thanks.
