### ISSUE TITLE
Moving forward

### ISSUE THREAD

**Issue by gfosco** [facebook/php-webdriver#212]
In order to support both Facebook internal use and acceptance in the broader community, and considering the slow current slow pace of development (last release tagged 7 months ago,) we should maintain an official community version which is allowed to grow on its own.  

This way, the community can support current practices and interoperate better with other tools.  Important bug-fixes can be made to both versions, and everyone could help review and improve the code.  There are many forks, and some of that can be shared back for the benefit of all.

I've created a branch, community, which can become the default branch.  How about we use that to comply with PSR-2 and add Namespaces, per #204 and #190, and make a 1.0 release?

Any thoughts on this approach?

**Comment by janoszen** [comment]
I have a working version with namespaces here: https://github.com/opsbears/php-webdriver

Saves you some work, just search and replace. :)

**Comment by 0x20h** [comment]
+1

**Comment by OndraM** [comment]
+1, though this would mean rewriting our tests (or at least doing lots of search & replace).

**Comment by janoszen** [comment]
@OndraM Please do check my fork, it's all done.

**Comment by gabrielpreston** [comment]
I'm on board with this as well

**Comment by 0x20h** [comment]
@janoszen Why not prepare a PR?

**Comment by janoszen** [comment]
Any requirements on the namespace part?

**Comment by 0x20h** [comment]
Just some thoughts:
- `Facebook\Webdriver` as root namespace (other proposals?)
- comply to PSR-4 (correct the autoload section in `composer.json`)
- Rename WebdriverException to `Facebook\Webdriver\Exception`
- Generally: follow one class per file
- put exceptions under `Facebook\Webdriver\Exception`

**Comment by janoszen** [comment]
I can do that fairly quickly if that is ok.

**Comment by OndraM** [comment]
@0x20h I would suggest keeping the name Web**D**river. It is also official name of the [W3C standard](http://www.w3.org/TR/webdriver/)..

**Comment by 0x20h** [comment]
@OndraM yep, absolutely. Thanks for the feedback!

**Comment by gfosco** [comment]
I'm :+1: on all of those suggestions @0x20h @OndraM

**Comment by janoszen** [comment]
OK guys, I have made the changes requested to my own repo (see above). It would need some real world testing, so if you have a project, feel free to jump on it. Feedback is also welcome.

**Comment by 0x20h** [comment]
Hey @janoszen, thanks for your work!
Just had a quick look at it. 
I think you should keep the directory structure and create sub namespaces.

**Comment by janoszen** [comment]
Yeah, that wasn't clear. I'll get this done as soon as I have some time.

**Comment by janoszen** [comment]
OK, it's done, but I've done an insane amount of automatic refactoring, so getting a second pair of eyes on the code would be good before the PR.

**Comment by 0x20h** [comment]
FYI, our testsuite seems fine with your branch.
Let's move the discussion to the PR :)

**Comment by gfosco** [comment]
Can we get that submitted as a PR against the community branch here?

**Comment by drjayvee** [comment]
I welcome this approach, as it allows for more centralized development.

I have one tiny PR to contribute: https://github.com/facebook/php-webdriver/pull/217

**Comment by gfosco** [comment]
Ok, we did it!..  :+1:
