### ISSUE TITLE
Webdriver v0.6.0 stalls installation via composer

### ISSUE THREAD

**Issue by tomolas** [facebook/php-webdriver#219]
Webdriver v0.6.0 stalls entire installation via composer.
Seems like there is a corrupted .zip archive. Same thing happens when I tried to extract the file manually. 
This is part of console output from "composer -vvv update":

  ```
- Installing facebook/webdriver (v0.6.0)
Reading /vagrant/.composer/files/facebook/webdriver/2c5b305ea91b00ebbc433ad1663b7f16c1b31ec5.zip from cache
    Loading from cache
    Extracting archive
Executing command (CWD): unzip '/vagrant/web/libs/vendor/facebook/webdriver/95ab95adf32422d1886107cc620208a0' -d '/vagrant/web/libs/vendor/composer/8bf18198' && chmod -R u+w '/vagrant/web/libs/vendor/composer/8bf18198'
```

**Comment by php-denken** [comment]
Your consoleoutput looks ab bit weiter but it says clearly installing from cache. The composer cache is lokaly on your machine. Habe you tried to perform a "composer clear-cache"? This will drop your cache and forces composer to load files fresh form remote repo.

**Comment by tomolas** [comment]
Hi, thanks for answering. Yes. I've tried clearing the cache both manually and by composer clear-cache. 
Output after running composer clear-cache and subsequent composer -vvv update:

```
- Installing facebook/webdriver (v0.6.0)
Downloading https://api.github.com/repos/facebook/php-webdriver/zipball/2c5b305ea91b00ebbc433ad1663b7f16c1b31ec5
    Downloading: 100%         
Writing /vagrant/.composer/files/facebook/webdriver/2c5b305ea91b00ebbc433ad1663b7f16c1b31ec5.zip into cache
    Extracting archive
Executing command (CWD): unzip '/vagrant/web/libs/vendor/facebook/webdriver/b5b503fbc6aa2403f5df6b51ecd417b5' -d '/vagrant/web/libs/vendor/composer/1645bbe0' && chmod -R u+w '/vagrant/web/libs/vendor/composer/1645bbe0'
```

**Comment by tomolas** [comment]
Hi, thanks for answering. Yes. I've tried clearing the cache both manually and by composer clear-cache. 
Output after running composer clear-cache and subsequent composer -vvv update:

```
- Installing facebook/webdriver (v0.6.0)
Downloading https://api.github.com/repos/facebook/php-webdriver/zipball/2c5b305ea91b00ebbc433ad1663b7f16c1b31ec5
    Downloading: 100%         
Writing /vagrant/.composer/files/facebook/webdriver/2c5b305ea91b00ebbc433ad1663b7f16c1b31ec5.zip into cache
    Extracting archive
Executing command (CWD): unzip '/vagrant/web/libs/vendor/facebook/webdriver/b5b503fbc6aa2403f5df6b51ecd417b5' -d '/vagrant/web/libs/vendor/composer/1645bbe0' && chmod -R u+w '/vagrant/web/libs/vendor/composer/1645bbe0'
```

**Comment by gfosco** [comment]
I'm not able to reproduce this, it installs correctly for me through composer... I think this must be something on your end.  Please try from a different machine and/or network.
