### ISSUE TITLE
How to use createBySessionID ?

### ISSUE THREAD

**Issue by hgati** [facebook/php-webdriver#220]
my code is...
```php
// test.php
$obj = RemoteWebDriver::create('http://localhost:8910/wd/hub', DesiredCapabilities::phantomjs());
$session_id = $obj->getSessionID();
for($i=0; $i < 30; $i++){
    $wd = RemoteWebDriver::createBySessionID($session_id, 'http://localhost:8910/wd/hub');
    $wd->get('http://www.6pm.com/nydj-petite-petite-sarah-boot-in-classic-indigo-denim');
    $wd->quit();
}
```

the result is...
```sh
# php -f test.php

PHP Fatal error:  Uncaught exception 'Facebook\WebDriver\Exception\WebDriverException' with message 'JSON decoding of remote response failed.
Error code: 4
The response: 'Variable Resource Not Found - {"headers":{"Accept":"application/json","Content-Length":"85","Content-Type":"application/json;charset=UTF-8","H
ost":"localhost:8910"},"httpVersion":"1.1","method":"POST","post":"{\"url\":\"http:\\/\\/www.6pm.com\\/nydj-petite-petite-sarah-boot-in-classic-indigo-denim\
"}","url":"/session/2c5e8d70-1300-11e5-8ed2-47ede3e62013/url","urlParsed":{"anchor":"","query":"","file":"url","directory":"/session/2c5e8d70-1300-11e5-8ed2-
47ede3e62013/","path":"/session/2c5e8d70-1300-11e5-8ed2-47ede3e62013/url","relative":"/session/2c5e8d70-1300-11e5-8ed2-47ede3e62013/url","port":"","host":"",
"password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/session/2c5e8d70-1300-11e5-8ed2-47ede3e62013/url","queryKey":{},"chunks":["sess
ion","2c5e8d70-1300-11e5-8ed2-47ede3e62013","url"]}}'
' in /var/www/htdocs/matrix/vendor/facebook/web in /var/www/htdocs/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php on line 251
```

how to use createBySessionID? 
Is there an example ?

**Comment by gfosco** [comment]
Closing this as it has not received any engagement.  You may want to ask this on StackOverflow.  Thanks.

**Comment by elliotthill** [comment]
Had a similar issue and solved it. My stack trace is below. In my case this was due to forgetting the '/wd/hub' on the end of the host. I had mine pointing to http://ondemand.saucelabs.com:80, which was causing the issue. Make sure its http://ondemand.saucelabs.com:80/wd/hub. 

A more helpful error message would have been nice :)

	PHP Fatal error:  Uncaught exception 'Facebook\WebDriver\Exception\WebDriverException' with message 'JSON decoding of remote response failed.
	Error code: 4
	The response: 'Unknown command'
	' in /vagrant/www/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:260
	Stack trace:
	#0 /vagrant/www/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(97): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
	#1 /vagrant/www/wp-content/themes/myproject/inc/crons/selenium.php(14): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://ondemand...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 5000)
	#2 {main}
	  thrown in /vagrant/www/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php on line 260
