### ISSUE TITLE
Redundant methods

### ISSUE THREAD

**Issue by tim-bezhashvyly** [facebook/php-webdriver#221]
`WebDriverBy::className()` and `WebDriverBy::id` looks redundant to me as their usecases can be easily covered by `WebDriverBy::cssSelector()`.

**Comment by jameshd** [comment]
Perhaps, however I would imagine they're still perfectly valid to have. 
I've always mused over the performance of CSS selectors over ids/class name selectors. 

We use a [BEM](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) standard and selecting by classname suits us.

**Comment by tim-bezhashvyly** [comment]
Ah, now I see that these are actually methods of Selenium API. For adaptor one-to-one mimicking of API definitely makes sense. Sorry for a hustle.
