### ISSUE TITLE
Timeout Change In HttpCommandExecutor Breaks Many Codeception tests.

### ISSUE THREAD

**Issue by TroyRudolph** [facebook/php-webdriver#222]
About five months ago, a change was made to HttpCommandExecutor that reduced the timeout value from 300,000 milliseconds to 30,000 milliseconds.  The comments indicate that the change corrects a typo.  Nevertheless, it is an order-of-magnitude change.  It causes problems with a number of our Codeception suites and so we are stalled on Codeception 2.0.7 because that timeout value cannot be overridden.

Please see https://github.com/Codeception/Codeception/issues/1984#issuecomment-113561925 for details.

I think that the correct solution is to allow that value to be overridden.  If that is too difficult to do, perhaps, for the short term, you could put it back the way it was. 

Thank you

**Comment by n8whnp** [comment]
Hello, 

I had a similar problem with some pages in our test suite. The setting can be changed when the HttpCommandExecutor is instantiated. However Codeception does not provide support for doing so. I have made a PR to add that support to Codeception's WebDriver module and it looks like it will be accepted. I think php-webdriver can safely close this issue.

**Comment by gfosco** [comment]
We did add the method to allow changing it, and as @n8whnp said once Codeception supports using it, this should be a non-issue.

If you'd like to submit a PR setting the default request timeout back to 300,000, I'll consider it and let others comment.  Thanks.
