### ISSUE TITLE
Modal box dialog

### ISSUE THREAD

**Issue by harikt** [facebook/php-webdriver#225]
Hi, 

I am trying to make use of testing with codeception and in the background as codeception is making use of webdriver, I would like to know how we could make use of modal dialog form submissions / looking for text contents etc .

I had a peep into the http://stackoverflow.com/questions/13936167/how-to-deal-with-modaldialog-using-selenium-webdriver question and it mentions about `driver.switchTo().activeElement()` .

Not sure how I could move forward. Any information to move forward is helpful.

Thank you.

**Comment by n8whnp** [comment]
Hello,

First off, codeception has their own areas to ask these kind of questions and reports should go there first. Try:

https://github.com/Codeception/Codeception

That being said, codeceptions WebDriver module already wraps those calls:

http://codeception.com/docs/modules/WebDriver#switchToWindow

Have a nice day.

**Comment by harikt** [comment]
Thank you @n8whnp , 

I did noticed a question http://phptest.club/t/acceptance-test-for-modal-windows/413 which was not answered. So was here, and I did find a solution for the same.

Thank you.
