### ISSUE TITLE
getKeyboard not work

### ISSUE THREAD

**Issue by dada20042030** [facebook/php-webdriver#226]
my code is 
$driver = RemoteWebDriver::create($host, $capabilities);
$driver->getKeyboard()->sendKeys(WebDriverKeys::CONTROL, 't');

but it not work

my system is windows 7

**Comment by TelmoNeves** [comment]
You made a mistake:

You should use an array instead:

`$driver->getKeyboard()->sendKeys(array(WebDriverKeys::CONTROL, 't'));`
