### ISSUE TITLE
Composer autoloading problem

### ISSUE THREAD

**Issue by theprog** [facebook/php-webdriver#231]
While using following on composer.json -
```
{
  "require": {
    "facebook/webdriver": "dev-master"
  }
}
```

It gets the master branch which doesn't follow psr-4 convention. So need to include that  lib/__init__.php

But if you like autoload then just use

```
composer require "facebook/webdriver"
```

It gets the community branch which have psr-4 convention.

**Comment by gfosco** [comment]
Ok, I just updated the readme to require ~1.0.

Thanks for the catch!
