### ISSUE TITLE
Handling stale elements

### ISSUE THREAD

**Issue by mastermindg** [facebook/php-webdriver#232]
I've got a script that cycles thru pages and it's failing after a few pages. The element is definitely there on all pages but I keep getting an exception.

Here's my code:

    $selector="//a[contains(@title,'Next Page')]";
    $driver->wait()->until(
		\Facebook\WebDriver\WebDriverExpectedCondition::presenceOfElementLocated(
			\Facebook\WebDriver\WebDriverBy::XPath($selector)
		)
	);
    $element = $driver->findElement(\Facebook\WebDriver\WebDriverBy::XPath($selector));
	if ($element->isDisplayed()) {
		$driver->findElement(\Facebook\WebDriver\WebDriverBy::XPath($selector))->click();
	}

I'd expect not to see an error as this should be handling the presence of the element on the page. What am I missing here?

Here's the error:

    PHP Fatal error:  Uncaught exception    'Facebook\WebDriver\Exception\StaleElementReferenceException' with message 'Element is no longer attached to the DOM
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
    Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
    System info: host: 'server', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-48-generic', java.version: '1.8.0_45'
    Driver info: driver.version: unknown' in /opt/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:112
    Stack trace:
    #0 /opt/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php(278): Facebook\WebDriver\Exception\WebDriverException::throwException(10, 'Element is no l...', Array)
    #1 /opt/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(503): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
    #2 / in /opt/vendor/facebook/webdriver/lib/Exception/WebDriverException.php on line 112

**Comment by ernani** [comment]
Not sure if it helps but I am using a try catch block and if there is a stale element I redo the whole thing.

**Comment by gabrielpreston** [comment]
We follow the same principle with a lot of our code as well.

**Comment by Clar64** [comment]
@ernani I sit with the same issue. How do you redo the whole thing?

**Comment by emiglobetrotting** [comment]
this link will you understand what it means http://docs.seleniumhq.org/exceptions/stale_element_reference.jsp; but the best way to deal with this exception is to do what @ernani did for example

    while(<somecondition>){
        try{
             //do something here
             <somecondition> = false
        }catch(StaleElementReferenceException $ex){
             //<somecondition> still true because exception occurred
             //e.g. reset url to previous url before this exception occur
             // or quit driver to redo again
             // or redo a state
            // or test if similar state works in 5 consecutive times then if your original case fails repeatedly after a number of times you can quite to avoid infinite loop.
        }
    }

**Comment by Clar64** [comment]
Thanks!!

**Comment by emiglobetrotting** [comment]
your welcome :)
