### ISSUE TITLE
Firefox existing profile

### ISSUE THREAD

**Issue by theprog** [facebook/php-webdriver#238]
In order to create a new profile the wiki says to use

````
$profile = new FirefoxProfile();
````

But when I already have a profile that have some credential stored with it, how can I use that one instead of creating new ones?

Say I have a profile named selenium on my linux machine in - ~/.mozilla/firefox/random.selenium/
Can I use it instead of creating new one?

I have browsed inside source of FirefoxProfile and FirefoxDriver but I didn't had any clue. Also in issues  I didn't find any previously solved issue for this case.

Thanks

**Comment by AlexMiroshnikov** [comment]
Looks like at the moment you can do as it's described in https://github.com/facebook/php-webdriver/wiki/Launching-Browsers#adding-a-firefox-profile , e.g. http://stackoverflow.com/questions/10559728/uploading-files-remotely-on-selenium-webdriver-using-php .

**Comment by natesreich** [comment]
Could someone provide a working example of this?

It was fairly easy do to with php-webdriver using the WebDriverFirefoxProfile class: https://github.com/Element-34/php-webdriver/blob/master/PHPWebDriver/WebDriverFirefoxProfile.php

**Comment by Leopard123** [comment]
I believe this should do it
```php
use Facebook\WebDriver\Firefox\FirefoxDriver;

$host = 'http://localhost:4444/wd/hub';
$capabilities = DesiredCapabilities::firefox();
$capabilities->setCapability(FirefoxDriver::PROFILE, base64_encode(file_get_contents('pathToProfile.zip')));
$driver = RemoteWebDriver::create($host, $capabilities, 5000);
```

**Comment by gouchaoer** [comment]
wiki is no longer right for lastest version....
I search around php-webdriver/selenium/stackoverflow and find there's no solution for this

**Comment by gouchaoer** [comment]
I hope firefox have a option like chrome`chrome_options.add_argument('--profile-directory=Default')` to set profile directory.

**Comment by gouchaoer** [comment]
I figured it out, see:https://github.com/facebook/php-webdriver/issues/310

**Comment by StasToken** [comment]
**Leopard123** I from your example a little understood - **pathToProfile.zip** this should be a compressed path to the profile? or he compressed profile files?

**Comment by gouchaoer** [comment]
I have move to chromium.
chromium is better

**Comment by StasToken** [comment]
**gouchaoer:** Science trolls have a solution! - Oh, the crutches, the bike is the fork  php-webdriver
 Also the same curve only in there job profile is true, too, needs revision I half rewrote it to be honest but it works-tested [Element-34/php-webdriver](https://github.com/Element-34/php-webdriver)

**Comment by StasToken** [comment]
To be precise the file: [ProfileTest.php
](https://github.com/Element-34/php-webdriver/blob/master/test/ProfileTest.php)
