### ISSUE TITLE
Wrong namespaces used on unit tests

### ISSUE THREAD

**Issue by EvanCoh** [facebook/php-webdriver#242]
Hello! Thank you for the php-webdriver. Excellent work.

I have noticed that on the composer.json you have included:
"autoload-dev": {
    "psr-4": {
      "Facebook\\WebDriver\\": "tests/functional"
    }

And the functional tests are using this namespace, but the unit tests in 'tests/unit' are using the same namespace too. Maybe you should remove the namespaces from the unit tests or change the composer json namespace path to include the unit tests as well.

**Comment by gfosco** [comment]
Care to submit a PR and become a contributor?

**Comment by EvanCoh** [comment]
sure! I am on it. I will remove the namespaces from the unit tests. If in the future you will need them you can change the composer.json accordingly.
