### ISSUE TITLE
Mouse move doesn't work, can't enable native events

### ISSUE THREAD

**Issue by penelern** [facebook/php-webdriver#245]
Hello,

I am trying to move the mouse but it's not working:

05:17:07.548 INFO [14] org.openqa.selenium.remote.server.DriverServlet - Executing: [get: https://www.facebook.com])
05:17:10.658 INFO [14] org.openqa.selenium.remote.server.DriverServlet - Done: [get: https://www.facebook.com]
05:17:10.678 INFO [14] org.openqa.selenium.remote.server.DriverServlet - Executing: [find element: By.id: loginbutton])
05:17:13.250 INFO [14] org.openqa.selenium.remote.server.DriverServlet - Done: [find element: By.id: loginbutton]
05:17:13.270 INFO [14] org.openqa.selenium.remote.server.DriverServlet - Executing: [mousemove: 0 false])
05:17:13.503 INFO [14] org.openqa.selenium.remote.server.DriverServlet - Done: [mousemove: 0 false]
05:17:13.516 INFO [14] org.openqa.selenium.remote.server.DriverServlet - Executing: [click: nothing])
05:17:13.957 INFO [14] org.openqa.selenium.remote.server.DriverServlet - Done: [click: nothing]

I even tried to enable native events:

<?php

namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Remote\WebDriverCapabilityType;
use Facebook\WebDriver\Interactions\Internal\WebDriverMouseMoveAction;
use Facebook\WebDriver\Interactions\Internal\WebDriverMouseAction;
use Facebook\WebDriver\Firefox\FirefoxProfile;
use Facebook\WebDriver\Firefox\FirefoxDriver;

require_once('vendor/autoload.php');

$host = 'http://localhost:4444/wd/hub';
$profile = new FirefoxProfile();
$profile->setPreference('setEnableNativeEvents',true);

$capabilities = array(WebDriverCapabilityType::BROWSER_NAME => 'firefox',
					  FirefoxDriver::PROFILE , $profile);  
$driver = RemoteWebDriver::create($host, $capabilities,50000);

$driver->get("https://www.facebook.com");
$login_button = $driver->findElement(WebDriverBy::id('loginbutton'));
$driver->getMouse()->mouseMove($login_button->getCoordinates());
$driver->getMouse()->click();

//$driver->quit();
?>

Please give a hint on how to make the mouse move.
In about:config:
setEnableNativeEvents is true
but 
webdriver_enable_native_events is false, and stays false even if I setPreference('webdriver_enable_native_events',true);

Thank you in advance.

**Comment by cryptton2004** [comment]
I'm encountering the same issue. I was unable to find a solution so far :(

**Comment by cryptton2004** [comment]
Got it to work by disabling the native events (since they are not supported on the latest browser versions).
