### ISSUE TITLE
How to catch an exception

### ISSUE THREAD

**Issue by cfleck** [facebook/php-webdriver#250]
Hi all. 
I got this code snippet and when it is successful it returns $test == 1. I expected $test to be 0 when it fails, but it isnt. It throws an exception. How can i prevent that?

$test = $driver->wait(10)->until(
	WebDriverExpectedCondition::textToBePresentInElement(
		WebDriverBy::id('id_of_div'),'successful'
	)
);

**Comment by AlexMiroshnikov** [comment]
What's the exception? May be just to wrap this snippet with a corresponding try-catch?
As we can see at https://github.com/facebook/php-webdriver/blob/community/lib/WebDriverWait.php , it's an expected behavior, and i uess you can set `$test = 0` when `wait` throws `NoSuchElementException` exception.

**Comment by cfleck** [comment]
Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\TimeOutException' in /var/www/html/selenium/vendor/facebook/webdriver/lib/WebDriverWait.php:78 Stack trace: #0 /var/www/html/selenium/vendor/facebook/webdriver/fleck.php(71): Facebook\WebDriver\WebDriverWait->until(Object(Facebook\WebDriver\WebDriverExpectedCondition)) #1 {main} thrown in /var/www/html/selenium/vendor/facebook/webdriver/lib/WebDriverWait.php on line 78

Thats the exception.

Tried this now which doesn't work...
try{
	$test = $driver->wait(10)->until(
		WebDriverExpectedCondition::textToBePresentInElement(
			WebDriverBy::id('id_of_div'),'successful'
		)
	);
}
catch(NoSuchElementException $e) {
	$last_exception = $e;
	$test = 0;
}

**Comment by cfleck** [comment]
... got it. Thanks for your suggestion. It was a timeoutexception in my case so the catch had to look like that:

catch(TimeOutException $e) {
	$last_exception = $e;
	$test = 0;
}

**Comment by gabrielpreston** [comment]
All of these custom exceptions are all extended off WebDriverException, which in turn extends off of Exception. You can just do a catch on Exception if you want to catch any and all forms of failures thrown by PHP WebDriver.
