### ISSUE TITLE
Javascript console content

### ISSUE THREAD

**Issue by borgogelli** [facebook/php-webdriver#252]
Using php-webdriver can I read the javascript console content ?

**Comment by gabrielpreston** [comment]
Yup!

https://github.com/facebook/php-webdriver/blob/community/lib/WebDriverOptions.php#L156

**Comment by borgogelli** [comment]
Thank you very much. It's works fine.

**Comment by th3l0g4n** [comment]
Using ```getLog('browser')``` gives me a lot of Browser internal log output but no messages that actually appear in the console, like console.logs or SyntaxErrors.

@borgogelli is this what you wanted and what you get?
