### ISSUE TITLE
findElements() throws exception when no elements found.

### ISSUE THREAD

**Issue by Alexander-0x80** [facebook/php-webdriver#253]
According to the [docs](http://facebook.github.io/php-webdriver/classes/WebDriverSearchContext.html#method_findElements) `findElements()` should return an empty array when no elements are found, but i get a `WebDriverCurlException` when running this snippet : 

    $element = \WebDriverBy::cssSelector("#not_exists tr > td:first-child");
    $found   = $webDriver->findElements($element);

**Comment by gabrielpreston** [comment]
This has been brought up before as well, but I don't think was ever resolved.

**Comment by gfosco** [comment]
Sounds like a relatively easy fix... Contributions welcome!

**Comment by krzysiekpiasecki** [comment]
>> According to the docs findElements() should return an empty array when no elements are found

I't does. This method is just unsafe (missing @throws tag).

WebDriverCurlException signals some kinds of important problems. There is no need to fix it.

**Comment by gfosco** [comment]
:+1:

**Comment by fayce** [comment]
I have the same issue. 
How can I check if an element exist then ?

**Comment by fayce** [comment]
To answer my own question,  the curl exception would happen only if there was an implicit wait.

driver->manage()->timeouts()->implicitlyWait(30);

once removed the implicit wait, findElements() would just return an empty array when no element was found.

**Comment by emilorol** [comment]
I was in a similar situation and I did this with success in case someone is on the same boat.

**1. Under my name space**

```php
use \Facebook\WebDriver\Exception\NoSuchElementException;
```

**2. In my code**

```php
try
{
  $search = $driver->findElement(WebDriverBy::xpath('//*[@id="content"]/p[1]'))->getText();
}
catch (NoSuchElementException $e)
{
  // the element did not exist
  var_dump($e);
}
```

**Comment by OndraM** [comment]
@emilorol However you are using `findElement()` method here, which is supposed to throw `NoSuchElementException` in this case.

The original issue was about `findElements()` (note the **s**) method, which should always return an array - an empty one if no elements were found. However I cannot reproduce this original issue (`findElements()` throwing an exception instead of returning empty array), but if anyone can, an reproducible testcase or pull request is definitely welcome :)

**Comment by emilorol** [comment]
Oh, my bad.

I visit this page looking for a solution on how to tell when the element is not present on the page so that the test will continue on one direction or another.

Thank you.

**Comment by shubhamdxt** [comment]
any one  tell me which method decide that how many test case should be automate in selenium

**Comment by rokaspaulik** [comment]
why this got closed?
