### ISSUE TITLE
Fatal error: Class 'Facebook\WebDriver\Firefox\FilesystemIterator' not found

### ISSUE THREAD

**Issue by foxicatko** [facebook/php-webdriver#259]
File: lib/Firefox/FirefoxProfile.php on line 160 contains reference to FilesystemIterator class with invalid namespace.

Fixes are either to add a 'use' clause or prepend the reference with absolute namespace path (in this case, simple '\').

**Comment by gfosco** [comment]
Fixed by @black-silence, will tag a new version for this correction.  Sorry!
