### ISSUE TITLE
takeScreenshot() not capturing full page

### ISSUE THREAD

**Issue by demichl68** [facebook/php-webdriver#264]
Im using facebook/webdriver with firefox and selenium server 2.48.2.
When calling Facebook webdriver's own
```
takeScreenshot()
```
Method, the screen is captured, but only the visible part of it. 
I need to capture the whole screen as im using webdriver to automate email campaign tests.
Is there any native way to do this, or will I have to capture multiple screens scrolling down?

I'm just a little bit confused, as the webdriver wiki has a page called "Taking Full Screenshot and of an Element", but it's definitely not taking full screenshots.

**Comment by DGCarramona** [comment]
The JSON Wire Protocol says about screenshot "Take a screenshot of the current page". So, I think it's not possible to implement the screenshot of the whole page (event not visible parts).
