### ISSUE TITLE
WebDriverWait does not respect 0s wait

### ISSUE THREAD

**Issue by oehlschl** [facebook/php-webdriver#265]
Due to the coalesce operator [here](https://github.com/facebook/php-webdriver/blob/community/lib/WebDriverWait.php#L38), WebDriverWait overwrites a requested wait of 0s with the default 30s. That behavior is both non-obvious and not well documented, and pass-throughs of wait arguments are common enough in packages that include the Facebook WebDriver that it's not unreasonable to expected an argument of 0 intended to disable a wait call.

This could be solved if that line were an isset() instead of a coalesce.

**Comment by gfosco** [comment]
Interested in sending in a PR to alter this behavior?  And, if anyone else feels differently, please speak up.  Thanks.

**Comment by oehlschl** [comment]
I don't have a Facebook account and thus can sign the licensing agreement
apparently required of a pull request, otherwise I would have led with that.

**Comment by oehlschl** [comment]
*cannot

**Comment by gfosco** [comment]
Ok, please review #267 for me.
