### ISSUE TITLE
getPageSource() bug! (firefox)

### ISSUE THREAD

**Issue by mihutz** [facebook/php-webdriver#266]
When trying to get page source after navigating to an url which contains "#"(bookmark) I recieve the last source before the current get().

Example:
$webdriver->get('http://www.domain1.com');
echo md5($webdriver->getPageSource()); // source1
$webdriver->get('http://www.domain1.com/anotherRoute#test');
echo md5($webdriver->getPageSource()); // source2 == source1

If I change the domain:
$webdriver->get('http://www.domain1.com');
echo md5($webdriver->getPageSource()); // source1
$webdriver->get('http://www.domain2.com/anotherRoute#test');
echo md5($webdriver->getPageSource()); // source1 != source2

I made some test locally and the webbrowser navigated correctly. Only the html sources got by selenium are the same.

=====

 There is no ajax, just the #bookmark which will scroll down the page. I investigate more into this and I found that selenium doesn't wait for the browser to complete the loading if you try to navigate to an url from the same domain if there are any bookmarks(it just send the orders to the browser without any waiting). When you navigate to another url , then everything is fine and selenium waits for the browser to finish the loading for the first page and navigate to the next page only after loading is completed.

Thanks!

**Comment by gfosco** [comment]
Interesting... So you're saying that domain1.com and domain1.com/anotherRoute don't contain the same source?...  Can you create a unit test that fails here?
