### ISSUE TITLE
ChromeDriverService port check

### ISSUE THREAD

**Issue by akhillb** [facebook/php-webdriver#268]
How about we use fsockopen function to check if the port 9515 is free and then use it? I was also thinking we could have a list of some three to five ports which would be used if 9515 was not available. I would also be happy to submit a PR if you think this approach looks good.
Thanks.

**Comment by gfosco** [comment]
I'd be willing to review a PR for this, sure.

**Comment by maximus1127** [comment]
```
        $digits = 4;
        $port = rand(pow(10, $digits - 1), pow(10, $digits) - 1);
        $args = ['--port=' . $port];
```
I got around it by adding this in `ChromeDriverService.php`. It takes any 4 digit port and randomly uses it. My use case is very minimal and this simple work around is good for me. If anyone tries this in the future and needs more custom checks, you could use this code that I found on another article:

```
    $fp = @fsockopen($ip, $portt, $errno, $errstr, 0.1);
    if (!$fp) {
        return false;
    } else {
        fclose($fp);
        return true;
    }
```
I'd imagine that you can set up an array of desired ports and loop over them to see if each one is available then stop when you reach the first available one. This is just a simple way to use a custom range of ports on launch to have multiple drivers running in sync without clashing with each other.

**Comment by andrewnicols** [comment]
This is nasty. I'd advice _not_ doing this.

If you need multiple chromedriver instances and cannot pre-configure how they will be distributed, then you would be much better off using Selenium and having it manage the grid for you. That is the purpose of Selenium. Doing this is gross and does not belong in the driver.
