### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by OndraM** [facebook/php-webdriver#275]
Current project is missing its changelog, making it hard to see human-readable differences between released versions. Only possibility is to check git logs, which is not always helpful (inconsistent commit messages, clutter in the diff etc.). When updating to each new php-webdriver version, I always struggle to see what happened in the repository, what is new, what has changed etc. :-(.

So I suggest adding CHANGELOG.md file in common format described on http://keepachangelog.com/.

Ideally, each PR would directly contain what was changed line in the changelog's Unreleased section (or if it is missing, it could be added after the merge). Once there is a release of a new version, the Unreleased header is changed to the current version (and re-added empty on the top of the file, so PR won't make conflicts) and so on.

What do you think? @gfosco?

**Comment by gfosco** [comment]
I hear where you're coming from, and I'd be supportive if people submitted in this way.  I can't promise to always enforce it, but yeah lets add a changelog going forward.. Would you like to send a PR updating the contribution guidelines and getting us started?

**Comment by OndraM** [comment]
Ok, no problem, I'll send it soon :). Thanks for support!
