### ISSUE TITLE
how to setup and get started

### ISSUE THREAD

**Issue by emiglobetrotting** [facebook/php-webdriver#276]
i'm a newbie trying to use your php-webdriver. i have run the selenium-server jar file on terminal. and i have done the git clone to obtain the php-webdriver as well. trying to run the example.php but having this error PHP Warning:  require_once(vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/nginx/html/php-webdriver/example.php on line 9
PHP message: PHP Fatal error:  require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/src/php-5.6.13/lib/php') in /usr/share/nginx/html/php-webdriver/example.php on line 9"

**Comment by php-denken** [comment]
Have a look at the readme file https://github.com/facebook/php-webdriver#installation

the composer dependencies are missing on your dev env.

**Comment by emiglobetrotting** [comment]
thanks for the reply. i've run the command to install the composer but received this error below

Some settings on your machine make Composer unable to work properly.
Make sure that you fix the issues listed below and run this script again:

The json extension is missing.
Install it or recompile php without --disable-json

The phar extension is missing.
Install it or recompile php without --disable-phar

The filter extension is missing.
Install it or recompile php without --disable-filter

The hash extension is missing.
Install it or recompile php without --disable-hash

The openssl extension is missing, which means that secure HTTPS transfers are impossible.
If possible you should enable it or recompile php with --with-openssl

What and what should I enable or disable?

**Comment by emiglobetrotting** [comment]
this is my php config

./configure \
    --prefix='/usr/local/src/php-5.6.13' \
    --disable-cgi \
    --with-libdir='/lib/x86_64-linux-gnu/' \
    --with-config-file-path='/etc/php5' \
    --with-openssl \
    --with-curl \
    --with-zlib \
    --with-pcre-regex \
    --with-mysql \
    --with-pdo-mysql \
    --with-mysqli \
    --enable-mysqlnd \
    --enable-pcntl \
    --enable-debug \
    --enable-maintainer-zts \
    --enable-mbstring \
    --enable-bcmath \
    --enable-exif \
    --enable-ftp \
    --enable-soap \
    --enable-sockets \
    --enable-opcache \
    --enable-zip \
    --enable-embedded-mysqli \
    --with-fpm-user=www-data  \
    --with-fpm-group=www-data \
    --enable-fpm \
    --enable-session

**Comment by gfosco** [comment]
This troubleshooting would probably be better solved on StackOverflow, or the composer repo: https://github.com/composer/composer
