### ISSUE TITLE
how to create $session variable or object instance

### ISSUE THREAD

**Issue by emiglobetrotting** [facebook/php-webdriver#280]
I am trying to create and use $session variable or object instance as given on these links https://github.com/facebook/php-webdriver/wiki/Launching-browsers, https://github.com/facebook/php-webdriver/wiki/Selectors, but when applied in my script i'm receiving an error that WebDriver interface cannot be instantiated, which is true. So how can I create the $session variable to use?

**Comment by gabrielpreston** [comment]
Can you provide an example of your code?

**Comment by emiglobetrotting** [comment]
thank you for willing to help me. 

  <?php

	use Facebook\WebDriver\Remote\DesiredCapabilities;
	use Facebook\WebDriver\Remote\RemoteWebDriver;
	use Facebook\WebDriver\Remote\WebDriverCapabilityType;
	use Facebook\WebDriver\WebDriverDimension;
	use Facebook\WebDriver\WebDriverBy;
	use Facebook\WebDriver\WebDriver;

  	require_once('vendor/autoload.php');

  	$host = 'http://localhost:4444/wd/hub'; 
  	$capabilities = DesiredCapabilities::firefox();
  	$driver = RemoteWebDriver::create($host, $capabilities);

	$window = new WebDriverDimension(1024, 768);
	$driver->manage()->window()->setSize($window);
	$driver->get('https://web.facebook.com/login.php');

	$inputUsername = $driver->findElement(
		WebDriverBy::xpath('.//input[@id="email"]')
	);
	$inputUsername->sendKeys('your_username');
	
	$inputPassword = $driver->findElement(
		WebDriverBy::xpath('.//input[@id="pass"]')
	);
	$inputPassword->sendKeys('your_password');
	
  	$button = $driver->findElement(
      	WebDriverBy::xpath('.//input[@id="u_0_2"]')
  	);
  	$button->click();

	$sScriptResult = $session->executeScript('return window.document.location.hostname',array());

	echo $sScriptResult;

	header('Content-Type: image/png');

	echo $driver->takeScreenshot();

**Comment by emiglobetrotting** [comment]
i think i can create and use a session variable this way

 $sessions = RemoteWebDriver::getAllSessions($host);
 $session = RemoteWebDriver::createBySessionID($sessions[0]['id'],$host);
 $sScriptResult = $session->executeScript('return window.document.location.hostname',array());

however, the $driver object can also be used to call the same RemoteWebDriver methods

 $sScriptResult = $driver->executeScript('return window.document.location.hostname',array());

 print_r($sScriptResult);

 Hence I wish to close this issue.
