### ISSUE TITLE
Bad Link in readme for DesiredCapabilities Wiki

### ISSUE THREAD

**Issue by phpdave** [facebook/php-webdriver#283]
in the readme change

See https://code.google.com/p/selenium/wiki/DesiredCapabilities for more details.

to 

See [https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities](https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities) for more details.

**Comment by DGCarramona** [comment]
You're right ! I'll do a PR this weekend, if I have enough time.

**Comment by 0x20h** [comment]
@phpdave It's so simple to propose the change yourself, even straight from the github website. Just give it a try, edit the readme, create a PR and experience the magic of open source contributions :heart:

**Comment by phpdave** [comment]
@0x20h @DGCarramona Didn't realize how easy github has made it recently.  I've made the PR  https://github.com/facebook/php-webdriver/pull/290

**Comment by 0x20h** [comment]
Nice :smile:!
