### ISSUE TITLE
is the facebook page down? Or am I being banned?

### ISSUE THREAD

**Issue by Oonabe** [facebook/php-webdriver#286]
Hi,

I'm trying to join the group in facebook because I have some questions. The first try to join in seemed not to get acces and now facebook is telling me that the content is not available, maybe because of changes being made in the group, the link not working anymore or me not having access to the page anymore.

Is something wrong with the group link? Can I join in or check if I'm being banned, even when I couldn't even join in?

**Comment by gfosco** [comment]
If you have a brand-new Facebook account and are a member of no other groups, you may have been refused access.  The page isn't down.

**Comment by Oonabe** [comment]
Yes, it seems like access was refused. I just wanted to get help on an issue I'm having to get php-webdriver working, I'll post it here on GitHub so I may get some help, as I can't join the facebook group, thanks for your answer.
