### ISSUE TITLE
Is there a known solution for the "Class not found" Problem?

### ISSUE THREAD

**Issue by Oonabe** [facebook/php-webdriver#287]
Hi,

I've tried to install php-webdriver following the steps you describe here. I'm getting a problem that seems to happen with some frequency to newbies like me on getting this webdriver client to work.

Everything with the installation seems to be ok, but then when I try to run a test script I always get the same error: "PHP Fatal Error: Class Facebook\WebDriver\WebDriverTestCase' not found in...'.

Sometimes is that class on that weird path, as I know that the class itself isn't there, but it was just an example, when I try some other tests with different classes I still get the error, not always leading to that path.

I've tried everything I found on the internet, I put the require 'autoload.php' command on the test files, I changed the version of phpunit in composer.json to the latest version, which I installed on my computer, or at least >=4.2.0, I tried to remove the -dev declaration on calling php-webdriver or phpunit in composer, I erased everything and started the whole installation again, making sure I follow every step as here described but still get this class not found problem.

Am I missing something? Why does the latest version of php-webdriver still require phpunit 4.2.0 when the latest stable version is already 5.2.9?

I'd thank any help on this, since I already wasted too days at work searching for a solution.

Cheers and thanks in advance.
Dave.

**Comment by Oonabe** [comment]
Hi, I dismissed this php webdriver client for now as I'm working on a project for my formation that has a deadline near in the future, I've erased everything as I'm working with Selenium WebDriver in Java so I'll close this subject.

Maybe I'll try it again in the future and if the problem persists I'll ask again. I've seen this same question in stackoverflow, but curiously the answer was to come ask here or in the facebook group :), as I'm not given permission to access the fb group this is the only possible way for me to ask.

Anyway, thanks for answering,
Dave.

**Comment by Eddcapone** [comment]
Is there a solution yet?

**Comment by OndraM** [comment]
@Eddcapone Solution for what exactly :)?

**Comment by Eddcapone** [comment]
For the problem described by @Oonabe

**Comment by sherylroberts** [comment]
I need help with this too. I don't know how to make certain classes load. I've been trying to make "WebDriverBy" to autoload but its not happening.
