### ISSUE TITLE
How to read data from excel file to use in scripts?

### ISSUE THREAD

**Issue by aseemaneja** [facebook/php-webdriver#288]
How to read data from excel file to use in scripts?

**Comment by 0x20h** [comment]
I think its ok to have it in the repo
https://getcomposer.org/doc/02-libraries.md#lock-file

**Comment by emiglobetrotting** [comment]
in what language, though it's a wrong question from here. checkout how to read excel file with <your preferred language> via google search engine you will definitely find solutions.

**Comment by gabrielpreston** [comment]
@aseemaneja - This question is not really meant for php-webdriver. Google how to parse Excel files in PHP.

**Comment by aseemaneja** [comment]
Yes, you are right. Earlier I tried to get the excel values via php-webdriver but then I try with direct php to get those values, which solved my problem.. anyways thanx for your response !!
