### ISSUE TITLE
timeout exception parallelization and selenium grid

### ISSUE THREAD

**Issue by blowAss** [facebook/php-webdriver#291]
Hi guys,

I am using webdriver on **dev-master#39d8be53309457458c4e023a9899a603c9be36d2** revision. And it works ok when I run several bamboo builds simultanoiusly. We have tests paralelization + we are using Selenium grid.

After updates to the newest versions some of tests begin failing with next error:

Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"firefox","platform":"ANY","javascriptEnabled":true,"nativeEvents":false}}

Operation timed out after 30000 milliseconds with 0 bytes received.

Issue disappears after roll back to the commit I  provided.

Desired capabilities:
$capabilities =  array(
            WebDriverCapabilityType::BROWSER_NAME       => "firefox"
            WebDriverCapabilityType::PLATFORM           => WebDriverPlatform::ANY,
            WebDriverCapabilityType::JAVASCRIPT_ENABLED => true,
            WebDriverCapabilityType::NATIVE_EVENTS      => false,
        );
 $this->webDriver = RemoteWebDriver::create(
            $this->seleniumHost,
            $capabilities,
            5000 
        );

Testsed on Tags: 1.1.1; 1.1.0; v0.6.0

BR,
Slava

**Comment by 0x20h** [comment]
I think the request and connect timeout behavior has changed and was decreased since the commit you referenced. Maybe that is your problem in your parallelized setup? You could try to set increased timeouts when using `RemoteWebDriver::create()` and give it try.

**Comment by 0x20h** [comment]
Especially `$request_timeout_ms` should be increased (was 0 before and thus unlimited) as it is set to 30sec by default now (matching your error message).
I think we should probably increase the default for this timeout.

@blowAss can you verify that this setting affects your test stability?

**Comment by blowAss** [comment]
many thanks will try and let you know

**Comment by blowAss** [comment]
Especially $request_timeout_ms should be increased (was 0 before and thus unlimited)

**Comment by 0x20h** [comment]
At least 
https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT_MS.html
says so.

**Comment by blowAss** [comment]
Seems it helped. Many thanks. Also I have sucess expirinace in connecting appium with facebook wd. Should I post the how to somwhere ?

**Comment by emiglobetrotting** [comment]
if you are having timeout issues, visit #12277

**Comment by emiglobetrotting** [comment]
> https://github.com/ariya/phantomjs/issues/12277#issuecomment-182862026

**Comment by blowAss** [comment]
issue can be closed. Thanks
