### ISSUE TITLE
phantomjs click() erroring when using a custom user-agent

### ISSUE THREAD

**Issue by BenMorel** [facebook/php-webdriver#293]
Reproduce script:

```php
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Remote\WebDriverCapabilityType;
use Facebook\WebDriver\Remote\WebDriverBrowserType;
use Facebook\WebDriver\WebDriverBy;
use Facebook\WebDriver\WebDriverPlatform;

$phantomJsPath = './phantomjs'; // set your own path here
$userAgent = 'UserAgentTest'; // try replacing with 'WebKit', it works!

$capabilities = [
    WebDriverCapabilityType::BROWSER_NAME => WebDriverBrowserType::PHANTOMJS,
    WebDriverCapabilityType::PLATFORM => WebDriverPlatform::ANY,
    'phantomjs.binary.path'=> $phantomJsPath,
    'phantomjs.page.settings.userAgent' => $userAgent
];

$host = 'http://localhost:4444/wd/hub';
$driver = RemoteWebDriver::create($host, $capabilities);

$driver->get('https://en.wikipedia.org/wiki/Main_Page');
sleep(3);

$driver->findElements(WebDriverBy::cssSelector('#p-navigation li a'))[1]->click();
sleep(3);

$driver->quit();
```

Result:

> PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnknownServerException: {"errorMessage":"undefined is not an object (evaluating 'B(A(a)).getComputedStyle(a,null).MozTransform.match')","request":{"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"27","Content-Type":"application/json; charset=utf-8","Host":"localhost:16354","User-Agent":"Apache-HttpClient/4.5.1 (Java/1.8.0_77)"},"httpVersion":"1.1","method":"POST","post":"{\"id\":\":wdc:1459518054699\"}","url":"/click","urlParsed":{"anchor":"","query":"","file":"click","directory":"/","path":"/click","relative":"/click","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/click","queryKey":{},"chunks":["click"]},"urlOriginal":"/session/58e41a50-f80f-11e5-9ec5-8b135ca6318f/element/:wdc:1459518054699/click"}}
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'localhost.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.versio in /mnt/hgfs/www/selenium-test/vendor/facebook/webdriver/lib/Exception/WebDriverException.php on line 118
Segmentation fault (core dumped)

If I use another browser, e.g. `$capabilities = DesiredCapabilities::firefox()`, it works.

More interestingly, **if I replace the user-agent string with anything containing `WebKit`, it works!** I found this weirdness while looking for the error on Google in a similar [ghostdriver issue](https://github.com/detro/ghostdriver/issues/325).

So I'm not sure whether this is a problem with `php-webdriver`, `selenium-server`, or with `phantomjs`?

The related segmentation fault is worrying, as well. Probably a PHP bug that should be reported if it can be isolated.

I'm using php-webdriver `1.1.1`, selenium-server-standalone `2.53.0` and phantomjs `2.1.1` on PHP `7.0.5`.

**Comment by 0x20h** [comment]
Hey @BenMorel,
I can reproduce the error you describe. However, I'm also getting the same results when using i.e. webdriver.io. I don't think it's related to webdriver-php, but rather a phantomjs issue.

**Comment by BenMorel** [comment]
@0x20h Thanks for testing with webdriver.io! I reported the issue to PhantomJS, let's wait & see.
