### ISSUE TITLE
Can only set Cookies for the current domain

### ISSUE THREAD

**Issue by gouchaoer** [facebook/php-webdriver#297]
I use selenium php-webdriver to set cookie on chrome and phantomjs.
On chrome, it is all right.
But on phantomjs, I got the exception:Can only set Cookies for the current domain, which is located at:https://github.com/ariya/phantomjs/blob/master/src/ghostdriver/request_handlers/session_request_handler.js#L752
I have read this issue:https://github.com/facebook/php-webdriver/issues/294, and I am sure that the $driver had finished loading current url.
![qq 20160426135404](https://cloud.githubusercontent.com/assets/5207582/14808324/fa830f14-0bb6-11e6-9163-f513abfd90fc.png)
I also explicitly set the cookie domain to current url but failed.

This question:http://stackoverflow.com/questions/30292025/ on stackoverflow is highly related but also failed to solve my problem.

Could you give me some idea?

**Comment by OndraM** [comment]
Looks like a phantomjs problem - setting the cookie is responsibility of the WebDriver implementation (GhostDriver in phantomjs), nothing that could be changed by php-webdriver.

If you think this is somehow affected by php-webdriver library, fell free to open a new bug.

Thank you!
