### ISSUE TITLE
Need additional Firefox config option to disable addon signing

### ISSUE THREAD

**Issue by adam-nielsen** [facebook/php-webdriver#303]
There are some issues with Selenium [not working with recent versions of Firefox](https://github.com/SeleniumHQ/selenium/issues/1350).  It turns out this is because Firefox requires add-on signing, the Selenium WebDriver add-on is not signed, so Selenium cannot remote control Firefox.

As a workaround, the Firefox profile can be modified to disable add-on signing, e.g.:

	$caps = Facebook\WebDriver\Remote\DesiredCapabilities::firefox();
	$profile = $caps->getCapability(Facebook\WebDriver\Firefox\FirefoxDriver::PROFILE);
	$profile->setPreference("xpinstall.signatures.required", false);
	$caps->setCapability(Facebook\WebDriver\Firefox\FirefoxDriver::PROFILE, $profile);
	$webDriver = Facebook\WebDriver\Remote\RemoteWebDriver::create(
	    'http://localhost:4444/wd/hub', $caps
	);

I see in `DesiredCapabilities::firefox()` it is already setting a user preference, so would it be possible to also set `xpinstall.signatures.required` to `false` in here, so that the unsigned Selenium addon can still run?

**Comment by OndraM** [comment]
This won't help, as this configuration option will not be available since Firefox 48, see https://wiki.mozilla.org/Add-ons/Extension_Signing

The current extension-based Firefox WebDriver won't work in FF 48+.

We would probably need to either start using the Marionette driver in Firefox 48 or stick with Firefox ESR.

**Comment by myBestSoftAndPref** [comment]
How to override the Firefox Add-on Signing requirement
http://www.ghacks.net/2016/08/14/override-firefox-add-on-signing-requirement/

**Comment by OndraM** [comment]
This is solved by Geckodriver https://github.com/mozilla/geckodriver in Firefox 48+, which replaces the WebDriver addon implementation.
