### ISSUE TITLE
Right click and arrow down

### ISSUE THREAD

**Issue by sawa74** [facebook/php-webdriver#304]
I want to use right click and select 'save as' to save an image, the following code just open the contextual menu but the arrow down is not working (i'm using chrome driver) :

$driver->action()->contextClick($img)->sendKeys(NULL, WebDriverKeys::ARROW_DOWN)->perform();

Is this possible ?

**Comment by gohelkiran** [comment]
what is value of $img?

**Comment by OndraM** [comment]
@sawa74 What browser in which version do you use?
