### ISSUE TITLE
Doesn`t work css selector with square brackets in WebDriverBy::cssSelector

### ISSUE THREAD

**Issue by twopizza** [facebook/php-webdriver#306]
I try to do 
`$elements = $this->driver->findElements(WebDriverBy::cssSelector(".profile-item['data-id'={$postId}]"));`
and getting exception
Facebook\WebDriver\Exception\InvalidSelectorException
invalid selector: An invalid or illegal selector was specified (Session info: chrome=51.0.2704.103) (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 25 milliseconds For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58' System info: host: 'Username-PC', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91' Driver info: org.openqa.selenium.chrome.ChromeDriver Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b), userDataDir=C:\Users\ADMINI~1\AppData\Local\Temp\scoped_dir12820_11226}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=51.0.2704.103, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}] Session ID: 7eedec748dbae8de1b1e2cd0fab87bda *** Element info: {Using=css selector, value=.profile-item['data-id'=717682055]}

Does it support css selectors with square bracket?

**Comment by gabrielpreston** [comment]
Try changing it to this. We don't have any problems using the square brackets in our selectors.

```
$elements = $this->driver->findElements(WebDriverBy::cssSelector(".profile-item[data-id='{$postId}']"));
```

**Comment by OndraM** [comment]
@twopizza Looks like an error in your selector - the single quotes should be around the value, not the key - as noted by @gabrielpreston . Thanks!
