### ISSUE TITLE
Firefox  Marionette suport

### ISSUE THREAD

**Issue by webmailcontatos** [facebook/php-webdriver#307]
Since selenium version 2.53.0  firefox 47 does not work. To use the Firefox browser will need to add support to the Marionette. Marionette, the next generation of FirefoxDriver. How can we solve this?

**Comment by z3liu** [comment]
I had the same problem. Look forward to a solution.

**Comment by borgogelli** [comment]
I use facebook/php-webdriver and the folowing commands work with Chrome driver, Firefox (Selenium built-in driver), PhantomJs and Safari but not with Marionette.

The code:
`$types = self::$webDriver->manage()->getAvailableLogTypes();`

The error:
`exception 'Facebook\WebDriver\Exception\UnknownServerException' with message 'GET /session/..../log/types did not match a known command `

Are there any other solutions to read the browser console ?

Regards

**Comment by OndraM** [comment]
@webmailcontatos Selenium 2.53.0 did not work with Firefox 47.0.0 due to bug in Firefox. However, Firefox 47.0.1 and Selenium 2.53.1 should be compatible. See https://github.com/SeleniumHQ/selenium/issues/2110.

The Marionette will AFAIK be necessary from Firefox 48 onwards.

**Comment by phpdave** [comment]
Looking at the examples at https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

It seems like all we'll need to do is set marionette to true in the desiered capabilities?  Or am I missing something?

```
$capabilities = DesiredCapabilities::firefox();
$capabilities->setCapability('marionette', true);
```

**Comment by webmailcontatos** [comment]
Not work form me

**Comment by OndraM** [comment]
@webmailcontatos Just checked against SauceLabs and Firefox 47 with `$capabilities->setCapability('marionette', true);` and works for me. What error do you get?

However, Marionette in FF 47 is uncomplete and I suggest to wait for FF 48 (which is scheduled to release for today) to get better WebDriver support.

But this has nothing to do with php-webdriver - there is no problem on its side, so I suggest closing this issue, cc @gfosco .

**Comment by webmailcontatos** [comment]
I get this error : 
"The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/jgraham/wires. The latest version can be downloaded from https://github.com/jgraham/wires"

**Comment by OndraM** [comment]
@webmailcontatos Hi, were you able to fix the problem? What code exactly do you use to create the instance of WebDriver?

**Comment by webmailcontatos** [comment]
I used this code : 
`<?php
$host = 'http://localhost:4444/wd/hub';
$profile = new Firefox\FirefoxProfile();
$capabilities = DesiredCapabilities::firefox();
$capabilities->setCapability(Firefox\FirefoxDriver::PROFILE, $profile);
$capabilities->setCapability('marionette', true);
$driver = RemoteWebDriver::create($host, $capabilities, 5000);`

**Comment by OndraM** [comment]
@webmailcontatos And how do you start Selenium server? What version of Selenium server do you use, please?

**Comment by webmailcontatos** [comment]
With version Selenium 3.0.0 it works. Now I will use only this version, thanks for you attention

**Comment by rageai** [comment]
@OndraM launch your selenium server like this
java -jar selenium...blah.jar -Dwebdriver.gecko.driver=/path/to/your/geckodriver
get gecko for your os here
https://github.com/mozilla/geckodriver/releases
also, you might want to add the location of your geckodriver to your system environment path.

**Comment by OndraM** [comment]
Selenium 3.0.1 + latest Firefox are definitely working (though there are some incomplete features in GeckoDriver, so lets hope Mozilla will fix them soon). So closing the issue now. 

Don't forget to define path to geckodriver like this:
```bash
$ java -Dwebdriver.gecko.driver="/opt/bin/geckodriver" -jar vendor/bin/selenium-server-standalone-3.0.1.jar
```

Also be aware of an issue with proxy settings in Firefox 48+ - https://github.com/facebook/php-webdriver/issues/334
