### ISSUE TITLE
why `\Facebook\WebDriver\Firefox\FirefoxProfile()` does not support a file path construction?

### ISSUE THREAD

**Issue by gouchaoer** [facebook/php-webdriver#309]
in java or c# version selenium driver, they all support a profile path to construct a FirefoxProfile object.
but in php-webdriver, it does not support. I really need this feature.
could you tell me how to do this?
thanks!

**Comment by cprn** [comment]
Do you mean something like that?
```sh
zip -r profile 3rkomsuo.selenium
openssl base64 -in "profile.zip" -out "profile.zip.b64"
```
...and then in your code:
```php
$session = $web_driver->session('firefox', array(
    'firefox_profile' => file_get_contents("profile.zip.b64")
));
```

(copied from #42)
