### ISSUE TITLE
how to retain firefox cache?

### ISSUE THREAD

**Issue by gouchaoer** [facebook/php-webdriver#310]
I am crawling a site with a lot of static files such as js,css and images.
But everytime i start a firfox session, i need to download everything again and again.
I need to cache those static files.
there are 2 threads in stackoverflow to discuss this, but they all not work.

http://stackoverflow.com/questions/22685755/retaining-cache-in-firefox-and-chrome-browser-selenium-webdriver

http://stackoverflow.com/questions/25623705/selenium-retaining-firefox-cache-and-history-files

i want to know how to retain firefox cache.
a php example code snippet will be great.

sharing firefox profile like this https://github.com/facebook/php-webdriver/issues/238 is not working.

**Comment by gouchaoer** [comment]
i finally figured it out how to retain firefox cache.
selenium standalone accept `-Dwebdriver.firefox.profile=default -Dwebdriver.reap_profile=true`, which means new selenium firefox instance should copy the profile from default firefox profile(include the cookies and cache). but this is useless in php-webdriver. 
actually, php-webdriver will send a "firefox_profile" parameters to the selenium standalone such as:
```
{"desiredCapabilities":{"browserName":"firefox","platform":"ANY","firefox_profile":balabala,""proxy":{"proxyType":"manual","ftpProxy":"127.0.0.1:8888","httpProxy":"127.0.0.1:8888","sslProxy":"127.0.0.1:8888"}}}

```
if selenium standalone see a firefox_profile in the json, it will ignore the `-Dwebdriver.firefox.profile=default` and start a empty new profile.

but if you delete the firefox_profile parameter, selenium standalone will use the `-Dwebdriver.firefox.profile=default` again.

**Comment by gouchaoer** [comment]
keep in mind that the firefox cache path is not in the default profile(see it by about:cache in firefox), so you should explicitly set a `browser.cache.disk.parent_directory` to make new firefox instance extends the cache path. then firefox cache retains.
remember only one instance can extends the cache(the cache directory is locked by the one firefox instance).
if you need to run multiple firefox instances concurrently and retain cache. And at the same time you need to control cookies, user-agent and image-loading and so on. 
since you can't pass 'firefox_profile' parameter to selenium standalone again. so I can give you a hint.

this cost me one week.
you can custom your firefox instance by directly modify the `prefs.js` whenever you start a new firefox session.
that's quite hard to figure it out. hope to help you.

**Comment by OndraM** [comment]
Thanks for your findings @gouchaoer!
