### ISSUE TITLE
PHP Fatal error:  Interface 'Facebook\WebDriver\WebDriverCapabilities'

### ISSUE THREAD

**Issue by osizanup** [facebook/php-webdriver#313]
1.php

`/*01*/    <?php`

`/*02*/`

`/*03*/	require "php-webdriver/lib/__init__.php";`

`/*04*/	$host = 'http://localhost:4444/wd/hub';`

`/*05*/`

`/*06*/	/*********************Firefox********************/`

`/*07*/	$driver = RemoteWebDriver::create($host, DesiredCapabilities::firefox());`

`/*08*/	`

`/*09*/	/*********************Chrome********************/`

`/*10*/	// $driver = RemoteWebDriver::create($host, DesiredCapabilities::chrome());`

`/*11*/	`

`/*12*/	$driver->get("http://google.com");`

`/*13*/	$element = $driver->findElement(WebDriverBy::name("q"));`

`/*14*/	if($element) {`

`/*15*/		$element->sendKeys("TestingBot");`

`/*16*/		$element->submit();`

`/*17*/	}`

`/*18*/	print $driver->getTitle();`

`/*19*/	$driver->quit();`

`/*20*/    ?>`

I've an error
`PHP Fatal error:  Interface 'Facebook\WebDriver\WebDriverCapabilities' not found in /var/www/html/FBseleniumDriver/php-webdriver/lib/Remote/DesiredCapabilities.php on line 25
`

So I added `require_once('WebDriverCapabilities.php');` in '__init__.php' on line 23

after that I'm getting following error

`PHP Fatal error:  Uncaught Error: Class 'DesiredCapabilities' not found in /var/www/html/FBseleniumDriver/1.php:7
Stack trace:
#0 {main}
  thrown in /var/www/html/FBseleniumDriver/1.php on line 7
`

**Comment by therageguy** [comment]
Follow this example
https://github.com/facebook/php-webdriver/blob/community/example.php

**Comment by ivantedja** [comment]
See #318
