### ISSUE TITLE
Bad Request returned with Selenium Server

### ISSUE THREAD

**Issue by BrunoSpy** [facebook/php-webdriver#314]
The following error happens on travis :

> [Facebook\WebDriver\Exception\UnknownServerException]                        
  Bad request                                                                  
  Command duration or timeout: 119 milliseconds                                
  Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'                                                                         
  System info: host: 'testing-gce-97d34353-11b8-4d81-9d18-263940f9d73b', ip:'127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-92-generic', java.version:'1.7.0_80'                                              
  Driver info: org.openqa.selenium.firefox.FirefoxDriver 

You can see the full build here : https://travis-ci.org/BrunoSpy/epeires2/jobs/152623178

I cannot find any difference with the previous passed build : https://travis-ci.org/BrunoSpy/epeires2/jobs/151570338

**Comment by OndraM** [comment]
Hi, are you able to reproduce the problem somehow?

Could you provide log from the selenium server? I see in your travis build that you redirects log from it to /dev/null - you could write it to a file and eg. print it to the output at the end of the travis build. (Or see https://github.com/facebook/php-webdriver/blob/community/.travis.yml for an example).

**Comment by BrunoSpy** [comment]
The travis build is ok now, and I don't know why as I didn't change anything...
I was not able to reproduce the bug on my own machine but next time it happens, I will save the log and post it here.

**Comment by OndraM** [comment]
@BrunoSpy Closing for now, but let us please know if the problem occurs again.
