### ISSUE TITLE
improve readme to add clarity to the sample code

### ISSUE THREAD

**Issue by ivantedja** [facebook/php-webdriver#318]
I think we need to add a link to `example.php` or add clarity that this library is using PHP namespace

When people see some snippets (especially under "Getting started" headline), they tend to copy paste the content to test it which cause an error:

```
PHP Fatal error:  Class 'DesiredCapabilities' not found
```

it is not clear that we need to import it `use Facebook\WebDriver\Remote\DesiredCapabilities;`

my suggestion is to add these text:

Above snippets are not intended to be a working example by simply copy pasting. See [example.php](example.php) for working example.

note: example.php meant to be a relative url

**Comment by gfosco** [comment]
Please send in a PR to update the Readme and I'll accept it.  Thanks!

**Comment by ivantedja** [comment]
@gfosco PR has been submitted :)
