### ISSUE TITLE
Drag and drop solution?

### ISSUE THREAD

**Issue by Moghul** [facebook/php-webdriver#319]
I'm having a hard time getting drag & drop functionality to work. No action seems to be performed on screen for either of the attempts below. Browser is Chrome 52.0.2743.116 m, chromedriver 2.23.

Things I've tried:
```
$webDriver->getMouse()
            ->mouseDown($draggableElement->getCoordinates())
            ->mouseMove($dropZone->getCoordinates())
            ->mouseUp($dropZone->getCoordinates());
```
```
12:47:36.554 INFO - Executing: [mousemove: 10 false])
12:47:36.577 INFO - Done: [mousemove: 10 false]
12:47:36.579 INFO - Executing: [mousedown: no args])
12:47:36.589 INFO - Done: [mousedown: no args]
12:47:36.592 INFO - Executing: [mousemove: 11 false])
12:47:36.613 INFO - Done: [mousemove: 11 false]
12:47:36.616 INFO - Executing: [mousemove: 11 false])
12:47:36.629 INFO - Done: [mousemove: 11 false]
12:47:36.631 INFO - Executing: [mouseup: nothing])
12:47:36.640 INFO - Done: [mouseup: nothing]
```

```
$webDriver->action()
            ->moveToElement($draggableElement)
            ->clickAndHold($draggableElement)
            ->moveToElement($dropZone)
            ->release($dropZone);
```
```
12:52:05.177 INFO - Executing: [mousemove: 10 false])
12:52:05.204 INFO - Done: [mousemove: 10 false]
12:52:05.207 INFO - Executing: [mousemove: 10 false])
12:52:05.223 INFO - Done: [mousemove: 10 false]
12:52:05.225 INFO - Executing: [mousedown: no args])
12:52:05.228 INFO - Done: [mousedown: no args]
12:52:05.231 INFO - Executing: [mousemove: 11 false])
12:52:05.252 INFO - Done: [mousemove: 11 false]
12:52:05.253 INFO - Executing: [mousemove: 11 false])
12:52:05.268 INFO - Done: [mousemove: 11 false]
12:52:05.269 INFO - Executing: [mouseup: nothing])
12:52:05.272 INFO - Done: [mouseup: nothing]
```

Seems like a really silly thing to get wrong but I can't figure out what I missed and Google is proving unfruitful.

Edit:
Tried this as per a Facebook group discussion I found... Didn't work.
`$action = $webDriver->action();
$action->dragAndDrop($draggableElement, $dropZone)->perform();`
```
12:45:35.030 INFO - Executing: [mousemove: 10 false])
12:45:35.049 INFO - Done: [mousemove: 10 false]
12:45:35.051 INFO - Executing: [mousedown: no args])
12:45:35.054 INFO - Done: [mousedown: no args]
12:45:35.058 INFO - Executing: [mousemove: 11 false])
12:45:35.080 INFO - Done: [mousemove: 11 false]
12:45:35.081 INFO - Executing: [mousemove: 11 false])
12:45:35.096 INFO - Done: [mousemove: 11 false]
12:45:35.098 INFO - Executing: [mouseup: nothing])
12:45:35.102 INFO - Done: [mouseup: nothing]
```

EDIT: Updated with stack traces. There are no errors but they sure seem similar. Not sure if that means anything.

**Comment by Moghul** [comment]
To avoid an overloaded comment, I'm gonna double post.
Through some coincidental Frankenstein's Monster sort of sorcery, the following code does the trick:

`        $webDriver->action()->dragAndDrop($draggableElement, $dropZone)->perform();

        $webDriver->action()
            ->moveToElement($draggableElement)
            ->clickAndHold($draggableElement)
            ->moveToElement($dropZone)
            ->release($dropZone)
            ->perform();

        $webDriver->getMouse()
            ->mouseDown($draggableElement->getCoordinates())
            ->mouseMove($dropZone->getCoordinates())
            ->mouseUp($dropZone->getCoordinates());`

Removing any lines, reordering the 3 blocks, pretty much anything but this will either fail every time or be very hit or miss. I have no idea why it 'works'. Just in case it's not understood, I accidentally uncommented all 3 blocks at the same time and was surprised to see it work.

**Comment by olleharstedt** [comment]
This is the top google result for Facebook webdriver drag and drop. Would be nice with an update? I've tried different alternatives but the webdriver throws an exception in all cases:

> Facebook\WebDriver\Exception\UnknownServerException: Error communicating with the remote browser. It may have died.

Selenium log before exception:

> 16:24:49.268 INFO - Executing: [mousemove: 5 false])

Selenium version: 3.7.1

Geckodriver: 0.23.0
