### ISSUE TITLE
WebDriverCurlException in non-headless

### ISSUE THREAD

**Issue by Moghul** [facebook/php-webdriver#321]
I am running a series of tests on a website and I'm having a few issues getting the tests to behave reliably. It might error 0 times in 5 sets or 6 times in a single set (21 tests per set)

The error I generally get is 

Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session/9d32d102-f7f3-4742-8fbd-2ea2ec71b2a3/url with params: {"url":"http:\/\/app.website.test"}

There doesn't seem to be anything related to it in the server's logs. No mentions of Curl Exceptions in the log...

It only ever happens in Chrome and Firefox, and only when starting out the test. In Chrome, it will actually load the page, and then proceed to do... nothing. The page will keep 'loading' until the exception occurs.

On Firefox, the page is never loaded. It loads about:blank&utm_content=firstrun and complains that the url is invalid until the exception occurs.

I'm using Selenium server 2.53.1, chromedriver 2.23, Firefox 47.0.1, and Chrome 53.0.2785.101 m, and running my tests with PHPUnit 5.5.4. Everything works perfectly in PhantomJS.

`$webDriver->get("http://app.website.test/account");`

That's the line it fails on. I've tried catching the error and handling it but it seems like any action after the error just... triggers the error again.

Can I get some assistance?

Setup function:

```
        $profile = new FirefoxProfile();
        $capabilities = Capabilities::firefox();
        $capabilities->setCapability(FirefoxDriver::PROFILE, $profile);
        $this->webDriver = Driver::create(
            'http://127.0.0.1:4444/wd/hub',
            $capabilities,
            10000,
            10000);
        $this->configureTest(); // This is where the get() is called.
```

```
        if($webDriver->getCurrentURL() !== "http://app.website.test/account"){
            $webDriver->get('http://app.website.test/account');
        }
```

**Comment by OndraM** [comment]
@Moghul Hi, were you able to fix the problem?

**Comment by Moghul** [comment]
Sort of... I've managed to figure out that I was running the 'get' a bit too fast for it and so a sleep() command fixed this particular issue. Unfortunately, it now pops up in other places. It might just be me but I am guessing that the system the tests are running on is slowing down the browsers at different times depending on what's running in the background.

However, since timeouts happen sometimes when i use 'waits', it might not be that. It all seems very unreliable to me. Some day, when I'm on this task again, I'll try running this on a fresh machine not bloated with other software.
