### ISSUE TITLE
HttpCommandExecutor stuck

### ISSUE THREAD

**Issue by firodj** [facebook/php-webdriver#326]
My acceptance test sometimes stuck for unlimited time > 30mins event the default timeout settings just 30secs.
- HipHop VM 3.14.5 (rel)
  Compiler: tags/HHVM-3.14.5-0-gc6bf714e6468213eed377527b431e9cd4cec1432
  Repo schema: 9ab3fe4281c731189b558d921eb7317b0eb2b2e6
- selenium-server-standalone-2.53.1.jar
- ChromeDriver 2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1)
- Google Chrome 53.0.2785.116
- Codeception 2.2.3
- All inside Vagrant Box with Ubuntu 14.04, with Xvfb

It is trapped on `curl_exec` at https://github.com/facebook/php-webdriver/blob/community/lib/Remote/HttpCommandExecutor.php#L309

I checked the selenium still running. If I abort with Ctrl+C and re run the tests then the stuck removed by itself without touching(restarting) the selenium.

Does anyone have some problem? Thanks

**Comment by OndraM** [comment]
@firodj Do you know what is the command that is stucked?

**Comment by firodj** [comment]
`DriverCommand::NEW_SESSION` when called from RemoteWebDriver::create.

I am using Codeception. Let say I am running tests in a row like these:
```
./codecept.phar run tests/acceptance/folder1
./codecept.phar run tests/acceptance/folder2
./codecept.phar run tests/acceptance/folder3
```

The stuck at sometimes happens when testing folder3, never at folder1.

Maybe has correlation when selenium just have closing the google chrome browser.

**Comment by OndraM** [comment]
I guess this could be some problem with ChromeDriver. I've read similar reports of ChromeDriver being stucke, which were solved by using latest version of ChromeDriver... Thats my only idea, sorry.

**Comment by OndraM** [comment]
Sorry, there is no way I can help... If you find any way how to reproduce the issue, please feel free to open new issue.
