### ISSUE TITLE
Webdriver failing during automation

### ISSUE THREAD

**Issue by jamesekelly3** [facebook/php-webdriver#329]
Hello, 
I am autopopulating a form in my code base using facebook webdriver. The form is pretty long (about 100 fields). The test runs fine until near the end of the form. I researched the problem and put in explicit waits between most of the fields. This helped the program run, but it is still failing toward the form. I've gotten a few different errors (ElementNotFound, ElementNotVisible, TimeOutException,WebDriverCurlException, UnknownServerException) and I have not changed the test. How can I make my script run smoothly?

**Comment by gabrielpreston** [comment]
Are all of the fields visible at once or are they spread across multiple pages?

**Comment by jamesekelly3** [comment]
Visible at once. One form. One page.

**Comment by gabrielpreston** [comment]
Interesting, assuming you are doing a new find after each sendKeys, I wouldn't think you'd run into those first two exceptions- ElementNotFound and ElementNotVisible. Can you provide an example of the logic you are using for finding each input and then sending text to it?

**Comment by jamesekelly3** [comment]
I will first thing tomorrow. I'm not at my desk at this time. Thank you for
your help! I really do appreciate it!
