### ISSUE TITLE
Setting and Referer

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#331]
All pleasant time of day! :) 
I have two problems which I cannot solve, I decided to ask here. 

1. How can I set the referer? ( Specify the URL from which the browser allegedly came ) 
2. Specify titles for User-Agent. 
And so I needed to install in the browser these two values do not tell me how to do it? 
In their tests, I use here such code:
`<?php
namespace Facebook\WebDriver;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
require_once('vendor/autoload.php');
$host = 'http://localhost:4444/wd/hub';
$capabilities = DesiredCapabilities::chrome();
$driver = RemoteWebDriver::create($host, $capabilities, 50000,50000);
$driver->get("http://example.com/");
$driver->manage()->deleteAllCookies();
$driver->manage()->addCookie(array(
  'name' => 'cookie_name',
  'value' => 'cookie_value',
));
$cookies = $driver->manage()->getCookies();
$driver->quit();
?>`

**Comment by gabrielpreston** [comment]
I am pretty sure that Selenium does not allow you to manually do either of those things. The developers of Selenium are pretty adamant about not adding in support for those types of things unfortunately.

**Comment by StasToken** [comment]
Maybe this can be done through the "command line" browser?

**Comment by OndraM** [comment]
You can eg. install some Firefox extension to spoof the referer. But this is not supported directly with Selenium - see discussion in https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/141

**Comment by StasToken** [comment]
Hi all I know that question is already closed but I found a way to install User-Agent to Firefox
`$profile->setPreference('general.useragent.override','String User Agent or Firefox php web driver');` 
In General, write it if someone will need :-)
