### ISSUE TITLE
alertIsPresent doesn't wait the set timeout in seconds

### ISSUE THREAD

**Issue by gustavomanolo** [facebook/php-webdriver#332]
I'm trying to wait for a maximum of 2 seconds for an alert with:
`$this->driver->wait(2,500)->until(WebDriverExpectedCondition::alertIsPresent());`

but it doesn't wait for the given time, and i get the following exception:
Curl error thrown for http GET to /session/1364c0a5-d6ce-400b-b3c2-92a4ced7a072/alert_text Operation timed out after 30001 milliseconds with 0 bytes received

the other WebDriverExpectedCondition works great, but this one.

**Comment by OndraM** [comment]
Hi, I cannot reproduce the issue, works fine for me. Maybe there is problem with your browser? What browser in which version do you use?
