### ISSUE TITLE
How to choose a select list

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#336]
Good day, I have a list, how do I choose 12 point? unfortunately the example given in the documentation why it is not working...
`<span id="ggdfghdfgh_gq_period_text" initial="1M">
<select class="select_period" name="ggdfghdfgh_gq_period">
<option value="1M">1</option>
<option value="2M">2</option>
<option value="3M">3</option>
<option value="4M">4</option>
<option value="5M">5</option>
<option value="6M">6</option>
<option value="7M">7</option>
<option value="8M">8</option>
<option value="9M">9</option>
<option value="10M">10</option>
<option value="11M">11</option>
<option value="12M">12</option>
</select></span>`

**Comment by OndraM** [comment]
Hi, could you please send the code you tried?

You need to use WebDriverSelect, something like this:
```
$selectElement = $driver->findElement(WebDriverBy::css('select.select_period"'));
$select = new WebDriverSelect($selectElement);
$select->selectByValue('12M'); // or you can use selectByVisibleText() or selectByIndex() methods
```

**Comment by StasToken** [comment]
> PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\NoSuchElementException: no such element
Um... what a strange problem finds element even XPath 
The code I used was similar to this, I do not understand why he can't find the item...
`$selectElement = $driver->findElement(WebDriverBy::xpath("id('nkuyj_tk_period_text')/select"));
$select = new WebDriverSelect($selectElement);
$select->selectByValue('12M');`
how to catch a bug with the search item?

**Comment by StasToken** [comment]
Why it can not find the element? Xpath is not written manually error is not possible in css, too, finds

**Comment by OndraM** [comment]
If you use
```
$selectElement = $driver->findElement(WebDriverBy::css('select.select_period"'));
```
to retrieve the element, it should work. I think the ID you use changes, so you should not rely on in.

**Comment by OndraM** [comment]
You can easily test your selectors in Developer Tools. Or you could try this: http://elementalselenium.com/tips/verifying-locators

**Comment by StasToken** [comment]
Thanks, your advice helped, indeed the error was in the way. The question is closed.
