### ISSUE TITLE
How to start autoload

### ISSUE THREAD

**Issue by merkychacon** [facebook/php-webdriver#337]
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\ddd\example.php on line 9

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\ddd\example.php on line 9

**Comment by OndraM** [comment]
Hi,
you need to install php-webdriver using [Composer](https://getcomposer.org).

It will generate the autoload.php file.

**Comment by merkychacon** [comment]
Thanks OndraM
But, with composer is the only solution? I cloned this repository directly because I am having problems with composer.

**Comment by OndraM** [comment]
@merkychacon Yes, Composer is the only supported way of installation. The php-webdriver itself has many dependencies, so cloning the repository won't work - you have to install those dependencies (and their dependencies) using composer.
