### ISSUE TITLE
Set profile config

### ISSUE THREAD

**Issue by nekulin** [facebook/php-webdriver#340]
I'm trying to set the Yala browser, but not working

        $desiredCapabilities = DesiredCapabilities::firefox();
        $options = new FirefoxProfile();
	// optimization
        $options->setPreference('browser.sessionhistory.max_entries', '0');
        $options->setPreference('network.http.use-cache', 'true');
        $options->setPreference('browser.cache.offline.enable', 'true');
	$desiredCapabilities->setCapability(FirefoxDriver::PROFILE, $profile);
	$driver = RemoteWebDriver::create($url, $desiredCapabilities);

When the browser is opened I go to about:config I see the default settings

**Comment by OndraM** [comment]
Hi @nekulin, I guess you are not using proper data types expected by firefox settings (integer and boolean in this case). Your example really do not work, but changing the values in this way makes it work for me:

```
$options->setPreference('browser.sessionhistory.max_entries', 0);
$options->setPreference('network.http.use-cache', true);
$options->setPreference('browser.cache.offline.enable', true);
```

**Comment by OndraM** [comment]
Or actually, if you pass these values as string, php-webdriver will enquote the value making firefox to not accept them, as those settings are declared as integer or boolean respectively.

**Comment by nekulin** [comment]
Thanks, I'll try
