### ISSUE TITLE
Opera is not working

### ISSUE THREAD

**Issue by smunukuntla** [facebook/php-webdriver#343]
Hers is the code 
```
 public function testOperaBrowser()
    {
        $desired_capabilities = DesiredCapabilities::opera();
        $desired_capabilities->setCapability('acceptSslCerts', true);
        $driver = RemoteWebDriver::create('http://localhost:4444/wd/hub', $desired_capabilities);
        $driver->get('http://docs.seleniumhq.org/');
        $driver->wait(10);
        echo "The title is '" . $driver->getTitle() . "'\n";
        $driver->quit();

    }

Error Message 

/usr/bin/php "/Users/smunukuntla/Documents/Selenium PHP/vendor/phpunit/phpunit/phpunit" --no-configuration --filter "/::testOperaBrowser( .*)?$/" Selenium_Drivers_Implementation "/Users/smunukuntla/Documents/Selenium PHP/tests/1_Selenium_Drivers_Browsers/Selenium_Drivers_Implementation.php" --teamcity
Testing started at 4:53 PM ...
PHPUnit 5.5.7 by Sebastian Bergmann and contributors.


Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"opera","platform":"ANY","acceptSslCerts":true}}

Operation timed out after 30004 milliseconds with 0 bytes received
 /Users/smunukuntla/Documents/Selenium PHP/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:92
 /Users/smunukuntla/Documents/Selenium PHP/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:320
 /Users/smunukuntla/Documents/Selenium PHP/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:100
 /Users/smunukuntla/Documents/Selenium PHP/tests/1_Selenium_Drivers_Browsers/Selenium_Drivers_Implementation.php:51
 ```

**Comment by OndraM** [comment]
Hi @smunukuntla, what version of Opera do you use? If it is one of the latest blink-based Opera (version >12), you have to use operablink as name of the browser. This is currently not builtin to php-webdriver, but you can easily do it manually:

```
$desired_capabilities = new DesiredCapabilities();
$desired_capabilities->setBrowserName('operablink');
```

Due to bug in OperaChromiumDriver you also have to define path to opera binary (https://github.com/operasoftware/operachromiumdriver/issues/9), like this:

```
$desired_capabilities->setCapability('chromeOptions', ['binary' => '/usr/bin/opera']);
```

With this set-up and with Opera 40.0.2308.54 it does work for me. However, I will create new issue to track the built-in support of Opera in php-webdriver.

**Comment by smunukuntla** [comment]
@OndraM Thanks a ton for providing the solution. yes I'm using opera 40 version. As you suggested, it worked for me. Thanks again.

**Comment by salarmehr** [comment]
@OndraM Trying this in Windows I get:

     PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnknownServerException: The path to the driver executable must be set by the webdriver.opera.driver system property; for more information, see https://github.com/operasoftware/operachromiumdriver. The latest version can be downloaded from https://github.com/operasoftware/operachromiumdriver/releases in C:\www\www\webdriver\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:114
