### ISSUE TITLE
Version 1.2.0 is not available via composer / packagist.org

### ISSUE THREAD

**Issue by andreisusanu** [facebook/php-webdriver#346]
https://packagist.org/packages/facebook/webdriver

**Comment by OndraM** [comment]
Hi, thank you. I am aware of the problem, the hook from github to packagist is probably broken; @gfosco must take care of it, as only he can adjust the repository settings :-).

Thanks for you patience

**Comment by andreisusanu** [comment]
It's fixed now. Thanks!
