### ISSUE TITLE
JSON decoding of remote response failed issue

### ISSUE THREAD

**Issue by liuzongyao** [facebook/php-webdriver#347]
I am a newer for this. I installed the php webdriver according to the Installation guard and then copy the example.php file on https://github.com/facebook/php-webdriver/blob/community/example.php and  when I run this example.php , it will fail and give error information. so could any one help me to resolve this issue, thanks so much.

{Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\WebDriverException' with message 'JSON decoding of remote response failed.
Error code: 4
The response: '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"><!--
 /*
 Stylesheet for Squid Error pages
 Adapted from design by Free CSS Templates
 http://www.freecsstemplates.org
 Released for free under a Creative Commons Attribution 2.5 License
*/
}

**Comment by OndraM** [comment]
@liuzongyao You must have Selenium server listening on URL specified when creatin RemoteWebDriver instance (like 'http://localhost:4444/wd/hub'), but you probably have something else occupying this URL. How did you start your selenium server?

**Comment by liuzongyao** [comment]
I download the selenium-server-standalone-2.53.1.jar  and use java -jar selenium-server-standalone-2.53.1.jar  and it said ' Selenium Server is up and running'

**Comment by gabrielpreston** [comment]
What's this bit about Squid in the error message? I know that's a proxy
service. Is that running locally on your machine? Are you trying to proxy
all of your requests through Squid?
