### ISSUE TITLE
Where geckodriver path should be specified in code?

### ISSUE THREAD

**Issue by grikis** [facebook/php-webdriver#349]
I added this code in setUp function: 
$capabilities->setCapability('firefoxOptions', ['binary' => '/opt/selenium/geckodriver']);
, but when I run test it says "UnknownServerException: Firefox option was set, but is not a FirefoxOption: {binary=/opt/selenium/geckodriver}"
Where I'm wrong?

**Comment by OndraM** [comment]
@grikis Hi, what version of Firefox and Selenium driver do you use?

But in general, I would recommend specifying the path to binary using Selenium server property, like this:

```java -Dwebdriver.firefox.bin="/usr/bin/firefox-esr" -jar selenium-server-standalone-2.53.1.jar```

**Comment by grikis** [comment]
Well I'm using latest versions. And yeah, specifying the path like that, works fine. But I was wondering is there are another way how to specify

**Comment by OndraM** [comment]
@grikis FYI I guess you can also specify path to Firefox binary using `firefox_binary` capability - see https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities.

` $capabilities->setCapability('firefox_binary', /usr/bin/firefox');`

But I'm not sure this works with Firefox 48+ and Marionette driver.

**Comment by cryptton2004** [comment]
On windows, you can also specify it in your system environment variables. Under 'Path' variable also add "Drive:\Path\To\geckodriver\". Ex: "D:\tests\selenium\geckodriver".
