### ISSUE TITLE
Facebook\WebDriver\Exception\WebDriverException: JSON decoding of remote response failed.

### ISSUE THREAD

**Issue by TBlindaruk** [facebook/php-webdriver#350]
My code is a

```
<?php
/**
 * Created by tania.
 * Date: 19.10.16
 * Time: 11:01
 * @corporation Maksi
 */

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;

/**
 * Class WebTest
 */
class WebTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var RemoteWebDriver
     */
    protected $webDriver;

    protected function setUp()
    {
        $this->webDriver = RemoteWebDriver::create('http://test.local/index.php', DesiredCapabilities::firefox());
    }

    public function testTitle()
    {
        $this->webDriver->get('http://test.local/index.php');
        $this->assertEquals('Example Domain', "1");
    }

    public function tearDown()
    {
        $this->webDriver->quit();
    }

}
```

I got a 

> PHPUnit 5.6.1 by Sebastian Bergmann and contributors.
> 
> E                                                                   1 / 1 (100%)
> 
> Time: 493 ms, Memory: 10.00MB
> 
> There was 1 error:
> 
> 1) WebTest::testTitle
> Facebook\WebDriver\Exception\WebDriverException: JSON decoding of remote response failed.
> Error code: 4
> The response: '﻿<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" >
> <head>
>         <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
>         <meta name="Description" content="PHP-Addressbook" />
>         <meta name="Keywords" content="" />
>         <style type="text/css">
>                 body,#footer,ul {margin:0;padding:0;}
> body {background-image:url('./header.jpg');background-repeat:repeat-x;background-position:top left;}
> body,p,td,h1,h2,a,a:hover {font-family:Arial,Helvetica,sans-serif;font-size:12px}
> h1 {font-size:18px}
> h2 {font-size:14px}
> a {color:#036}
> a:hover {color:#06C;text-decoration:none}
> img {border:0;}
> # container {margin:0 auto;width:780px;border:0}
> # top{margin:5px 0 0;height:20px;text-align:right;}
> # header {height:80px;}
> # nav {margin:0 0 20px;height:25px;width:770px;float:left;border:0;display:inline;}
> # nav ul li a {color:#fff;padding:0 4px;}
> # nav ul li img {display:none;}
> # content {margin:20px 0 0;width:780px;}
> # footer {margin:45px 0 0;padding:20px 0;clear:both;}
> 
> ul {list-style:none;}
> ul li {display:inline;}
> # footer ul li {display:block;}
> 
> label {margin-right:0.5em;width:10em;float:left;text-align:left;display:block;}
> # search-az {text-align:center;padding:2px;}
> # a-z a {font-size:75%;}
> 
> .odd {background:#e5e5e5;}
> .even {background:#f3f3f3;}
> # right,.right {float:right;}
> # left,.left {float:left;}
> 
> .clear {clear:both;}
> 
> .msgbox {padding:16px;border:1px solid #ccc;background:#fff4b4;width:60%;font-weight:700;}
> .msgbox i {font-weight:400;}
> 
> table {width:100%;border:1px solid #ccc;border-collapse:collapse;}
> table tr td {border:1px solid #ccc;padding:2px 1px}
> table img,.center {text-align:center;}
> table th {text-align:left;font-size:14px;padding:8px 4px;}
> 
> table#maintable th {text-align:center;border:1px solid #ccc;font-size:12px;background:#739fce;color:#fff;}
> 
> table#birthdays {border:0;}
> table#birthdays th {color:#fff;background:#739fce;margin:25px;border:1px solid #ccc;}
> .tablespace td {border:0;}
> 
> /\* View.php */
> table#view,table#view td {border:1px solid #000;border-collapse:collapse;}
> table#view td {padding:5px;}
> 
> /\* Source Forge */
> # download {margin:0;width:180px;background:#63A624;color:#fff;border:1px solid #000;text-align:center;}
> # download a,#top a {color:#fff;}
> 
>   </style>
>         <link rel="icon" type="image/png" href="icons/font.png" />
>         <title>Address book</title>
>         </head>
>         <body>
>                 <div id="container">
>                         <div id="top">
> [<a title="other languages" href="?more_langs=yes">+</a>] | <a href='?lang=ar'><img title='Arabic' alt='Arabic' src='icons/sa.gif'/></a> | <a href='?lang=zh'><img title='Chinese' alt='Chinese' src='icons/cn.gif'/></a> | <a href='?lang=es'><img title='Spanish' alt='Spanish' src='icons/es.gif'/></a> | <a href='?lang=fr'><img title='French' alt='French' src='icons/fr.gif'/></a> | <a href='?lang=ru'><img title='Russian' alt='Russian' src='icons/ru.gif'/></a> | 
> 
> <a href="preferences.php?from=%2Findex.php%2Fsession">Preferences</a>
>                         </div>
>                         <div id="header"><a href="."><img src="title.png" title="Addressbook" alt="Addressbook" /></a></div>
>                         <div id="nav">
>                         <ul>
> <li>
>         <a href="./">home</a>
> </li>
> <li>
>         <a href="edit.php">add new</a>
> </li>
>         <li>
>                 <a href="group.php">groups</a>
>         </li>
>         <li>
>                 <a href="birthdays.php">next birthdays</a>
>         </li>
>     <li>
>         <a href="view.php?all&amp;print">print all</a>
>   </li>
>     <li>
>       <a href="view.php?all&amp;print&amp;phones">print phones</a>
>   </li>
>     <li>
>         <a href="csv.php">export csv</a>
>   </li> 
> </ul>
>                         </div>
>                         <div id="content">
> 
> <br /><br />
> 
> <div id="search-az">
>         <form accept-charset="utf-8" method="get" name="searchform" onsubmit="return false">
>                 <input type="text" value="" name="searchstring" title="Search for any text" size="45" tabindex="0" 
>                        onkeyup="filterResults(this)"/>
>         </form>
> <script type="text/javascript">
>         document.searchform.searchstring.focus();
> </script>
> </div><br />
> <hr />
> <label style='width:24em;'><strong>Number of results: <span id='search_count'>8</span></strong></label>
> <form id="right" method="get">
>         <select name="group" onchange="this.parentNode.submit()">
>                                 <option value="">[all]</option>
>                 <option value="[none]">[none]</option>
>                 <option>Group Name 1</option>
> <option>name</option>
> <option>Name</option>
>         </select>
> </form><br /><br class="clear" />
> 
> <a href="а я никуда не веду" title="tttt"></a>
> <form accept-charset="utf-8" name="MainForm" method="post" action="group.php">
>         <input type="hidden" name="group" value="" />
>         <table id="maintable">
>                 <tr>
>                         <th></th>
> <th>First name</th><th>Last name</th><th>E-mail</th><th>Telephone</th>                  
>                         <th></th><th></th><th></th><th></th><th></th>
>                 </tr>
> <tr class='odd' name='entry'><td class='center'><input type='checkbox' id='id3' name='selected[]' value='3' title='Select ( )' alt='Select ( )' accept='' /></td><td></td><td></td><td><a href='mailto:'></a></td><td></td><td class='center'><a href='view.php?id=3'><img src='icons/status_online.png' title='Details' alt='Details' /></a></td><td class='center'><a href='edit.php?id=3'><img src='icons/pencil.png' title='Edit' alt='Edit'/></a></td><td class='center'><a href='vcard.php?id=3'><img src='icons/vcard.png' title='vCard' alt='vCard'/></a></td><td/><td/></tr>
> <tr class='even' name='entry'><td class='center'><input type='checkbox' id='id4' name='selected[]' value='4' title='Select ( )' alt='Select ( )' accept='' /></td><td></td><td></td><td><a href='mailto:'></a></td><td></td><td class='center'><a href='view.php?id=4'><img src='icons/status_online.png' title='Details' alt='Details' /></a></td><td class='center'><a href='edit.php?id=4'><img src='icons/pencil.png' title='Edit' alt='Edit'/></a></td><td class='center'><a href='vcard.php?id=4'><img src='icons/vcard.png' title='vCard' alt='vCard'/></a></td><td/><td/></tr>
> <tr class='odd' name='entry'><td class='center'><input type='checkbox' id='id6' name='selected[]' value='6' title='Select (" . "DROP DATABASE" .  )' alt='Select (" . "DROP DATABASE" .  )' accept='' /></td><td></td><td>" . "DROP DATABASE" . </td><td><a href='mailto:'></a></td><td></td><td class='center'><a href='view.php?id=6'><img src='icons/status_online.png' title='Details' alt='Details' /></a></td><td class='center'><a href='edit.php?id=6'><img src='icons/pencil.png' title='Edit' alt='Edit'/></a></td><td class='center'><a href='vcard.php?id=6'><img src='icons/vcard.png' title='vCard' alt='vCard'/></a></td><td/><td/></tr>
> <tr class='even' name='entry'><td class='center'><input type='checkbox' id='id5' name='selected[]' value='5' title='Select (alert(1) )' alt='Select (alert(1) )' accept='' /></td><td></td><td>alert(1)</td><td><a href='mailto:'></a></td><td></td><td class='center'><a href='view.php?id=5'><img src='icons/status_online.png' title='Details' alt='Details' /></a></td><td class='center'><a href='edit.php?id=5'><img src='icons/pencil.png' title='Edit' alt='Edit'/></a></td><td class='center'><a href='vcard.php?id=5'><img src='icons/vcard.png' title='vCard' alt='vCard'/></a></td><td/><td/></tr>
> <tr class='odd' name='entry'><td class='center'><input type='checkbox' id='id7' name='selected[]' value='7' title='Select (1 1)' alt='Select (1 1)' accept='1;1' /></td><td>1</td><td>1</td><td><a href='mailto:1'>1</a></td><td>1</td><td class='center'><a href='view.php?id=7'><img src='icons/status_online.png' title='Details' alt='Details' /></a></td><td class='center'><a href='edit.php?id=7'><img src='icons/pencil.png' title='Edit' alt='Edit'/></a></td><td class='center'><a href='vcard.php?id=7'><img src='icons/vcard.png' title='vCard' alt='vCard'/></a></td><td class='center'><a href='http://maps.google.com/maps?q=1%2C+&amp;t=h'>
>                           <img src='icons/car.png' title='Google Maps' alt='vCard'/></a></td><td/></tr>
> <tr class='even' name='entry'><td class='center'><input type='checkbox' id='id1' name='selected[]' value='1' title='Select (2131 23123)' alt='Select (2131 23123)' accept='фівфі;123' /></td><td>23123</td><td>2131</td><td><a href='mailto:фівфі'>фівфі</a></td><td>1231</td><td class='center'><a href='view.php?id=1'><img src='icons/status_online.png' title='Details' alt='Details' /></a></td><td class='center'><a href='edit.php?id=1'><img src='icons/pencil.png' title='Edit' alt='Edit'/></a></td><td class='center'><a href='vcard.php?id=1'><img src='icons/vcard.png' title='vCard' alt='vCard'/></a></td><td class='center'><a href='http://maps.google.com/maps?q=231231%2C+&amp;t=h'>
>                           <img src='icons/car.png' title='Google Maps' alt='vCard'/></a></td><td class='center'><a href='http://www.�івфі'><img src='icons/house.png' title='Guessed homepage (www.�івфі)' alt='Guessed homepage (www.�івфі)'/></a></td></tr>
> <tr class='odd' name='entry'><td class='center'><input type='checkbox' id='id8' name='selected[]' value='8' title='Select (Tania BLindaruk)' alt='Select (Tania BLindaruk)' accept='t.blindaruk@gmail.com;tt.blindaruk@gmail.com' /></td><td>BLindaruk</td><td>Tania</td><td><a href='mailto:t.blindaruk@gmail.com'>t.blindaruk@gmail.com</a></td><td>Переулок</td><td class='center'><a href='view.php?id=8'><img src='icons/status_online.png' title='Details' alt='Details' /></a></td><td class='center'><a href='edit.php?id=8'><img src='icons/pencil.png' title='Edit' alt='Edit'/></a></td><td class='center'><a href='vcard.php?id=8'><img src='icons/vcard.png' title='vCard' alt='vCard'/></a></td><td class='center'><a href='http://maps.google.com/maps?q=%D0%9F%D0%B5%D1%80%D0%B5%D1%83%D0%BB%D0%BE%D0%BA.+%D0%A7%D0%BA%D0%B0%D0%BB%D0%BE%D0%B2%D0%B0%2C+&amp;t=h'>
>                           <img src='icons/car.png' title='Google Maps' alt='vCard'/></a></td><td/></tr>
> <tr class='even' name='entry'><td class='center'><input type='checkbox' id='id2' name='selected[]' value='2' title='Select (mmk kjmojok)' alt='Select (mmk kjmojok)' accept='' /></td><td>kjmojok</td><td>mmk</td><td><a href='mailto:'></a></td><td></td><td class='center'><a href='view.php?id=2'><img src='icons/status_online.png' title='Details' alt='Details' /></a></td><td class='center'><a href='edit.php?id=2'><img src='icons/pencil.png' title='Edit' alt='Edit'/></a></td><td class='center'><a href='vcard.php?id=2'><img src='icons/vcard.png' title='vCard' alt='vCard'/></a></td><td class='center'><a href='http://maps.google.com/maps?q=kjnjn%2C+&amp;t=h'>
>                           <img src='icons/car.png' title='Google Maps' alt='vCard'/></a></td><td/></tr>
> <tr><td class='center'><input type='checkbox' id='MassCB' onclick="MassSelection()" /></td><td><em><strong>Select all</strong></em></td><td colspan='8'></td></tr>
> </table><br /><div class='left'><input type='button' value="Send e-Mail" onclick="MailSelection()" /></div><div></div><div class='right'><input type='submit' name='add' value='Add to'/>-<select name='to_group'><option>Group Name 1</option>
> <option>name</option>
> <option>Name</option>
> </select></div><br /><br class='clear' /></form><script type="text/javascript">
> 
> </script>
>         </div>
>         <div id="footer">
>                         <ul>
>                                 <li><a href="http://sourceforge.net/projects/php-addressbook/">php-addressbook</a> <a href="notes.htm">v4.1.4</a></li>
>                         </ul>
>         </div>
> </div>
> 
> ```
>     </body>
> ```
> 
> </html> 
> 
> '

Where response is  a code of page

**Comment by OndraM** [comment]
Hi, the first option of ` RemoteWebDriver::create()` method is URL of the running remote Selenium server, not URL of the page. So for example the default is `http://localhost:4444/wd/hub`. It is a bit confusing in the code, so I will improve the comment. Thank you!

You may also be interested in projects like https://github.com/lmc-eu/steward, which integrates PHPUnit with php-webdriver and takes care about the connection to Selenium server, so they can tell you more information if the connection fails.
