### ISSUE TITLE
Cannot get the page Firefox

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#351]
All good time of coding... 
I encountered a very strange problem when working with firefox - for some reason at the start of the scenario browser opens and nothing happens nor getting page not what. I tested this scenario on google hrome it worked fine... Can tell the beginner what can be the problem?
Use this code for the script: 
`<?php
// An example of using php-webdriver.
namespace Facebook\WebDriver;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
require_once('vendor/autoload.php');
// start Firefox with 5 second timeout
$host = 'http://localhost:4444/wd/hub'; // this is the default
$capabilities = DesiredCapabilities::firefox();
$driver = RemoteWebDriver::create($host, $capabilities, 5000);
// navigate to 'http://docs.seleniumhq.org/'
$driver->get('http://docs.seleniumhq.org/');
// adding cookie
$driver->manage()->deleteAllCookies();
$cookies = $driver->manage()->getCookies();
// click the link 'About'
$link = $driver->findElement(
  WebDriverBy::id('menu_about')
);
$link->click();
// print the title of the current page
echo "The title is '" . $driver->getTitle() . "'\n";
// print the URI of the current page
echo "The current URI is '" . $driver->getCurrentURL() . "'\n";
// Search 'php' in the search box
$input = $driver->findElement(
  WebDriverBy::id('q')
);
$input->sendKeys('php')->submit();
// wait at most 10 seconds until at least one result is shown
$driver->wait(10)->until(
  WebDriverExpectedCondition::presenceOfAllElementsLocatedBy(
    WebDriverBy::className('gsc-result')
  )
);
// close the Firefox
$driver->quit();`
The script launches the browser and then any action is not happening... 
in consequence displays this error:

> PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"firefox","platform":"ANY","firefox_profile":"UEsDBBQAAAAAALZpVknf9RXUMgAAADIAAAAHAAAAdXNlci5qc3VzZXJfcHJlZigicmVhZGVyLnBhcnNlLW9uLWxvYWQuZW5hYmxlZCIsIGZhbHNlKTsKUEsBAhQDFAAAAAAAtmlWSd\/1FdQyAAAAMgAAAAcAAAAAAAAAAAAAALaBAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAAVwAAAAAA"}}

Operation timed out after 30001 milliseconds with 0 bytes received in /home/test/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:92
Stack trace:
#0 /home/test/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throwException(-1, 'Curl error thro...', Array)
#1 /home/test/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(100): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 /home/test/test.php(10): Facebook\WebDrive in /home/test/vendor/facebook/webdriver/lib/Exception/WebDriverException.php on line 92

The log files:

> java -jar /var/selenium/server.jar 
13:12:59.390 INFO - Launching a standalone server
13:12:59.858 INFO - Java: Oracle Corporation 25.91-b14
13:12:59.859 INFO - OS: Linux 4.4.0-42-generic i386
13:12:59.947 INFO - v2.43.1, with Core v2.43.1. Built from revision 5163bce
13:13:01.072 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match with current platform: LINUX
13:13:01.298 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
13:13:01.304 INFO - Version Jetty/5.1.x
13:13:01.330 INFO - Started HttpContext[/selenium-server,/selenium-server]
13:13:01.615 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@1531931
13:13:01.615 INFO - Started HttpContext[/wd,/wd]
13:13:01.615 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
13:13:01.616 INFO - Started HttpContext[/,/]
13:13:01.638 INFO - Started SocketListener on 0.0.0.0:4444
13:13:01.640 INFO - Started org.openqa.jetty.jetty.Server@da2dbb
13:13:48.388 INFO - Executing: [new session: Capabilities [{browserName=firefox, platform=ANY, firefox_profile=UEsDBBQAAAAAALZpVknf9RXUMgAAA...}]])
13:13:48.506 INFO - Creating a new session for Capabilities [{browserName=firefox, platform=ANY, firefox_profile=UEsDBBQAAAAAALZpVknf9RXUMgAAA...}]
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
}},"app-system-defaults":{"webcompat@mozilla.org":{"d":"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi","e":true,"v":"1.0","st":1474324920000},"firefox@getpocket.com":{"d":"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi","e":true,"v":"1.0.4","st":1474324920000},"e10srollout@mozilla.org":{"d":"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi","e":true,"v":"1.2","st":1474324920000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","e":true,"v":"49.0","st":1474324920000}},"app-system-share":{"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi","e":false,"v":"3.2","st":1442597402000}}}
1477124050989	addons.xpi	DEBUG	No changes found
1477124051008	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477124051009	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477124051045	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477124051046	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477124051048	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477124051058	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477124051078	addons.xpi-utils	DEBUG	Starting async load of XPI database /tmp/anonymous6280270887015617271webdriver-profile/extensions.json
1477124051081	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477124051082	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477124051088	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1477124051094	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477124051096	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477124051096	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477124051096	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477124051097	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477124051098	addons.manager	DEBUG	Starting provider: GMPProvider
1477124051119	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477124051120	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477124051122	addons.manager	DEBUG	Starting provider: PluginProvider
1477124051122	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477124051124	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477124051129	addons.manager	DEBUG	Completed startup sequence
1477124052122	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1477124052123	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1477124052133	addons.xpi-utils	DEBUG	Successfully read XPI database
1477124052183	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477124052184	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477124052185	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1477124052872	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477124052872	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477124052873	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
JavaScript error: file:///tmp/anonymous6280270887015617271webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11464: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:215)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:169)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
13:14:55.481 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'coterell', ip: '192.168.1.13', os.name: 'Linux', os.arch: 'i386', os.version: '4.4.0-42-generic', java.version: '1.8.0_91'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:176)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:112)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:89)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:108)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:112)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:173)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:163)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:129)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'coterell', ip: '192.168.1.13', os.name: 'Linux', os.arch: 'i386', os.version: '4.4.0-42-generic', java.version: '1.8.0_91'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:69)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:215)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:169)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
	... 9 more
Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
}},"app-system-defaults":{"webcompat@mozilla.org":{"d":"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi","e":true,"v":"1.0","st":1474324920000},"firefox@getpocket.com":{"d":"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi","e":true,"v":"1.0.4","st":1474324920000},"e10srollout@mozilla.org":{"d":"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi","e":true,"v":"1.2","st":1474324920000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","e":true,"v":"49.0","st":1474324920000}},"app-system-share":{"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi","e":false,"v":"3.2","st":1442597402000}}}
1477124050989	addons.xpi	DEBUG	No changes found
1477124051008	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477124051009	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477124051045	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477124051046	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477124051048	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477124051058	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477124051078	addons.xpi-utils	DEBUG	Starting async load of XPI database /tmp/anonymous6280270887015617271webdriver-profile/extensions.json
1477124051081	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477124051082	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477124051088	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1477124051094	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477124051096	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477124051096	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477124051096	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477124051097	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477124051098	addons.manager	DEBUG	Starting provider: GMPProvider
1477124051119	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477124051120	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477124051122	addons.manager	DEBUG	Starting provider: PluginProvider
1477124051122	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477124051124	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477124051129	addons.manager	DEBUG	Completed startup sequence
1477124052122	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1477124052123	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1477124052133	addons.xpi-utils	DEBUG	Successfully read XPI database
1477124052183	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477124052184	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477124052185	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1477124052872	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477124052872	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477124052873	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
JavaScript error: file:///tmp/anonymous6280270887015617271webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11464: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]

Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'coterell', ip: '192.168.1.13', os.name: 'Linux', os.arch: 'i386', os.version: '4.4.0-42-generic', java.version: '1.8.0_91'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
	... 14 more
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
}},"app-system-defaults":{"webcompat@mozilla.org":{"d":"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi","e":true,"v":"1.0","st":1474324920000},"firefox@getpocket.com":{"d":"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi","e":true,"v":"1.0.4","st":1474324920000},"e10srollout@mozilla.org":{"d":"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi","e":true,"v":"1.2","st":1474324920000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","e":true,"v":"49.0","st":1474324920000}},"app-system-share":{"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi","e":false,"v":"3.2","st":1442597402000}}}
1477124050989	addons.xpi	DEBUG	No changes found
1477124051008	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477124051009	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477124051045	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477124051046	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477124051048	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477124051058	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477124051078	addons.xpi-utils	DEBUG	Starting async load of XPI database /tmp/anonymous6280270887015617271webdriver-profile/extensions.json
1477124051081	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477124051082	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477124051088	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1477124051094	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477124051096	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477124051096	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477124051096	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477124051097	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477124051098	addons.manager	DEBUG	Starting provider: GMPProvider
1477124051119	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477124051120	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477124051122	addons.manager	DEBUG	Starting provider: PluginProvider
1477124051122	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477124051124	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477124051129	addons.manager	DEBUG	Completed startup sequence
1477124052122	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1477124052123	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1477124052133	addons.xpi-utils	DEBUG	Successfully read XPI database
1477124052183	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477124052184	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477124052185	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1477124052872	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477124052872	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477124052873	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
JavaScript error: file:///tmp/anonymous6280270887015617271webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11464: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	... 19 more
13:14:55.497 WARN - Exception: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
}},"app-system-defaults":{"webcompat@mozilla.org":{"d":"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi","e":true,"v":"1.0","st":1474324920000},"firefox@getpocket.com":{"d":"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi","e":true,"v":"1.0.4","st":1474324920000},"e10srollout@mozilla.org":{"d":"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi","e":true,"v":"1.2","st":1474324920000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","e":true,"v":"49.0","st":1474324920000}},"app-system-share":{"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi","e":false,"v":"3.2","st":1442597402000}}}
1477124050989	addons.xpi	DEBUG	No changes found
1477124051008	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477124051009	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477124051045	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477124051046	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477124051048	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477124051058	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477124051078	addons.xpi-utils	DEBUG	Starting async load of XPI database /tmp/anonymous6280270887015617271webdriver-profile/extensions.json
1477124051081	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477124051082	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477124051088	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1477124051094	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477124051096	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477124051096	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477124051096	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477124051097	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477124051098	addons.manager	DEBUG	Starting provider: GMPProvider
1477124051119	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477124051120	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477124051122	addons.manager	DEBUG	Starting provider: PluginProvider
1477124051122	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477124051124	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477124051129	addons.manager	DEBUG	Completed startup sequence
1477124052122	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1477124052123	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1477124052133	addons.xpi-utils	DEBUG	Successfully read XPI database
1477124052183	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477124052184	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477124052185	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1477124052872	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477124052872	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477124052873	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
JavaScript error: file:///tmp/anonymous6280270887015617271webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11464: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]

**Comment by OndraM** [comment]
Hi, what version of Firefox and Selenium server do you use?

You can try downgrading to firefox 47.0.1 or use Firefox ESR version. You can even install it together with your current Firefox  and then provide path to Firefox ESR to your  Selenium server like this:

`java -jar vendor/bin/selenium-server-standalone-2.53.1.jar -Dwebdriver.firefox.bin="/usr/bin/firefox-esr"`

**Comment by StasToken** [comment]
Thank you!
Did everything you said worked - indeed the problem was in new version of firefox, I hope in the future it will eliminate.... 
**PS:** OndraM - a special thanks to you, I hope someday to be as good in this business as you will also be able to help people. You've already come to the rescue a second time. Thank you very much good luck to you.
