### ISSUE TITLE
Radio select not working

### ISSUE THREAD

**Issue by nicktan147** [facebook/php-webdriver#352]
I tried to find solution this issue to click on radio input but it doesn't seems to work. This is my html code:-

`<input type="radio" name="ns_Z7_79I61180LO4VE0AM3FPAKC3KR6_fromOtherFavorFlag" id="ns_Z7_79I61180LO4VE0AM3FPAKC3KR6_fromOtherFavorFlag" disabled="true" value="false" onclick="checkTransferTo(this,1);isAllowAlert();">`

In my PHP I was doing this:-

```
$enableRadio = $engine->findWebElem($driver,"Enable Radio Input To: ","xpath","//input[contains(@id, 'fromOtherFavorFlag')]");
							if (!$enableRadio[0]){                                                                
                                $merr+=1;
                                $errMsg.= "<br>".$enableRadio[1];
                            }
								$enableRadio[1]->click();
								$driver->getMouse()->mouseMove($enableRadio[1]->getCoordinates());
								$driver->getMouse()->click();
```

**Comment by nicktan147** [comment]
Issue resolved

**Comment by gabrielpreston** [comment]
Why are you switching from `$enableRadio[0]` to `$enableRadio[1]` in your if block?

**Comment by nicktan147** [comment]
In the variable $enableRadio, 

`$enableRadio = $engine->findWebElem($driver,"Enable Radio Input To: ","xpath","//input[contains(@id, 'fromOtherFavorFlag')]");`

It returns in array form, `$enableRadio[0]` will return boolean, while `$enableRadio[1]` will return the value I want

**Comment by gabrielpreston** [comment]
Are you still experiencing this problem? If so, can you share the error you are getting? As well as a dump of what the value is for `$enableRadio`?

**Comment by nicktan147** [comment]
@gabrielpreston  Apparently, radio button has name, therefore it selects the first option. I changed to other method of finding, the best way to identify it is using xpath to find onclick which is different in both radio options. Anyway thanks for your support!
