### ISSUE TITLE
Faerfoks Running in the background - or how to save resources?

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#355]
All kind of testing time!
Interested in such an unusual question... is it possible in Linux to run Firefox in the background that would be the window with the current test displayed on the display? is this possible? and will it save resources? or maybe somebody will share their experience how to minimize resources expended on testing the same site?

**Comment by OndraM** [comment]
@StasToken Sorry, I'm not really sure I understand the question :-). But you have several ways how to start Firefox for Selenium in Linux:
- In foreground, so the new windows will pop on top of your windows
- Encapsulated in virtual framebuffer, like Xvfb
- Inside Docker with prepared [Selenium images](https://hub.docker.com/r/selenium/)

I guess the first option would need most resources from this options, and the Xvfb will need a bit less of them. Docker is also not a wrong choice.

**Comment by StasToken** [comment]
I was just a year ago saw an article where a programmer starts firefox in console mode, passing it is even alleged screen resolution, Firefox started in the console, I'm now interested whether it is possible thus to save resources by not showing the graphics... the trouble is that I can't find this material on the Internet 

In General, the question is left open, please write any ideas and do not hesitate - I think this will interest many more people.

**Comment by OndraM** [comment]
IMHO there are plenty of resources explaining this - you can just google for keyword "headless firefox selenium" or something like that. Few random options:
- http://tobyho.com/2015/01/09/headless-browser-testing-xvfb/ 
- http://www.alittlemadness.com/2008/03/05/running-selenium-headless/
- http://elementalselenium.com/tips/38-headless
