### ISSUE TITLE
Tell me how to open multiple tabs simultaneously in the browser?

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#356]
Is it possible open multiple tabs in one browser? 
I use code:

```
foreach ($url as $value){
$driver->get($value);
$driver->manage()->deleteAllCookies();
$driver->manage()->addCookie(array(
  'name' => 'cookie_name',
  'value' => 'cookie_value',
));
$cookies = $driver->manage()->getCookies();
//end
}
```

But when you open new tab it will kill the old I need to open 3 tabs in parallel, do not tell me is that possible to do? examine any, even the most unusual ways.

**Comment by OndraM** [comment]
@StasToken Hi, have look to similar question on StackOverflow. Hope it helps! https://stackoverflow.com/questions/35391009/open-new-tab-in-chrome-using-selenium-facebook-php-webdriver

**Comment by StasToken** [comment]
It's not really helped me, their example does not work gives quite strange error: PHP Notice:  Use of undefined constant CONTROL - assumed 'CONTROL'  And opening new tabs is not happening...

**Comment by StasToken** [comment]
replace code `$kbd->sendKeys(WebDriverKeys::CONTROL,'t');` Error is gone but the tab still doesn't open
