### ISSUE TITLE
mouseMove is not working

### ISSUE THREAD

**Issue by grikis** [facebook/php-webdriver#359]
I'm using this command:
$element = $this->driver->findElement(WebDriverBy::cssSelector('li.level0:nth-child(5)'));
        $this->driver->getMouse()->mouseMove( $element->getCoordinates() );
But when i run it i get UnknownCommandException: POST /session/b9c56994-1dc4-4631-8377-2d0a331fc60f/moveto did not match a known command

**Comment by OndraM** [comment]
Hi, this looks like in issue in Geckodriver, the new Selenium driver shipped with Firefox 48+. See https://github.com/mozilla/geckodriver/issues/159 and https://github.com/SeleniumHQ/selenium/issues/2285. You could either use Firefox 47.0.1 or Firefox ESR version to use the previous, non-marionette based firefox selenium driver.
