### ISSUE TITLE
Cannot find firefox binary in PATH

### ISSUE THREAD

**Issue by knide** [facebook/php-webdriver#361]
Hi I'm new to selenium and php web driver, I'm on OSX and I already have the selenium standalone server running.

But when I run example.php I get this error:

> Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\UnknownServerException' with message 'Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: MAC
> Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
> System info: host: 'Knides-MacBook-Pro.local', ip: 'x.x.x.x', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_112'
> Driver info: driver.version: FirefoxDriver' in /Users/knide/Sites/php-webdriver-community/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:121
> Stack trace:
> #0 /Users/knide/Sites/php-webdriver-community/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php(318): Facebook\WebDriver\Exception\WebDriverException::throwException(13, 'Cannot find fir...', Array)
> #1 /Users/knide/Sites/php-webdriver-community/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(100): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
> #2 /Users/k in /Users/knide/Sites/php-webdriver-community/vendor/facebook/webdriver/lib/Exception/WebDriverException.php on line 121

I have firefox installed obviously, so I'm not sure why it can't be found. Its on my /Applications/Firefox.app

Any help would be appreciated. Thanks!

**Comment by vebmaster** [comment]
> @knide How did you solve this issue?! Plz Help! Thanks.

install firefox :)

**Comment by atefBB** [comment]
@vebmaster Thx !
