### ISSUE TITLE
about:config Firefox

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#362]
Good day, interested in the question, the Mozilla firefox browser has a settings page which is available on request in the address bar about:config can I change these settings using the php-webdriver
For example:
gfx.font_rendering.directwrite.enabled = true

**Comment by OndraM** [comment]
Hi, instead of going through the about:config interface you can alter the Firefox configuration options using capabilities and `FirefoxProfile` class:

```
$capabilities = DesiredCapabilities::firefox();
$profile = new FirefoxProfile();
$profile->setPreference('gfx.font_rendering.directwrite.enabled', true);

$capabilities->setCapability(FirefoxDriver::PROFILE, $profile);
```

**Comment by StasToken** [comment]
If you use an error occurs
error : PHP Fatal error:  Uncaught Error: Class 'Facebook\WebDriver\FirefoxProfile' not found in 
Everything else is working fine what it could be?

**Comment by StasToken** [comment]
Oh... sory... I was stupid and forgot to connect Facebook\WebDriver\FirefoxProfile :)
