### ISSUE TITLE
ImplicitlyWait doesn't work

### ISSUE THREAD

**Issue by grikis** [facebook/php-webdriver#363]
I added this line before my get method 
$this->driver->manage()->timeouts()->implicitlyWait(30);
But if element doesn't show up immediately, test fails. 
Tests are running in latest chrome version with 2.53.1 selenium

**Comment by OndraM** [comment]
@grikis What browser in which version do you use? Could you also provide the error output from both php-webdriver and selenium server? Thanks!

**Comment by grikis** [comment]
$this->driver->findElement(WebDriverBy::cssSelector('.link-wishlist > span:nth-child(2)'))->click();
$this->driver->findElement(WebDriverBy::cssSelector('button.button.btn-checkout'))->click();
In this piece of code after clicking on first element the second one appears after 1-2 seconds. And it shows this error ElementNotVisibleException: element not visible.
But if I add sleep(3) between them everything works fine.

**Comment by gohelkiran** [comment]
Same issue, implicit wait not working when waiting for ajax request
$driver->manage()->timeouts()->implicitlyWait(10);

**Comment by OndraM** [comment]
@gohelkiran Could you please provide mor information? Code you use, browser version and Selenium server version?

**Comment by gohelkiran** [comment]
I am using selenium-server-standalone-3.0.1 and  Browser Firefox 50

I am using below code for wait.
$driver->manage()->timeouts()->implicitlyWait($waitTime);
$waitTime in seconds

**Comment by OndraM** [comment]
I wrote functional test ensuring the implicit wait works - see #408.

So I'm closing this for now - but anyone please open new bug if you have an reproducible scenario.

Firefox users also make sure you are having latest Firefox and Geckodriver.

**Comment by emilorol** [comment]
Hi,

I can confirm that the wait() is not really working.

```php
$driver->manage()->timeouts()->implicitlyWait(10);
```
or
```php
$driver->wait(10, 1000)->until(
  WebDriverExpectedCondition::visibilityOf($driver->findElement(WebDriverBy::id('first_name')))
);
```
or
```php
$driver->wait(10, 1000)->until(
  WebDriverExpectedCondition:: presenceOfElementLocated($driver->findElement(WebDriverBy::id('first_name')))
);
```
I have try a few more combinations without luck.

Running on: 
Ubuntu 16.04 
Selenium 3.3.1 
Chrome driver 2.28.455506
Google Chrome 57.0.2987.110 (64-bit)

I am testing an app written on jQuery that add the fields to the DOM and I need to wait until the element is present.

**Comment by OndraM** [comment]
@emilorol Hi, the wait() is most probably working, I guess there will be some other issue.

What is the exact error you get?

What is the command you use to start selenium server?

Could you please provide some reproducible scenario?

Thank you!

**Comment by emilorol** [comment]
Thank you for the quick response.

The selenium server is running smooth and processing all the tests. I use the selenium standalone server as a service on the Ubuntu Server. From my Mac I execute the PHP file with the test and it run it on the server. I use a VNC (x11nvc) to see what is going on with the headless chrome running on the server.

This is the error I get:

```php
Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\NoSuchElementException' with message 'no such element: Unable to locate element: {"method":"id","selector":"first_name"}
  (Session info: chrome=57.0.2987.110)
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 4.4.0-71-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 34 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'selbox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-71-generic', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.28.455506 (1 in /Users/admin/Documents/Sites/test-site/vendor/facebook/webdriver/lib/Exception/WebDriverException.php on line 102
```

**Comment by OndraM** [comment]
Oh, I see. And is this the error you get when running what code exactly?

If it is the first case:
```
$driver->wait(10, 1000)->until(
  WebDriverExpectedCondition::visibilityOf($driver->findElement(WebDriverBy::id('first_name')))
);
```

then you MUST already have the element loaded and you only waits until it became visible (otherwise the `findElement` method throws an exception). . See documentation of the method: "An expectation for checking that an element, known to be present on the DOM of a page, is visible."

But if the element is not present on the page at all and you are waiting until it appears in the DOM and became visible, you should use `visibilityOfElementLocated` instead:

```
$driver->wait(10, 1000)->until(
  WebDriverExpectedCondition::visibilityOfElementLocated($WebDriverBy::id('first_name'))
);
```

**Comment by emilorol** [comment]
This is the code I am running:

```php
$driver->wait(10, 1000)->until(
  WebDriverExpectedCondition::visibilityOfElementLocated($driver->findElement(WebDriverBy::id('first_name')))
);

$driver->findElement(WebDriverBy::id('first_name'))->click();
$driver->getKeyboard()->sendKeys('James');
```
No luck still.

**Comment by OndraM** [comment]
If you call call the findElement method when the element is not present on the page, it will throws the exception. But the `visibilityOfElementLocated` method accept the WebDriverBy instance - see my the example above.

**Comment by emilorol** [comment]
So I should use it like this:

```php
$driver->wait(10, 1000)->until(
  WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::id('first_name'))
);
```
in your example you put $WebDriverBy and that throw me off a bit.

**Comment by OndraM** [comment]
@emilorol Yes, sorry, that was a typo :).

**Comment by emilorol** [comment]
It work like a charm. Thank you very much.

**Comment by emilorol** [comment]
I updated the wiki page with this example for anyone in the same boat.

[HowTo-Wait](https://github.com/facebook/php-webdriver/wiki/HowTo-Wait#wait-until-an-element-is-added-to-the-dom)

Once again thank you.

**Comment by OndraM** [comment]
@emilorol 👍 great, thanks!
