### ISSUE TITLE
WebDriverActions->sendKeys() don't remove actions after perform()

### ISSUE THREAD

**Issue by eyepin** [facebook/php-webdriver#366]
\Facebook\WebDriver\Interactions\WebDriverActions

$actions = new WebDriverActions($webDriver);
$actions->sendKeys(null, 'abc')->perform(); // send keys 'abc'
$actions->sendKeys(null, '123')->perform(); // send keys 'abc123' expected only '123'

shouldn't perform() remove the action?

Work around: 
$actions1 = new WebDriverActions($webDriver);
$actions2 = new WebDriverActions($webDriver);

$actions1->sendKeys(null, 'abc')->perform();
$actions2->sendKeys(null, '123')->perform();

**Comment by OndraM** [comment]
@eyepin No, it is working as expected. WebDriverActions is a builder type object - you define actions you want to perform, and once you want them to be executed, you call the `perform()` method to execute all of the defined actions. But you may for example want to perform the same sequence later, so you just call the perform again.
