### ISSUE TITLE
custom header

### ISSUE THREAD

**Issue by nekulin** [facebook/php-webdriver#368]
Example:

```
selenium.start("addCustomRequestHeaders=true");
selenium.addCustomRequestHeader("HEADER_NAME", "HEADER_VALUE");
```

How to do it ?

**Comment by OndraM** [comment]
Hi, the addCustomRequestHeaders capability was part of obsolete Selenium RC and is not part of Selenium WebDriver. There is long-standing policy of Selenium project to not manipulate the HTTP protocol itself by Selenium - only focus on emulating user actions. So if you really need this, you must take another approach, like BrowserMob proxy, browser extension etc. See eg. https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/2047
