### ISSUE TITLE
How to click on element which is in the frame?

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#369]
Good time - tell me how to click on element which is in a frame on the page?
Tried to click like on a normal page does not work...

**Comment by edno** [comment]
Did you had a look at the wiki [Alert, Window Tab, frame iframe and active element](https://github.com/facebook/php-webdriver/wiki/Alert,-Window-Tab,-frame-iframe-and-active-element)?

**Comment by gabrielpreston** [comment]
You need to switch context to the iframe in question. Check out what @edno referenced you to, specifically https://github.com/facebook/php-webdriver/wiki/Alert,-Window-Tab,-frame-iframe-and-active-element#frame-iframe

**Comment by StasToken** [comment]
I'm a little confused... So what I need to switch to iframe, I realized.... 
I've got this code
`<div>
		
		<div>


				<div>
					<div>
<noindex>
<iframe>

<html><body>
<a href="#">Clic</a>
</body></html>

</iframe>
</noindex>						
						<div></div>
					</div>
				</div>

			
		</div>
	
</div>`
I'm trying to click like that, and still get the error
`$my_frame = $driver->findElement(WebDriverBy::xpath('/div[2]/div/div/div/div/noindex/iframe'));
$driver->switchTo()->frame($my_frame);
$element = $driver->findElement(WebDriverBy::xpath("/html/body/a"));
$driver->getMouse()->mouseMove($element->getCoordinates());
$element->click();`
He can't find the frame Don't prompt and the frames for the first time practice to be honest?!

**Comment by StasToken** [comment]
Thank you to everyone who responded. I after all itself could understand what was wrong. The question can be considered closed.
