### ISSUE TITLE
Convenience class for checkbox

### ISSUE THREAD

**Issue by OndraM** [facebook/php-webdriver#373]
Similary as we have [WebDriverSelect](https://github.com/facebook/php-webdriver/blob/community/lib/WebDriverSelect.php) for `<select>`, it may be handy to have also something like WebDriverCheckbox for `<input type="checkbox">` elements with helper methods:
- check
- uncheck
- isChecked

and maybe some more.

**Comment by deleugpn** [comment]
What about `radio` input? Should `checkbox` and `radio` be treated as one?

**Comment by OndraM** [comment]
@deleugpn True. I have some of this WIP already prepared, and it includes both checkboxes and radio buttons.  I hope to send it soon :).
