### ISSUE TITLE
Test failure when using with Grid causes window not to shut

### ISSUE THREAD

**Issue by jasonr-ffrees** [facebook/php-webdriver#377]
Hi,

I've built up a suite of tests using php-webdriver with a combination of other tools (including Selenium Grid).

I've been looking into some issues we've been having with grid sessions not being closed upon failure, therefore taking up slots on the gird and queueing other tests.

On investigating I found that there appears to be an uncaught exception when an element is not found (WebDriverCurlException). Once this exception is thrown, the test dies instantly, not allowing any post-test actions to be carried out (such as running the quit function).

I've found that I can catch this exception, print a relevant error message and close the session, however I'd rather not surround tests/actions with a try/catch all of the time.

Have any of you had any experience with this issue before? Is there a preferred workaround?

Here's a simple test where I'm seeing the issue:

```php
<?php

require('vendor/autoload.php');

$host = 'http://localhost:4444/wd/hub';
$driver = \Facebook\WebDriver\Remote\RemoteWebDriver::create($host, \Facebook\WebDriver\Remote\DesiredCapabilities::chrome());
$driver->manage()->timeouts()->implicitlyWait(30);
$driver->get('http://google.co.uk');
$driver->findElement(\Facebook\WebDriver\WebDriverBy::id('fakeElement'))->click();
$driver->quit();
```

And here's the terminal output when I run it via the command line:

```
PHP Fatal error:  Uncaught exception 'Facebook\WebDriver\Exception\WebDriverCurlException' with message 'Curl error thrown for http POST to /session/c6b12ec3-4189-49bb-94fd-e337a7ce6dc8/element with params: {"using":"id","value":"fakeElement"}
```

**Comment by cryptton2004** [comment]
Hi,

I don't know if this is the right way, but I found it on some forums and I'm using it successfully right now:
At the end of your setUp() function:
```
    protected function setUp(){
        .......
        .......
        //Start of Custom Shutdown
        //If a Fatal Error is returned, this will close the opened browser
        //otherwise it will stay open forever :(
        $that = $this;
        register_shutdown_function(function() use ($that) {
            if (!$that->isTearDownHappened()) {
                $that->tearDown();
            }
        });
        //End of Custom Shutdown
    }

    protected function tearDown() {
        //$this->tearDownHappened = true; //This is part of Custom Shutdown
        $this->tearDownHappened = true;
        $this->driver->quit();
    }

    //This entire function is part of Custom Shutdown
    public function isTearDownHappened() {
        return $this->tearDownHappened;
    }
```
Hope it helps.

**Comment by OndraM** [comment]
@jasonr-ffrees Hi, the issue is that you use implicitlyWait with value same/greater than timeout for requests between php-webdriver and the selenium server (which is 30 sec by default). So you got WebDriverCurlException because of the request timeout, not NoSuchElementException, which should occur instead.

You can either:
- use implicitlyWait with value less than 30
- set greater timeout when creating WebDriver instance, like 45 seconds:
```
$driver = \Facebook\WebDriver\Remote\RemoteWebDriver::create(
    $host, 
    \Facebook\WebDriver\Remote\DesiredCapabilities::chrome(), 
    30000, 
    45000
);
```

But my suggestion would be even different - always use [explicit waits](https://github.com/facebook/php-webdriver/wiki/HowTo-Wait#explicit-waits) instead of implicit ones ;-).

**Comment by jasonr-ffrees** [comment]
Hey guys,

Apologies for the late response. I managed to fix this with a combination of tweaking the wait times and amending my hooks. Makes sense now I think about it.

Seems to be behaving now, cheers for all of your help!

**Comment by imsheng** [comment]
@jasonr-ffrees How to do it？
