### ISSUE TITLE
API documentation is not being updated

### ISSUE THREAD

**Issue by gohelkiran30** [facebook/php-webdriver#378]
Please update the document for latest available methods
http://facebook.github.io/php-webdriver/namespaces/default.html

For example, below URL not lists any methods for this class
http://facebook.github.io/php-webdriver/classes/WebDriverAction.html

There are many methods available though as per file content.
https://github.com/facebook/php-webdriver/blob/edf9659e1c23cc814d9c717eec07ee3e3c0d6a31/lib/Interactions/WebDriverActions.php

It is very hard to search for any specific method without proper document

**Comment by OndraM** [comment]
@gohelkiran30 Hi, the API generator is obviously broken. Maybe @gfosco can do something about it? 

And BTW @gohelkiran30, you may be looking for https://facebook.github.io/php-webdriver/classes/WebDriverActions.html - is is outdated, however it contains the methods of WebDriverActions class. I would also suggest using some IDE (like PhpStorm or NetBeans), that will help you with autocompleting names of the methods etc.

**Comment by OndraM** [comment]
API doc is now again up-to-date and available on https://facebook.github.io/php-webdriver/ .

**Comment by OndraM** [comment]
API doc is now again up-to-date and available on https://facebook.github.io/php-webdriver/ .

Thanks @gohelkiran30 for the report! 👍
