### ISSUE TITLE
executeScript() not working with setAttribute()

### ISSUE THREAD

**Issue by hariesnurikhwan** [facebook/php-webdriver#379]
When I click "Sign In" button the value isn't really set by selenium.

```
$element = $driver->findElement(
    WebDriverBy::name('username')
);

$driver->executeScript('arguments[0].setAttribute("value", "myusername")', [
	$element
]);
````

**Comment by OndraM** [comment]
@hariesnurikhwan Hi, what version of Selenium standalone server and what Browser do you use? Could you provide reproducible testcase, including the exact HTML? Does php-webdriver provide any error?

**Comment by OndraM** [comment]
Ping @hariesnurikhwan ?

**Comment by OndraM** [comment]
The execute script appears to be working in functional tests. There may be some issue with Marionette Geckodriver, but it is still beta, so it is expected to not be feature complete for a while

So I'm closing this one - but if reproducible testcase is provided I can have a look :-).
