### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Facebook\WebDriver\Exception\NoSuchDriverException' 

### ISSUE THREAD

**Issue by zloadmin** [facebook/php-webdriver#382]
**My code:**
```
<?php
namespace Facebook\WebDriver;
use Facebook\WebDriver\Chrome\ChromeDriver;
require_once('vendor/autoload.php');
putenv("webdriver.chrome.driver=/usr/local/bin/chromedriver");
$driver = ChromeDriver::start();
$driver->get('http://fl.ru/');
echo  $driver->getTitle() . PHP_EOL;
echo  $driver->getCurrentURL() . PHP_EOL;
```

**I get:**
```

PHP Fatal error:  Uncaught exception 'Facebook\WebDriver\Exception\NoSuchDriverException' with message 'no such session
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.11.6 x86_64)' in /Projects/freelance/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:107
Stack trace:
#0 /Projects/freelance/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php(318): Facebook\WebDriver\Exception\WebDriverException::throwException(6, 'no such session...', Array)
#1 /Projects/freelance/vendor/facebook/webdriver/lib/Remote/Service/DriverCommandExecutor.php(54): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 /Projects/freelance/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(547): Facebook\WebDriver\Remote\Service\DriverCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#3 /Projects/freelance/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(195): Facebook\WebDriver\ in /Projects/freelance/vendor/facebook/webdriver/lib/Exception/WebDriverException.php on line 107

Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\NoSuchDriverException' with message 'no such session
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.11.6 x86_64)' in /Projects/freelance/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:107
Stack trace:
#0 /Projects/freelance/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php(318): Facebook\WebDriver\Exception\WebDriverException::throwException(6, 'no such session...', Array)
#1 /Projects/freelance/vendor/facebook/webdriver/lib/Remote/Service/DriverCommandExecutor.php(54): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 /Projects/freelance/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(547): Facebook\WebDriver\Remote\Service\DriverCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#3 /Projects/freelance/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(195): Facebook\WebDriver\ in /Projects/freelance/vendor/facebook/webdriver/lib/Exception/WebDriverException.php on line 107
```

**Comment by OndraM** [comment]
Hi, could you please try it against the master branch? There have been some changes related to ChromeDriver, which are not yet released in tagged version.

In your composer.json:

```
"require": {
    "facebook/webdriver": "dev-master",
    ...
```
and run `composer update`.

**Comment by zloadmin** [comment]
**Working! Thanks!**

**Comment by OndraM** [comment]
@zloadmin Great :-). And did you use dev-master or dev-community? I realized I wrote dev-master - could you please try it also against dev-community branch?

**Comment by zloadmin** [comment]
I used "dev-master", but "dev-community" working too.

**Comment by OndraM** [comment]
@zloadmin Ok, so please prefer dev-community, as dev-master branch is no longer maintained :).

**Comment by zloadmin** [comment]
@OndraM Ok. Thanks!

**Comment by taylorotwell** [comment]
I'm having a similar issue. If I create WebDriver instance in two different PHPUnit test cases it throws this error when trying to run the second test class:

Facebook\WebDriver\Exception\NoSuchDriverException: no such session
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.2 x86_64)

This is on the `dev-community` branch.

**Comment by taylorotwell** [comment]
Nevermind. I believe this was a problem on my end. Thanks.

**Comment by vunv92** [comment]
@taylorotwell Can you explain your solution, i am having same isssue.

**Comment by cerw** [comment]
Stlll having this issue on dev-community or lastest version.

**Comment by OndraM** [comment]
@cerw Could you please provide whole error output + maybe reproducible testcase? This would help dig into the issue. Thanks!

**Comment by tangtingting** [comment]
just like @taylorotwell ,If I create WebDriver instance in two different PHPUnit test classes it throws this error when trying to run the second test class:

**Problem**
2017-12-08 12:29:53 Error Message: Facebook\WebDriver\Exception\NoSuchDriverException: no such session
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86_64) in D:\test\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:100
Stack trace:
#0 D:\test\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throwException(6, 'no such session...', Array)
#1 D:\test\vendor\facebook\webdriver\lib\Remote\Service\DriverCommandExecutor.php(55): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 D:\test\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(535): Facebook\WebDriver\Remote\Service\DriverCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#3 D:\test\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(214): Facebook\WebDriver\Remote\RemoteWebDriver->execute('get', Array)
#4 D:\test\CIMP\lib\ChromeLibrary.php(25): Facebook\WebDriver\Remote\RemoteWebDriver->get('http://192.168....')
#5 D:\test\CIMP\lib\CreateDriverInformation.php(15): ChromeLibrary->loginCIMP('http://192.168....', 'auto_test', '123456')
#6 D:\test\CIMP\CimpTest.php(24): CreateDriverInformation->__construct('http://192.168....', 'auto_test', '123456')
#7 [internal function]: CimpTest->testCreateDriver()
#8 D:\test\vendor\phpunit\phpunit\src\Framework\TestCase.php(1062): ReflectionMethod->invokeArgs(Object(CimpTest), Array)
#9 D:\test\vendor\phpunit\phpunit\src\Framework\TestCase.php(913): PHPUnit_Framework_TestCase->runTest()
#10 D:\test\vendor\phpunit\phpunit\src\Framework\TestResult.php(686): PHPUnit_Framework_TestCase->runBare()
#11 D:\test\vendor\phpunit\phpunit\src\Framework\TestCase.php(868): PHPUnit_Framework_TestResult->run(Object(CimpTest))
#12 D:\test\vendor\phpunit\phpunit\src\Framework\TestSuite.php(722): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#13 D:\test\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(517): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#14 D:\test\vendor\phpunit\phpunit\src\TextUI\Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array, true)
#15 D:\test\vendor\phpunit\phpunit\src\TextUI\Command.php(116): PHPUnit_TextUI_Command->run(Array, true)
#16 D:\test\vendor\phpunit\phpunit\phpunit(52): PHPUnit_TextUI_Command::main()
#17 {main}

php version:7.1.10
phpunit version:  5.7.23
chrome version:63.0
chromeDriver version:2.3.3

**Comment by tangtingting** [comment]
I have solved by adding "quite chrome" after every testCase

**Comment by tangtingting** [comment]
I have solved by adding "quite chrome" after every testCase
