### ISSUE TITLE
Passing acceptInsecureCerts to marionette driver

### ISSUE THREAD

**Issue by robgudgeon** [facebook/php-webdriver#384]
Hi

I'm trying to overcome the issue with [firefox not accepting insecure certificates](https://bugzilla.mozilla.org/show_bug.cgi?id=1103196) - these are internal, dev sites.

I'm using selenium 3.0.1, firefox nightly 53.0a1 & gecko driver 0.12.0. Selenium is launched as 
`java -Dwebdriver.gecko.driver="C:\selenium\geckodriver.exe" -jar selenium-server-standalone-3.0.1.jar`

My code looks like this:

> $profile = new \FirefoxProfile();
> $capabilities = \DesiredCapabilities::firefox();
> $capabilities->setCapability(\FirefoxDriver::PROFILE, $profile);
> $capabilities->setCapability('marionette', true);
> $capabilities->setCapability('testCap', true);
> $capabilities->setCapability('acceptInsecureCerts', true);

But firefox nightly is not being passed the acceptInsecureCerts capability. This is the output from Selenium:

> UnknownServerException: 
> Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
> System info: host: 'BTP121353', ip: '10.109.20.55', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
> Driver info: org.openqa.selenium.firefox.FirefoxDriver
> Capabilities [{moz:profile=C:\Users\607963~1\AppData\Local\Temp\rust_mozprofile.xIjsxxqz2SI1, rotatable=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIA<snipped>aAwAAAAA=}, platform=ANY, proxy={}, specificationLevel=0, moz:accessibilityChecks=false, testCap=true, acceptInsecureCerts=false, browserVersion=53.0a1, platformVersion=6.1, moz:processID=7284, browserName=firefox, platformName=windows_nt, firefox_profile=UEsDBBQAAAAAAOljJEoAAAAAAAAAA...}]

I'm a little confused as marionette=true is passed on as a capability, but a test/meaningless capability (testCap=true) is passed on as a firefox options, but my acceptInsecureCerts=true is ignored, or overridden.

Does anyone have any ideas, or got any working code to use marionette & acceptInsecureCerts?

Might be worth pointing out I'm using an older version of the community branch, if that matters.

**Comment by OndraM** [comment]
@robgudgeon Hi, could you please try with the latest php-webdriver version?

I don't hve the Aurora Firefox, so I cannot verify it actually works, but the capability is being passed to selenium as it is supposed to (latest php-webdriver; selenium 3.0.1)

```
13:56:04.536 INFO - Executing: [new session: Capabilities [{testCap=true, acceptInsecureCerts=true, browserName=firefox, platform=ANY, firefox_profile=UEsDBBQAAAAAAAJvJErf9RXUMgAAA...}]])
```

BTW you don't have to use marionette = true, as the marionette driver is default with Selenium 3.

**Comment by robgudgeon** [comment]
Hi, thanks for the reply.

Sorry, turns out I'm using the master branch, not community. I've updated to the latest master.

I've configured Selenium to log to a file and it seems that yes, the capability is being passed on:

> 13:11:00.352 INFO - Executing: [new session: Capabilities [{testCap=true, acceptInsecureCerts=true, browserName=firefox, platform=ANY, firefox_profile=UEsDBBQAAAAAAF1pJEoAAAAAAAAAA...}]])
> 13:11:00.362 INFO - Creating a new session for Capabilities [{testCap=true, acceptInsecureCerts=true, browserName=firefox, platform=ANY, firefox_profile=UEsDBBQAAAAAAF1pJEoAAAAAAAAAA...}]
> 

but somehow this isn't being honoured by Selenium/marionette/firefox, as I still get the following output:

> UnknownServerException: 
> Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
> System info: host: 'BTP121353', ip: '10.109.20.55', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
> Driver info: org.openqa.selenium.firefox.FirefoxDriver
> Capabilities [{moz:profile=C:\Users\607963~1\AppData\Local\Temp\rust_mozprofile.9Rmhp9Djxmko, rotatable=false, firefoxOptions={args=[], profile=UEsDBBQ<snipped>ADaAwAAAAA=}, platform=ANY, proxy={}, specificationLevel=0, moz:accessibilityChecks=false, testCap=true, acceptInsecureCerts=false, browserVersion=53.0a1, platformVersion=6.1, moz:processID=11052, browserName=firefox, platformName=windows_nt, firefox_profile=UEsDBBQAAAAAAHtoJEoAAAAAAAAAA...}]

Interestingly, I've commented out the line to set marionette to true and marionette=true is no longer in the Selenium exception output. 

So it doesn't appear to be a php-webdriver issue, must be related to my Selenium/marionette/firefox nightly set up (not sure what, though, as it's all default settings & latest versions)

**Comment by OndraM** [comment]
@robgudgeon Ok, this may be issue with the latest version. You can try Selenium 3.0.2 once it is released. If you need to accept ssl certs and Firefox, you can use Firefox 47.0.1, Firefox ESR or use it through Docker. And please don't forget to let us know if you will find the issue is actually somehow related to php-webdriver - I will do by best to fix it then (though as a sidenote - the master branch is no longer maintained, so any possible fixes will come to community branch).

Thank you and good luck setting it up :)
