### ISSUE TITLE
Need help setting it up

### ISSUE THREAD

**Issue by AymanEG** [facebook/php-webdriver#385]
Hello there,

I tried to use @ win 10 x64 following the guide : https://github.com/facebook/php-webdriver#installation

I faced a problem with gecko driver error msg so I downgrade the server to this version selenium-server-standalone-2.53.1.jar and stop creating this error.

I use the default example.php and getting this errors : 

```
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"firefox","platform":"ANY","firefox_profile":"UEsDBBQAAAAAAKK8JErf9RXUMgAAADIAAAAHAAAAdXNlci5qc3VzZXJfcHJlZigicmVhZGVyLnBhcnNlLW9uLWxvYWQuZW5hYmxlZCIsIGZhbHNlKTsKUEsBAhQDFAAAAAAAorwkSt\/1FdQyAAAAMgAAAAcAAAAAAAAAAAAAALaBAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAAVwAAAAAA"}}

Operation timed out after 30000 milliseconds with 0 bytes received in C:\Bitnami\wordpress\apps\wordpress\htdocs\tools\lib\Exception\WebDriverException.php:92
Stack trace:
#0 C:\Bitnami\wordpress\apps\wordpress\htdocs\tools\lib\Remote\HttpCommandExecutor.php(285): Facebook\WebDriver\Exception\WebDriverException::throwException(-1, 'Curl error thro...', Array)
#1 C:\Bitnami\wordpress\apps\wordpress\htdocs\tools\lib\Remote\RemoteWebDriver.php(100): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 C:\Bitnami\wordpress\apps\wordpress\ht in C:\Bitnami\wordpress\apps\wordpress\htdocs\tools\lib\Exception\WebDriverException.php on line 92

```
Please advise
regards

**Comment by OndraM** [comment]
Hi, Selenium server 2.53.1 is only compatible with Firefox 47.0.1 or Firefox ESR. So you must have installed this version of Firefox.

But selenium 3.x is compatible either:
- with Firefox 48+, but you need to install also [geckodriver](https://github.com/mozilla/geckodriver/releases) and provide path to it like this: 
`java -Dwebdriver.gecko.driver="/opt/bin/geckodriver" -jar vendor/bin/selenium-server-standalone-3.0.1.jar`
- with firefox 47.0.1 or Firefox ESR, byt you need to tell Selenium to not attempt to use the marionette/geckodriver like this:
`ava -Dwebdriver.firefox.marionette=false -jar vendor/bin/selenium-server-standalone-3.0.1.jar`

**Comment by AymanEG** [comment]
Thanks for your answer,

I followed  gecko driver part  (Using latest firefox 50.1.0) ,should not I expect some exe files  ?! all I do is:
git clone the github and use this to start the server:

`java -Dwebdriver.gecko.driver="C:\Bitnami\wordpress\apps\wordpress\htdocs\tools\bin\geckodriver" -jar vendor/bin/selenium-server-standalone-3.0.1.jar
`
Kindly update the documentations for other guys outhere :-)

However , I still have this error msg using the example.php

```
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnknownServerException: The driver executable is a directory: C:\Bitnami\wordpress\apps\wordpress\htdocs\tools\bin\geckodriver in C:\Bitnami\wordpress\apps\wordpress\htdocs\tools\lib\Exception\WebDriverException.php:121
Stack trace:
#0 C:\Bitnami\wordpress\apps\wordpress\htdocs\tools\lib\Remote\HttpCommandExecutor.php(318): Facebook\WebDriver\Exception\WebDriverException::throwException(13, 'The driver exec...', Array)
#1 C:\Bitnami\wordpress\apps\wordpress\htdocs\tools\lib\Remote\RemoteWebDriver.php(100): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 C:\Bitnami\wordpress\apps\wordpress\htdocs\tools\example.php(10): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Array, 5000)
#3 {main}
  thrown in C:\Bitnami\wordpress\apps\wordpress\htdocs\tools\lib\Exception\WebDriverException.php on line 121
```

Any help will be appreciated
Best regards

**Comment by AymanEG** [comment]
@OndraM  , Can you please follow this up ?!

**Comment by OndraM** [comment]
@AymanEG Hi, sorry, I'm volunteer maintainer, please understand I do not provide on-demand support, as my time I can give to this project is limited. But we definitely welcome other volunteers willing to help and send pull requests - eg. with updating the documentation as you suggest.

If you need further help, I suggest asking a question on eg. http://stackoverflow.com/.

And BTW I see error message "The driver executable is a directory" in the output you provide, so I guess the path to geckodriver is wrong.

**Comment by AymanEG** [comment]
Thanks for your time

**Comment by robgudgeon** [comment]
@AymanEG just in case you hadn't figured it out, you need to point to geckodriver.exe, not just the directory containing the driver, e.g. 

`java -Dwebdriver.gecko.driver="C:\Bitnami\wordpress\apps\wordpress\htdocs\tools\bin\geckodriver\geckodriver.exe" -jar vendor/bin/selenium-server-standalone-3.0.1.jar`

**Comment by AymanEG** [comment]
@robgudgeon  thanks for your reply.

Thats what I am missing , for some reason I dont have any exe at the directory , should I build it or do something else ?! I just clone the git @ https://github.com/mozilla/geckodriver

It will be better if you point to the exe url , I am using windows 10x64

Best regards

**Comment by gabrielpreston** [comment]
Download the appropriate release from https://github.com/mozilla/geckodriver/releases

**Comment by AymanEG** [comment]
Oh thanks guys , my bad ! I dont know how I missed it.
