### ISSUE TITLE
Tell me how to set cookies for a domain?

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#401]
Hi. Here's a question I have a website example.com ( which comes to the browser ) - and parallel connection still goes on domain.com - here I need to set cookies for domain.com tell me how can I do that?!
I used the code:
`$driver->manage()->addCookie(array(
  'name' => 'value',
));`
but this code only sets cookies for the current domain, how do I set cookies for another domain?!

**Comment by OndraM** [comment]
Hi can provide the domain using 'domain' key provided to the addCookie() method. See the method documentation for all available options:
https://github.com/facebook/php-webdriver/blob/2ee72c3a2e096a62da2c952dd66f738ec186a589/lib/WebDriverOptions.php#L37-L54

```
$driver->manage()->addCookie([
    'name' => 'cookie_name',
    'value' => 'cookie_value',
    'domain' => '.example.com',
]);
```

Also note you need to be on the domain that the cookie will be valid for. You cannot set cookie for domain different from the one where the browser is currently opened. See selenium docs for more information:
http://docs.seleniumhq.org/docs/03_webdriver.jsp#cookies

**Comment by StasToken** [comment]
OndraM What you wrote does not work, when trying to add the cookies for the domain I get this error:

> PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\InvalidCookieDomainException: You may only set cookies for the current domain
