### ISSUE TITLE
example.php fails: TypeError: form.submit is not a function

### ISSUE THREAD

**Issue by mirao** [facebook/php-webdriver#402]
### What are you trying to achieve? (Expected behavior)
Submit passes

### What do you get instead? (Actual behavior)
Submit passes, but test fails

```
[22-Jan-2017 22:04:00 Europe/Berlin] PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnexpectedJavascriptException: TypeError: form.submit is not a function
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'mira-HP-ENVY-Notebook', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.8.0-34-generic', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, firefoxOptions={args=[], profile=UEsDBBQACAgIAHqwNkoAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WTW/bMAy971cMOW3AIvRju2ynruuAAcU6LCh2FGSJttXIkqaPuPn3o2S7SRPHbndKbJMS+fj4yOjBUeugfLconGnxiXhWQv4vdUUaplrmgIBmhQKx+PC2ZMrD+y9v4s5TsIA21riQXGpgKtTdM0GjjeQz/hpCa9ya1CFYYmvp6+0yfbbM+6UCXYUaHS8+fXruNgTsgAn8ERCABxDfpfPhCmPhCtAtuHgYrmkwr0fKa2caoJ47aQN1UdMgm+RyeTZ+UWCFJwiHvtPXyngYz2awFqbVyjCBd2lWJWBr0/6pQa8QrYTUuLvFoGzw6TLaGMHUDPawCcYoT8A547jR3qh9uI/T97LSRiNqDTQFuFV+9OOn99Ba5jwsjV7mfCbjeWIReC/x3GCQPQ58RKRLTI1yx3w97aukXhNjQVN4DOA0U6n8r+ZcmYjwO+rxy1oohJMbfGacAxIgasTKI4EoB in /home/mira/workspace/selenium/vendor/facebook/webdriver/lib/Exception/WebDriverException.php on line 122

```
More likely because the input element on that page has id="submit", see [this post](http://manicode.blogspot.cz/2009/04/form-input-names-with-reserved-words.html).

I used click() instead, it works for me:
```// Search 'php' in the search box
$input = $driver->findElement(
    WebDriverBy::id('q')
);
$input->sendKeys('php');

# find submit
$submit = $driver->findElement(
    WebDriverBy::id("submit")
);
# and click
$submit->click();
```

### How could the issue be reproduced? (Steps to reproduce)
- Run the test example.php (`$ php -f example.php`)
- Watch the command `$input->sendKeys('php')->submit();`

### Details

* Php-webdriver version: 1.3
* PHP version: 7.0.13
* Selenium server version: 3.0.1
* Operating system: Ubuntu 16.10
* Browser used + version: Firefox 50.1

**Comment by OndraM** [comment]
@mirao Thanks for the report! It appears to be a problem with Selenium itself. I reported it directly to the Selenium project, see https://github.com/SeleniumHQ/selenium/issues/3398. 

So lets wait what they will think about it.

**Comment by mirao** [comment]
Thank you very much for reporting. I can confirm that it works well in Chrome.

**Comment by OndraM** [comment]
I updated the example to do click instead of submit, until the Selenium bug is fixed (I pushed a PR there, see https://github.com/SeleniumHQ/selenium/pull/3668 ).
