### ISSUE TITLE
Can't find checkbox

### ISSUE THREAD

**Issue by grikis** [facebook/php-webdriver#403]
I want to check a checkbox but webdriver can't find it and throws this error:
Facebook\WebDriver\Exception\NoSuchElementException: no such element: Unable to locate element: {"method":"id","selector":"cbox1"}

Code I'm using:
```
    public function testTest()
    {
        $this->driver->get('https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox');
        $this->driver->findElement(WebDriverBy::id('cbox1'));
    }
```

* PHP version: 7
* Selenium server version: 2.53.1
* Operating system: Windows
* Browser used + version: Chrome v55

**Comment by gabrielpreston** [comment]
This is because those are inside of iframes. You need to switch window handles to be inside of the iframe before you can find that element.
