### ISSUE TITLE
How to get page code to see the browser!?

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#407]
I apologize in advance if this question has already sounded
How to get page code to see the browser!?
I need to get the code page as string - Ko is the one who sees in the browser after the page is loaded with all iframe

**Comment by OndraM** [comment]
You are probably looking for method `getPageSource()` - see https://facebook.github.io/php-webdriver/latest/Facebook/WebDriver/WebDriver.html#method_getPageSource. It returns current page source as seen by the browser.
