### ISSUE TITLE
Tell me how to cut page load time over time!?

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#409]
I have some tests the page loads very long, and because of this the browser is not closed, tell me how to do that would be if the page was not loaded for 40 seconds selenium just closed the browser and everything? not issued error message...

**Comment by OndraM** [comment]
@StasToken Hi, you may be looking for `-browserTimeout` and `-timeout` options of Selenium server... Also consult the explicit wait here: https://github.com/facebook/php-webdriver/wiki/HowTo-Wait

Without error message or example code I cannot help you more, sorry...

**Comment by StasToken** [comment]
I will try to explain in more detail
I tell my browser to the page 
`$driver = RemoteWebDriver::create($host, $capabilities, 5000,120000);
$driver->get('http://'.$dat['domain'].'');`
okay... the problem is that the page sometimes loads very very slowly; and when the waiting time passes my test falls into a fatal error... And the browser at this time remains open and kept looking to expend resources PC 
My question actually is what would have prevented it.
If the browser couldn't get the page ( it was not until the end of the loaded ) then just execute 
`$driver->quit();` What would the browser has been closed...
PS: I have testers on the server create per day 20 - 30 is not closed browsers it is not convenient because the server starts to slow down and you have to solve this problem in the manual... I would be very grateful if someone tell me how to deal with it

**Comment by OndraM** [comment]
Hi, as I wrote, you should utilize the `-browserTimeout` and `-timeout` options of the selenium server jar. This setting should force close of the inactive browsers. See help:

```
  -timeout <nnnn>: an integer number of seconds we should allow a
    client to be idle
  -browserTimeout <nnnn>: an integer number of seconds a browser is
    allowed to hang
```

**Comment by StasToken** [comment]
Thank you very much for your help. Nice test!
