### ISSUE TITLE
Render a HTML String or local html file

### ISSUE THREAD

**Issue by llmuculusll** [facebook/php-webdriver#414]
### What are you trying to achieve? (Expected behavior)
I want to render a local HTML file by webdriver.
For example:
 ```php
$host = 'http://phantomjs:8910/wd/hub'; // webdriver server is on another host
$driver = RemoteWebDriver::create($this->host, DesiredCapabilities::phantomjs());
$driver->get('file:///tmp/test.html'); 
```

It is great that if I could render HTML string:

```php
$text = <<<EOT
<html><head><title>Test HTML</title></head><body><div>TEST BODY</div></body></html>
EOT;
$driver = RemoteWebDriver::create($this->host, DesiredCapabilities::phantomjs());
$driver->getHTML($text);    
```

### What do you get instead? (Actual behavior)
But it can not load the local file.
There no function to pass it HTML String.
I don't find any solution in facebook/php-webdriver.

* Php-webdriver version: ^1.3
* PHP version: 5.6
* Selenium server version: Docker image of wernight/phantomjs:2.1.1
* Operating system: Debian

**Comment by OndraM** [comment]
Hi, but the
```$driver->get('file:///tmp/test.html');``` is working, or not? Or is there any issue whit this?

As far as I know this is the only way how to render custom html - through a custom page. (Or you can implement some custom script and pass it the HTML through GET or POST, but I would not recommend this).

**Comment by llmuculusll** [comment]
Hi,
No it doesn't work.
maybe because /tmp/test.html is in script host and selenium is on another host.

**Comment by OndraM** [comment]
Oh, sure, the file must be accessible on this URL from the system where the browser (in this example phantom js) is started.

I would suggest starting PHP server using
```php -S localhost:8000 -t ./directoryWithTheFile/```

which will make the file accessible on url `http://localhost:8000/test.html`. As you run the phantom inside docker container, you will also need to properly set this up - see eg. https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach.
