### ISSUE TITLE
selenium tests not working with phpunit laravel.

### ISSUE THREAD

**Issue by Aqeel222** [facebook/php-webdriver#415]
### every time i got this output.
i am new in selenium though i worked with phpunit before.
![2017-02-13_2015](https://cloud.githubusercontent.com/assets/17747266/22891190/5e544a52-f230-11e6-9394-2f824c4bde63.png)
![2017-02-13_2029](https://cloud.githubusercontent.com/assets/17747266/22891191/5e554092-f230-11e6-9830-0956b2483e22.png)
![2017-02-13_2106](https://cloud.githubusercontent.com/assets/17747266/22891192/5e982f38-f230-11e6-895b-7efc1d1b69e8.png)
![2017-02-13_2107](https://cloud.githubusercontent.com/assets/17747266/22891235/823d6fb6-f230-11e6-9cf5-cf1aff1ac409.png)
![2017-02-13_2109](https://cloud.githubusercontent.com/assets/17747266/22891310/c0b28150-f230-11e6-97bc-cc32b297d310.png)

* Php-webdriver version: 
* PHP version: 7.0.6
* Selenium server version: 3.0.1
* Operating system:  windows 8.1
* Browser used + version: chrome + 56.0.2924.87

**Comment by OndraM** [comment]
Hi,
first of all - you appear to be using Selenium2TestCase from https://github.com/giorgiosironi/phpunit-selenium - which is different project, unrelated to this library. So please point any question relating this library there.

Also note the phpunit-selenium library appear to not be maintained anymore. I would suggest using different tools to integrate Selenium WebDriver into PHPUnit, like [Steward](https://github.com/lmc-eu/steward) or [Codeception](http://codeception.com).

Good luck!
