### ISSUE TITLE
example.php not working with selenium-server-standalone-3.0.1.jar

### ISSUE THREAD

**Issue by Eddcapone** [facebook/php-webdriver#416]
If I run example.php by navigating to this url:  http://localhost/selenium_standalone/example.php then I get this error:

> Fatal error: Uncaught Facebook\WebDriver\Exception\UnknownServerException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases in C:\xampp\htdocs\selenium_standalone\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:114 Stack trace: #0 C:\xampp\htdocs\selenium_standalone\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(321): Facebook\WebDriver\Exception\WebDriverException::throwException(13, 'The path to the...', Array) #1 C:\xampp\htdocs\selenium_standalone\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(121): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand)) #2 C:\xampp\htdocs\selenium_standalone\example.php(17): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), in C:\xampp\htdocs\selenium_standalone\vendor\facebook\webdriver\lib\Exception\WebDriverException.php on line 114

**Comment by OndraM** [comment]
Hi @Eddcapone, thanks for the report, but I have to close the issue, sorry - if you still experience the problem, please fill the issue template which is provided when creating a new issue - it helps us diagnose you issue and help you :). 

Thank you!

**Comment by Eddcapone** [comment]
I was able to solve it by installing gecko and passing gecko to the webserver as parameter

**Comment by itsDiwaker** [comment]
@Eddcapone Could you please elaborate more on what you mean by passing to the webserver as parameter?

**Comment by OndraM** [comment]
You can pass the geckodriver binary path to the Selenium server like this:
`java -Dwebdriver.gecko.driver="/usr/bin/geckodriver" -jar selenium-server-standalone-3.3.1.jar`
