### ISSUE TITLE
Screenshot filename

### ISSUE THREAD

**Issue by ashishkhanna** [facebook/php-webdriver#417]
### What are you trying to achieve? (Expected behavior)
Screenshot should save

### What do you get instead? (Actual behavior)
screenshot not saving as auto generated  filename length is greater than 255 characters

### How could the issue be reproduced? (Steps to reproduce)
any test case failed application will try to take screenshot

```php
// You can insert your PHP code here (or remove this block if it is not relevant for the issue).
```

### Details

* Php-webdriver version: 
* PHP version: 
* Selenium server version: 
* Operating system: 
* Browser used + version:

**Comment by OndraM** [comment]
@ashishkhanna Hi, could you please provide code you use to take the screenshot?

Because there is no auto generated filename from php-webdriver.
