### ISSUE TITLE
executeScript - inject prompt and return value

### ISSUE THREAD

**Issue by Eddcapone** [facebook/php-webdriver#418]
### What are you trying to achieve? (Expected behavior)
execute a javascript prompt and get the return value for later use in PHP.

### What do you get instead? (Actual behavior)
After the prompt is rendered, I get `UnknownServerException in WebDriverException.php line 114:
Failed to find value field
Build info: version: '3.0.1', revision: '1969d75...'`

### How could the issue be reproduced? (Steps to reproduce)

Normally I run this on a private site, for this example I changed it to the github page and try to enter the SMS code into the username field instead of my SMS field.

1. Run Selenium Server 3.0.1
2. Run this script

```php
...
<?php
namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\WebDriverBy;

require("vendor/autoload.php");

$driver = RemoteWebDriver::create('http://localhost:4444/wd/hub', DesiredCapabilities::firefox(), 5000);
$driver->get('https://github.com/login');

$usernameInput = $driver->findElement(WebDriverBy::id('login_field'));
$passwordInput = $driver->findElement(WebDriverBy::id('password'));

$smsCode = $driver->executeScript("return prompt('Please enter the SMS verification code.', '');");
									
$usernameInput->sendKeys($smsCode);
$passwordInput->sendKeys('1234')->submit();
?>
```
Stackoverflow: http://stackoverflow.com/questions/42268912/unknownserverexception-failed-to-find-value-field

### Details

Maybe It is also relevant to tell that I am using it in laravel 5.3.

* Php-webdriver version: 1.3.0
* PHP version: 7.0.6
* Selenium server version: 3.0.1
* Operating system: Windows 7 64 Bit Professional
* Browser used + version: Firefox 51.0.1 32 Bit

**Comment by OndraM** [comment]
Hi,
I replied on stackowerflow: http://stackoverflow.com/a/42269808/464890

See also https://github.com/mozilla/geckodriver/issues/431 .
