### ISSUE TITLE
Invalid argument supplied for foreach() in WebDriverKeys

### ISSUE THREAD

**Issue by Eddcapone** [facebook/php-webdriver#419]
### What are you trying to achieve? (Expected behavior)
Execute a javascript prompt and get the return value for later use in PHP.
**NOTE**: I already opened the same issue for firefox geckodriver, now I tested it by using chromedriver.

### What do you get instead? (Actual behavior)
After the prompt is rendered, I get `Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\teschd\vendor\facebook\webdriver\lib\WebDriverKeys.php on line 105`

### How could the issue be reproduced? (Steps to reproduce)

Normally I run this on a private site, for this example I changed it to the github page and try to enter the SMS code into the username field instead of my SMS field.

1. Run Selenium Server 3.0.1
2. Run this script

```php
<?php
namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\WebDriverBy;

require("vendor/autoload.php");

$driver = RemoteWebDriver::create('http://localhost:4444/wd/hub', DesiredCapabilities::chrome(), 5000);
$driver->get('https://github.com/login');

$usernameInput = $driver->findElement(WebDriverBy::id('login_field'));
$passwordInput = $driver->findElement(WebDriverBy::id('password'));

$smsCode = $driver->executeScript("return prompt('Please enter the SMS verification code.', '');");
									
$usernameInput->sendKeys($smsCode);
$passwordInput->sendKeys('1234')->submit();
?>
```
Stackoverflow: http://stackoverflow.com/questions/42268912/unknownserverexception-failed-to-find-value-field

### Details

Maybe It is also relevant to tell that I am using it in laravel 5.4.

* Php-webdriver version: 1.3.0
* PHP version: 7.0.6
* Selenium server version: 3.0.1
* Operating system: Windows 7 64 Bit Professional
* Browser used + version: Chrome 56.0.2924.87

**Comment by OndraM** [comment]
@Eddcapone I replied on SO. But I will keep this issue open, as there appears to be some issue with the encode method of WebDriverKeys - I will investigate it later.

**Comment by Eddcapone** [comment]
@OndraM yes it seems like you need to wrap the foreach with `if (is_array($keys)) { ... }`
