### ISSUE TITLE
Not works with .dev local domains

### ISSUE THREAD

**Issue by akalongman** [facebook/php-webdriver#421]
### What are you trying to achieve? (Expected behavior)
Open http://mylocaldomain.dev

### What do you get instead? (Actual behavior)
Error 
![failure-testbasicexample-0](https://cloud.githubusercontent.com/assets/423050/23255518/5bc67f1a-f9d5-11e6-9c72-64fed1dd166b.png)

### Details

* Php-webdriver version: Latest
* PHP version: 7.0
* Selenium server version: 
* Operating system: Ubuntu
* Browser used + version:

**Comment by OndraM** [comment]
@akalongman Hi, this is not a problem of php-webdriver - it seems the .dev domain is being registered as a new top level domain, thus you cannot use it for local domains. Try different one, like `.local`.

See also https://superuser.com/questions/919278/err-icann-name-collision-when-trying-to-use-localhost-dev-in-chrome for more information.

**Comment by edno** [comment]
It can be also achieved by changing the '/etc/host' file on your workstation.
