### ISSUE TITLE
The issue with cross domain cookies

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#423]
Hi, all good testing time!
I had such a question, I need to get all cookies from a specific domain from a profile Firefox 
The essence of my problem is that:
1) getCookies() - shows all the cookies BUT! it shows you cookies, only those who have established the current domain ( and I need to get cookies from another domain )
2) getCookieNamed - as in the first case, trying to find the cookie for the current domain....
It is possible that I overlooked in the documentation... please tell me how to get cookies for specific domain in this session?
## An example of my actions:
I) I'm trying to get the page example.com
II) Upon receipt of the page there is a lot of queries on domain example2.com ( There is the inclusion of all the JS etc. ) This time domain example2.com adds your cookies in the browser
III) Process system testing completed.
So... I need to get all the cookies installed example2.com
How to do it!?

### Technical information
Selenium server 2.53.1
OS: Ubuntu Linux 
Firefox: 47.0.1

_PS: I apologize in advance if this question has already been asked or I asked it not there, I tried to search on this topic and read the source codes but I do not what gave... I would be very grateful if anyone tell me whether what should I do in this situation._

**Comment by OndraM** [comment]
You - be design - can only read cookies from the context of the page the browser is currently displaying. 

If you need to read cookies from example2.com, you have to be on some page on this domain - there is AFAIK no way hot to work around this.

However, you can use selenium to go to some page on example2.com, like `example2.com/not-existing-page`, which will probably show you some 404 error page, however, you can now read cookies from this domain.

**Comment by StasToken** [comment]
Damn bad - I have also thought about this method you suggested but was hoping I wouldn't have to resort to such a method "analiticheskom"...
In any case, thanks for answering, now at least I know exactly what you can't do that.
**The question can be closed**
