### ISSUE TITLE
Is it possible to import dump cookies?

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#426]
Hello, Implementations in different languages such as Python seen function that allows you to upload the dump of the cookies in the browser, is it possible now to do it in php-webdriver, if not will there be such a possibility in the future?

**Comment by OndraM** [comment]
Hi, could you please explain the use-case for this?

**Comment by StasToken** [comment]
Hello OndraM, - I came across an article: [How to save and load cookies using python selenium webdriver](http://stackoverflow.com/questions/15058462/how-to-save-and-load-cookies-using-python-selenium-webdriver) In General is to create a dam cookie and import it into the browser is a good idea if we have tests tied to the massive use of cookies this will avoid unnecessary movements when writing the test, and besides, now you cannot set cookies for a domain without going in to it.... importing dump allows you to bypass this restriction? or am I wrong? I'm basically just wondering whether it is planned that any lists you like php-webdriver

**Comment by OndraM** [comment]
None of the solutions (even the linked one in Python) will allow you to set cookie for different domain. This is intentional feature of Selenium WebDriver protocol (I guess this is also security measure of the browser). You cannot bypass this using Selenium.

**Comment by StasToken** [comment]
The screwed to be honest... Why would the developers make Selen driver for your browser specially if its castrated functionality....? - maybe I don't understand it but I think it's strange....

**Comment by StasToken** [comment]
About the installation of cookies on other domains is a separate issue, there is still the question is about the import-export cookies - how it is relevant to the question what do you think?

**Comment by OndraM** [comment]
@StasToken This is IMHO intentional security feature. 

About the import-export: no, this is currently not planned. I personally didn't find a use-case. But feel free to contribute by sending a PR. 

But I think you can simply implement it by yourselves even without the any generic export & import: just save the cookie you are interested in and set it afterwards in the next browser instance.

**Comment by StasToken** [comment]
about my contribution - you may be right I wonder if it's not who will do the deal with his base and perhaps add this feature to you php-webdriver - This is not the most relevant issue for today but still the functionality we need to expand slowly :-)

**Comment by shdehnavi** [comment]
I want to save cookies in a file, before saving i should convert all cookies in json format, but GetCookies() method give cookies in object and array format and cookies defined as protected and cannot convert to json, it shoud serialize 
What i can ?
