### ISSUE TITLE
How to check that Xpath was found?

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#428]
_Hello everyone, I apologize in advance I'm probably going to ask a stupid question... but I honestly sat there all day with var_dump did not understand how to odontolith the following..._
**Actually a question**
I'm trying to find the element using the design: `$driver->findElement(WebDriverBy::xpath('/html/body/a'));` How do I check that this element was found? there after will not be refunded _true_ or _false_ Do I just need to handle this condition on the similarity of design _if_ "If the Xpath has been found to do something if not do it" - **Tell me how to know the status whether the element is found?**

**Comment by OndraM** [comment]
Hi,
if elements is not found, an `NoSuchElementException` is thrown (when using `findElement` method). If you use `findElements()` method, it will return an empty array if none element matches given locator.

See newly created page on the [wiki](https://github.com/facebook/php-webdriver/wiki/Finding-an-element).

**Comment by StasToken** [comment]
No! - I for some reason when element not found immediately drops test and I do not have time to handle the exception 
use: `$driver->findElement(WebDriverBy::xpath('/html/body/a'));`
And after I run this code

> PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"/html/body/a"}
I don't have time like that to process the result of which he returned please tell me how to be?

**Comment by gabrielpreston** [comment]
You need to put that in a try/catch block.

**Comment by StasToken** [comment]
Sorry - but I don't understand is how?

**Comment by OndraM** [comment]
If `findElement()` method does not find an element with given locator (xpath/css etc.), it throws NoSuchElementException. 

Exception handling is PHP basics, please refer to PHP  manual or many resources on the internet, like https://www.w3schools.com/php/php_exception.asp

**Comment by StasToken** [comment]
And all understand - I have to be honest out of my head all flew out so that php knows how... 
Once again I apologize....

**Comment by OndraM** [comment]
No problem, that is great to hear! :)
