### ISSUE TITLE
Tell me is it possible to save the current user profile or upload it?

### ISSUE THREAD

**Issue by StasToken** [facebook/php-webdriver#429]
The actual survey in the hat, interested in how to save/load the current user profile of Firefox with all the settings?

**Comment by StasToken** [comment]
```
$caps = DesiredCapabilities::firefox();
$caps->setCapability(FirefoxDriver::PROFILE, $profile);
$driver = RemoteWebDriver::create($url, $caps);
```
That should contain the variable $profile and $url

**Comment by cprn** [comment]
I don't get what are you asking for. You create a profile locally:

        $capabilities = DesiredCapabilities::firefox();
        $profile = new FirefoxProfile();
        $profile->setPreference('browser.download.folderList', 2);
        $profile->setPreference('browser.download.dir', '/tmp/downloads');                
        $capabilities->setCapability(FirefoxDriver::PROFILE, $profile);

Code that zips and sends the profile to the remote is in:
`facebook/webdriver/lib/Firefox/FirefoxProfile.php: FirefoxProfile->encode()`
