### ISSUE TITLE
No Report

### ISSUE THREAD

**Issue by Eddcapone** [facebook/php-webdriver#431]
### What are you trying to achieve? (Expected behavior)
Show test report just like in PHP Unit

### What do you get instead? (Actual behavior)
No test report at all. I had to create a workaround.

### How could the issue be reproduced? (Steps to reproduce)
Run a random test, there will be no report at the end.

### Details

* Php-webdriver version: 1.3.0
* PHP version: 7.0.15
* Selenium server version: 3.3.1
* Operating system: Linux 745QG12 4.8.0-41-generic #44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Browser used + version: Firefox, 52.0

**Comment by OndraM** [comment]
@Eddcapone Hi, thanks for the report, but you didn't provide much information how to reproduce the issue.

What is the exact code you ar running?
What is the command you use to start the tests?

Also note php-webdriver library itself does not contain any PHPUnit integration, so this may be completely unrelated issue.

**Comment by ussher** [comment]
@Eddcapone I found this useful getting started: https://www.youtube.com/watch?v=MZ4laramYNs

Behat runs the tests and provides the test pass/fail feedback.

**Comment by cryptton2004** [comment]
I've been using Allure for generating HTML reports. If it's of any help: http://allure.qatools.ru/

**Comment by Eddcapone** [comment]
Thank you all, I wrote my own report system. But it is not very clean, since you have to maintain it and add all available methods. I will throw a look at your suggested software.
