### ISSUE TITLE
Profile has been set on both the capabilities and these options but they're different. Unable to determine which one you want to use?

### ISSUE THREAD

**Issue by hiyucheng** [facebook/php-webdriver#432]
```php
$host = 'http://localhost:4444/wd/hub';
$profile = new FirefoxProfile();
$profile->setPreference('log', "{level: info}");
        
$caps = DesiredCapabilities::firefox();
$caps->setCapability(FirefoxDriver::PROFILE, $profile);
        
$driver = RemoteWebDriver::create($host, $caps, 500000, 500000);
```

### Details

* Php-webdriver version: 
* PHP version: 5.5
* Selenium server version: 3.3
* Operating system: win7
* Browser used + version: firefox 52
* geckodriver version:0.15

**Comment by OndraM** [comment]
@hiyucheng Sorry, I don't understand what is to problem...

But if you still face one, please don't hesitate to open new issue (but please use the prepared template for bug report - it helps us to dig into your problem). Thanks!

**Comment by OndraM** [comment]
See also #434.

**Comment by OndraM** [comment]
Looks like an Selenium server issue, you should use Selenium version 3.3.1. 
https://github.com/SeleniumHQ/selenium/issues/3632
