### ISSUE TITLE
wrong behaviour when getting title of page with Persian characters

### ISSUE THREAD

**Issue by ooghry** [facebook/php-webdriver#433]
### What are you trying to achieve? (Expected behavior)
get page title with Persian characters.

### What do you get instead? (Actual behavior)
alien characters.

```php
$host = 'http://localhost:4444/wd/hub'; 
$capabilities = DesiredCapabilities::firefox();
$driver = RemoteWebDriver::create($host, $capabilities, 5000);
$driver->get('https://fa-ir.facebook.com');
$driver->wait()->until(
    WebDriverExpectedCondition::titleContains('فیس‌بوک')
);
echo "The title is '" . $driver->getTitle() . "'\n";
```

### Details

* Php-webdriver version: ^1.4
* PHP version: 7.0.8
* Selenium server version: 3.3.1
* Operating system: win 10
* Browser used + version: FF 52.0.2
* geckodriver: 0.15.0

**Comment by OndraM** [comment]
@ooghry Hi, and what exactly is the error/output you get?

If I use you example (but change `titleContains('فیس‌بوک')` to `titleContains('سیستم')`, because the actual title of the page doesn't contain this sequence, it works for me.

> The title is 'به فیس بوک خوش آمدید - به سیستم وارد شوید، نامنویسی کنید یا اطلاعات بیشتری دریافت کنید'

Also on Firefox 52 + latest Geckodriver.

**Comment by ooghry** [comment]
Hi OndraM
you right, selenium and php-webdriver work perfectly with utf-8 characters.

my main problem is I want click on css/js menu Persian item and it didn't work then I try get title of that page(facebook is example) and win 10 command line doesn't show Persian character and I think selenium server can't send utf-8 characters.

By the way,sorry about wrong report and thank you for your time.

**Comment by OndraM** [comment]
No problem at all! :-)
