### ISSUE TITLE
issue with firefox profile

### ISSUE THREAD

**Issue by haithem-gribaa** [facebook/php-webdriver#434]
### What are you trying to achieve? (Expected behavior)
lunch firefox driver 

### What do you get instead? (Actual behavior)
exception with message:
Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\UnknownServerException' with message 'Profile has been set on both the capabilities and these options, but they're different. Unable to determine which one you want to use.

### How could the issue be reproduced? (Steps to reproduce)
$profile = new FirefoxProfile();
$profile->setPreference(
  'browser.startup.homepage',
  'https://github.com/facebook/php-webdriver/'
);
$caps = DesiredCapabilities::firefox();
$caps->setCapability(FirefoxDriver::PROFILE, $profile);

$driver = RemoteWebDriver::create($url, $caps);

### Details

* Php-webdriver version: lasted
* PHP version: 5.6.30
* Selenium server version: 3.3
* Operating system: windows 7
* Browser used + version: firefox 52

**Comment by OndraM** [comment]
This looks like an Selenium server issue, which should be resolved in Selenium server version *3.3.1* - see https://github.com/SeleniumHQ/selenium/issues/3632. Could you please try this Selenium version?

**Comment by haithem-gribaa** [comment]
thank you i moved to 3.3.1 and problem is solved

**Comment by OndraM** [comment]
Great to hear!
