### ISSUE TITLE
[Facebook\WebDriver\Exception\UnknownCommandException] mouseMoveTo

### ISSUE THREAD

**Issue by bscheshirwork** [facebook/php-webdriver#435]
### What are you trying to achieve? (Expected behavior)
mouse move

### What do you get instead? (Actual behavior)
[Facebook\WebDriver\Exception\UnknownCommandException] mouseMoveTo
### How could the issue be reproduced? (Steps to reproduce)
https://github.com/Codeception/Codeception/issues/4104

### Details

* Php-webdriver version: 1.4
* PHP version: 7.1.3
* Selenium server version: selenium/firefox-standalone:3.3.0
* Operating system: debian
https://github.com/bscheshirwork/docker-yii2-app-advanced-rbac/tree/master/docker-codeception-run
* Browser used + version:

**Comment by OndraM** [comment]
Please try using Selenium 3.3.1, as the 3.3.0 version won't work properly with latest Firefox/Geckodriver.
See https://github.com/mozilla/geckodriver/pull/593

**Comment by kschroeder** [comment]
I'm having this issue, too.  

Facebook\WebDriver\Exception\UnknownCommandException: mouseMoveTo
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'dev', ip: '127.0.53.53', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.6.1.el7.x86_64', java.version: '1.8.0_121'

**Comment by llangen** [comment]
Same issue here but with Selenium server 3.4.0
