### ISSUE TITLE
Sending keyboard shortcuts not working.

### ISSUE THREAD

**Issue by Legenzoo** [facebook/php-webdriver#437]
### What are you trying to achieve? (Expected behavior)
Sending keyboard shortcuts like (CMD + t for a new tab, or CMD + a to select all).
**CMD + t and CMD + w especially important to me, to handle browser windows/tabs.**

### What do you get instead? (Actual behavior)
Nothing happening.

### How could the issue be reproduced? (Steps to reproduce)

```php
        $driver = RemoteWebDriver::create('http://localhost:4444/wd/hub', array(
                WebDriverCapabilityType::BROWSER_NAME => 'firefox'
        ));
        $driver->get('http://google.com');
        $input = $driver->findElement(WebDriverBy::id('lst-ib'));
        $input->click();
        $input->sendKeys('some text'); // text is inputted.

        $input->sendKeys(array(
            WebDriverKeys::COMMAND,
            'a',
        )); // nothing happening
```
Text is not marked. Opening a new tab with CMD + t also not working. 
The same for browser chrome.

### Details

* Php-webdriver version: 1.4
* PHP version: 7.1.1
* Selenium server version: Selenium build info: version: '3.3.1', revision: '5234b32'
* Operating system: macOS Sierra 0.12.4 (16E195)
* Browser used + version: Firefox 50.1, Chrome 57

**Comment by OndraM** [comment]
This works for me on Linux (with `WebDriverKeys::CONTROL` used instead of the `WebDriverKeys::COMMAND`). 

So maybe someone with Mac can help/try?

**Comment by felippebueno** [comment]
I'm having the same problem on MAC OS :(

**Comment by cprn** [comment]
This bug is present for several years now. Last time I heard about it people used mouse context menu instead, e.g. `contextClick($element).sendKeys('a')` does "Select All" operation.

**Comment by felippebueno** [comment]
Understanding, however I need to use CMD + C, CMD + V and CMD + T ...

**Comment by cprn** [comment]
See the [issue in Chromium](https://bugs.chromium.org/p/chromedriver/issues/detail?id=30) - it can't be fixed in facebook/php-webdriver. Quoting workarounds for future readers:

> control+delete or control+k to cut
> control+insert to copy
> shift+insert or control+y to paste
> javascript(window.open()) to open new tab

**Comment by felippebueno** [comment]
Thanks I'll try

**Comment by andrisi** [comment]
`$fileNameControl->sendKeys(WebDriverKeys::CONTROL . 'v');` works for me
