### ISSUE TITLE
Exception from ChromeDriver::start() "Constant CURLOPT_CONNECTTIMEOUT_MS already defined"

### ISSUE THREAD

**Issue by bluerelay** [facebook/php-webdriver#442]
### What are you trying to achieve? (Expected behavior)

I tested ChromeDriver class with following code,
`ChromeDriver::start($capabilities);`

### What do you get instead? (Actual behavior)

I got the following exception,
`Constant CURLOPT_CONNECTTIMEOUT_MS already defined`

### How could the issue be reproduced? (Steps to reproduce)

I think it was caused by Facebook\WebDriver\Net\URLChecker::GetHTTPResponseCode($url)
```php
if (!defined(CURLOPT_CONNECTTIMEOUT_MS)) {
            define('CURLOPT_CONNECTTIMEOUT_MS', 156);  // default value for CURLOPT_CONNECTTIMEOUT_MS
}

// the code should be. note the missing quotes ''
if (!defined('CURLOPT_CONNECTTIMEOUT_MS')) {
            define('CURLOPT_CONNECTTIMEOUT_MS', 156);  // default value for CURLOPT_CONNECTTIMEOUT_MS
}
```

### Details

* Php-webdriver version: 1.4
* PHP version: 7.0
* Selenium server version: 
* Operating system: Ubuntu 16.04 LTS
* Browser used + version: google-chrome beta 59

**Comment by OndraM** [comment]
@bluerelay Hi, this should be fixed in php-webdriver 1.4.1, see https://github.com/facebook/php-webdriver/pull/438.
