### ISSUE TITLE
when use DesiredCapabilities::htmlUnit() show error "PluginDefaultReplyText" is not defined

### ISSUE THREAD

**Issue by dream798** [facebook/php-webdriver#443]
### What are you trying to achieve? (Expected behavior)
when using DesiredCapabilities::htmlUnit()  and run get("http://xxxxx.com") ,some website is ok，but some website ,it show error like"ReferenceError: "PluginDefaultReplyText" is not defined"

### What do you get instead? (Actual behavior)
ERROR: Facebook\WebDriver\Exception\UnknownServerException: ReferenceError: "PluginDefaultReplyText" is not defined

i don't put my code here，because i try to find the reason in source code,and i find the class file "UnknownServerException" , i find it is empty ,so i think maybe it didn't develop complete?

* Php-webdriver version: 1.4
* PHP version: 7.1
* Selenium server version: 3.4.0
* Operating system: ubuntu 14.04.2 LTS
* Browser used + version: htmlUnit

**Comment by OndraM** [comment]
Hi, this is hard to say, but my guess is something specific to either the website or some HtmlUnit bug.

I think best would be to provide:
a) URL of the webpages which causes the problem
b) the PHP code you use to visit them
c) full error output of the exceptions

Thanks :)
