### ISSUE TITLE
browserName=null while creating the driver, but the right value is printed

### ISSUE THREAD

**Issue by Joel-Costamagna** [facebook/php-webdriver#444]
### What are you trying to achieve? (Expected behavior)

I lauch the test on selenium grid using a phpunit task in Bamboo CI server.
It should open the webpage, pass the test and show the results in bamboo.

### What do you get instead? (Actual behavior)

I see internet explorer and firefox opening, I see the test running, and when the test is finished, the browser close without apparent problems, but  the test fails and it shows an error :

`PHPUnit_Extensions_Selenium2TestCase_WebDriverException: The best matching driver provider org.openqa.selenium.safari.SafariDriver can't create a new driver instance for Capabilities [{browserName=null, platform=MAC, firefox_profile=....`

### How could the issue be reproduced? (Steps to reproduce)

```php
public function setUp()
    {
        $this->setHost('localhost');
        $this->setPort(4444);
        $this->setBrowserUrl('http://www.google.com');

        switch (getenv("browser")) {
			case 'firefox' :
				$this->webDriver =
					 RemoteWebDriver::create("localhost:4444/wd/hub", DesiredCapabilities::firefox()->setPlatform("MAC"));
				break;
			case 'chrome':
				$this->webDriver =
					 RemoteWebDriver::create("localhost:4444/wd/hub", DesiredCapabilities::chrome()->setPlatform("MAC"));
				break;
			case 'ie':
				$this->webDriver = RemoteWebDriver::create("localhost:4444/wd/hub",
					 DesiredCapabilities::internetExplorer()->setPlatform("WINDOWS"));
				break;
			case 'edge':
				$this->webDriver = RemoteWebDriver::create("localhost:4444/wd/hub",
					 DesiredCapabilities::microsoftEdge()->setPlatform("WINDOWS"));
				break;
			case 'safari':
				$this->webDriver = RemoteWebDriver::create("localhost:4444/wd/hub",
					 DesiredCapabilities::safari());
				break;
			default:
				error_log("erreur: entrez un nom valide de navigateur \n");
				exit(4);
		}
//this shows the right value.		
error_log(print_r("browserName = " . $this->webDriver->getCapabilities()->getBrowserName(), true));
	}
        public function testTitre()
	{
                //this is where it fails 
		$this->webDriver->get('https://github.com');
                //this is never shown
		error_log($this->webDriver->getCurrentURL());
		$this->assertContains('GitHub', $this->webDriver->getTitle());
	}

	public function tearDown()
	{
		$this->webDriver->quit();
	}
    }

```
### Details

PHPUnit 5.7.20
OS: macOS for the hub and Windows 10 for a node.
Selenium Version: 2.52
Browser: IE & firefox
Browser Version: latest

**Comment by Joel-Costamagna** [comment]
ok, so apparently the problem was I was extending`PHPUnit_Extensions_Selenium2TestCase` instead of `PHPUnit_Framework_TestCase` . I did not understand what the problem was though.

her

**Comment by OndraM** [comment]
Yes, Selenium2TestCase is part of legacy https://github.com/giorgiosironi/phpunit-selenium library, not php-webdriver.
