### ISSUE TITLE
How to set the download location for file downloads?

### ISSUE THREAD

**Issue by petericebear** [facebook/php-webdriver#448]
### What are you trying to achieve? (Expected behavior)
I want to set a download location when a page starts to download a file after following a link.

A page that I am tracking, sends a file to the downloads folder. I do not know the file name at that time.
How can I get the pushed file from its download location and filename?

* Php-webdriver version: Latest
* PHP version: 7.1

**Comment by OndraM** [comment]
@petericebear Hi, the Download dialog is out of Selenium reach and as far as I know, it cannot be reliably controlled.

However, there are some browser-based settings, which may set the browser behavior and the destination folder.

Have a look at https://stackoverflow.com/questions/40654358/how-to-control-the-download-of-files-with-chrome-selenium-and-python - the is about Python bindings, byt you can similarly use https://github.com/facebook/php-webdriver/wiki/ChromeOptions  to pass the configuration options with php-webdriver.
