### ISSUE TITLE
No way to create Page Objects

### ISSUE THREAD

**Issue by josh-palan** [facebook/php-webdriver#454]
### What are you trying to achieve? (Expected behavior)
Create instances of Page Objects similar to [how Behat does it](http://behat-page-object-extension.readthedocs.io/en/stable/guide/introduction.html)

### What do you get instead? (Actual behavior)
No way to create Page Objects

### Details

* Php-webdriver version: 1.4.1
* PHP version: 7.0
* Selenium server version: 3.4
* Operating system: Any
* Browser used + version: Any

**Comment by OndraM** [comment]
@josh-palan Hi, what exactly do you mean? 

Creating page object is plain and simple - it could be a simple PHP class with passed webDriver instance. For example:

```php
class MyPageObject
{
    /** @var RemoteWebDriver */
    private $webDriver;

    public function __construct(RemoteWebDriver $webDriver)
    {
        $this->webDriver = $webDriver;
    }

    public function getPageHeader()
    {
        $this->webDriver->findElement(WebDriverBy::cssSelector('h1.title'));
    }

    public function login($userName)
    {
        $this->webDriver->findElement(WebDriverBy::name(['login']))
            ->sendKeys($userName)
            ->submit();
    }

    ...
}
```

If you want some convenience layer (eg. with prepared abstract page objects, so you don't have to implement this yourselves), you can try some library providing this on top of php-webdriver, like https://github.com/lmc-eu/steward (see [page object example here](https://github.com/lmc-eu/steward-example/blob/master/tests/Pages/TitlePage.php)) or http://codeception.com/docs/06-ReusingTestCode#PageObjects.

Is this what you've been looking for?

**Comment by josh-palan** [comment]
Yes and no. Unfortunately, I've tried quite a few libraries that attempt to provide page objects on top of php-webdriver, but they aren't compatible with the facebook/php-webdriver.

What I was hoping for is a php implementation of [the Selenium page object java class](https://github.com/SeleniumHQ/selenium/wiki/PageObjects), including their implementation of a page factory, so that I could use things like annotations as a way to instantiate the page's properties.

**Comment by josh-palan** [comment]
Are there any updates on this? Any plans on implementing native page objects?

**Comment by OndraM** [comment]
@josh-palan IMO this is out of scope of php-webdriver. Its aim is to provide low layer OOP abstraction over the Selenium protocol(s) and access to features of Selenium. 

Extensions like PHPUnit integration, Page Objects, syntax sugar etc. should be done in other libraries. Checkout some of them (all built on top of php-webdriver):
- https://github.com/lmc-eu/steward 
- https://github.com/Codeception/Codeception 
- https://github.com/laravel/dusk

 to see if some fits your needs or if they provide some built-in Page Objects abstraction (or maybe fill issue there - it may be interesting extension for them). 

Thanks and happy testing :)

**Comment by josh-palan** [comment]
@OndraM I understand wanting to stick to only things that are included in Selenium by default, and just creating abstractions over existing features, however, page objects are a [default feature in Selenium](http://www.seleniumhq.org/docs/06_test_design_considerations.jsp#page-object-design-pattern)
