### ISSUE TITLE
Can't upload file

### ISSUE THREAD

**Issue by thhruu** [facebook/php-webdriver#458]
### What are you trying to achieve? (Expected behavior)
I want to upload the file. 

### What do you get instead? (Actual behavior)
raise  error 

Facebook\WebDriver\Exception\WebDriverException: JSON decoding of remote response failed. Error code: 4 The response: 'Error - incompatible type of argument(s) in call to _uploadFile(); candidates were _uploadFile(QString,QStringList)' in 
~~vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php on line 292

### How could the issue be reproduced? (Steps to reproduce)

```php
<?php

use Facebook\WebDriver as FbDriver;
use Facebook\WebDriver\Remote as FbRemote;
use Facebook\WebDriver\WebDriverBy as FbWebDriverBy;
use Facebook\WebDriver\Remote\WebDriverCapabilityType;
use Facebook\WebDriver\Remote;
class UploadTest{
    function __construct()
    {
        $host = 'http://localhost:8910';
        $caps = FbRemote\DesiredCapabilities::phantomjs();
        $this->driver = FbRemote\RemoteWebDriver::create($host, $caps, 5000);
    }
    function exec(){
        $this->driver->get('http://localhost/upload_test.php');
        $input = $this->driver->findElement(FbWebDriverBy::xpath('//input[@type="file"]'));
        $input->setFileDetector(new Facebook\WebDriver\Remote\LocalFileDetector());

//Error
        $input->sendKeys("/Path/to/file");
    }
}

$uploadtest = new UploadTest();
$uploadtest->exec();

```

I confirmed that there are no problems with chromedriver.

### Details

* Php-webdriver version: 
facebook/webdriver 1.4.1 

* PHP version: 
PHP 5.6.28

* Operating system: 
mac os sierra

* Browser used + version: 
phantomjs 2.1.1

**Comment by OndraM** [comment]
Hi @thhruu , thanks for your report!

It looks like uploading the file through selenium protocol in PhantomJS is broken - see https://github.com/ariya/phantomjs/issues/13302#issuecomment-158628631 . The only "solution" (or workaround) is to no use the LocalFileDetector for PhantomJS (this is done eg. in Codeception: https://github.com/Codeception/Codeception/commit/d45244c20a2ef550fa6e374c82ceada94bff291c#diff-b69c529efcc6368b5c564f8b36665a22R1134), however, this will work only if you run PhantomJS on the same machine as the Selenium tests.

Given PhantomJS is no longer maintained, I doubt this will ever gets fixed there. So I suggest migrating to [headless Chromedriver](https://developers.google.com/web/updates/2017/04/headless-chrome) instead - it works pretty well with latest Chrome 60.
