### ISSUE TITLE
Chromium Command Line Arguments - PDF Viewer

### ISSUE THREAD

**Issue by Keilost** [facebook/php-webdriver#460]
### What are you trying to achieve? (Expected behavior)
 I'am trying to add a argument to not see pdf files, just download it-

### What do you get instead? (Actual behavior)
 I can't find the argument to configure the browser

```php
        $caps = DesiredCapabilities::chrome();
        $options = new ChromeOptions();
        $options->addArguments(array(
            '--disable-pdf-viewer',
        ));
        $caps->setCapability(ChromeOptions::CAPABILITY, $options);
```

### Details

* PHP version: 7
* Operating system: Ubuntu 17.04
* Browser used + version: Chromium 60

**Comment by OndraM** [comment]
Looks like you now need to use the chrome prefs to achieve this, something like:
https://stackoverflow.com/a/43376832/464890
