### ISSUE TITLE
UnknownCommandException mouseMoveTo when calling moveToElement() 

### ISSUE THREAD

**Issue by paulbriton** [facebook/php-webdriver#462]
### What are you trying to achieve? (Expected behavior)
Trigger an hover event by moving mouse to element coordinates.

### What do you get instead? (Actual behavior)
`UnknownCommandException: mouseMoveTo`

### How could the issue be reproduced? (Steps to reproduce)

```php
$capabilities = DesiredCapabilities::firefox();
$driver = RemoteWebDriver::create('http://localhost:4444/wd/hub', $capabilities);

$driver->get("https://www.mozilla.org/en-US/");
$element = $driver->findElement(WebdriverBy::id("nav-button-menu"));
$driver->action()->moveToElement($element)->perform();
```

This looks like an old endpoint from the JsonWireProtocol which has been removed in some drivers (eg. IE and geckodriver). I think actions are the way to go now which I thought it was by calling `action()` method. 
IE and Geckodriver don't support the old APIs, so we'll have to implement w3c protocol in order to use latest versions of Selenium server.
Thank's for your help ;)

### Details

* Php-webdriver version: 1.4.1
* Selenium server version: 3.5.1
* InternetExplorerDriver: 3.5.1
* Geckodriver: 0.17.0
* PHP version: 5.6
* Operating system: Windows 10
* Browser used + version: Firefox 52, 56; IE 11

**Comment by OndraM** [comment]
@paulbriton You are right, the W3C spec contains quite a lot differences. However, the spec is not yet finished, and as this project is completely voluntarily maintained, there is currently no capacity to keep track with ongoing changes in the protocol. So my idea is to wait until the protocol is finished, and only then implement the W3C adapter amongst current JsonWire one.

However, for now you could simply use Selenium server as the translation adapter: it accepts JsonWire and W3C protocol, and translates it to the one the end browser actually talks. The only limitation is you cannot run local WebDriver (meaning connecting directly to GeckoDriver/EdgeDriver without the Selenium server).

However, @paulbriton, if you are willing to help, lets can have a chat and we can start implementing the W3C support sooner! The protocol is still getting more mature and heading to completion and the changes in it may be less breaking :).

**Comment by OndraM** [comment]
And two more notes: there are report the mouseMoveTo in Geckodriver may not yet be wotrking

Also the new Selenium server (3.5+) runs int "passthrough" mode, meaning it do not provides the protocol translation by default and must be run with `-enablePassThrough false` parameter (as per https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG )

**Comment by paulbriton** [comment]
I know that the W3C spec isn't finished yet, but things are moving quite fast from drivers' and Selenium's side. I think the translation to an end browser with Selenium server isn't fully functional since I can't get my test suite working on all browsers (AFAIK ChromeDriver is the more compliant). 

About you're notes, I know that mouseMoveTo doesn't work with Geckodriver, it's this ticket purpose. Since the Geckodriver has been written from scratch, they concentrate their efforts to implement the W3C spec. When I saw an Action class on those bindings I was thinking that we were spec compliant even if it isn't finished. Moreover, I do use the passthrough mode. Without it I can't manage to launch a single test.

> As this project is completely voluntarily maintained, there is currently no capacity to keep track with ongoing changes in the protocol.

This is the same for the Selenium project. I think those bindings could be "official" PHP ones and therefore It will be easier to track changes. They (selenium maintainers) mainly need one active lead developer and since your quite active on this project I think you can met the requirements. 

So I'll be glad to help you to implement the W3C spec and I'm open for a chat !

**Comment by paulbriton** [comment]
@OndraM I've talk to some Selenium members and It'll be nice to see you on #selenium at Freenode (irc.freenode.net) !

**Comment by OndraM** [comment]
W3C compatible actions support was added by #560 and will be part of release 1.8.0 :tada: .
