### ISSUE TITLE
Expose HTTP Response information to the driver

### ISSUE THREAD

**Issue by cardonator** [facebook/php-webdriver#470]
### What are you trying to achieve? (Expected behavior)
I would like to be able to check HTTP response codes as part of my tests.

### What do you get instead? (Actual behavior)
I can't see a way this data is exposed.

### How could the issue be reproduced? (Steps to reproduce)
Just create a web driver and get/navigate to a page.

### Details

* Php-webdriver version: 1.4
* PHP version: 5.6
* Selenium server version: 3.3.1
* Operating system: Docker/Ubuntu

**Comment by OndraM** [comment]
Hi, HTTP status codes are intentionally not available directly through, as Selenium mission statement is to "emulate user actions" (and user does not see and interact with HTTP codes). See https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/141 
HTTP status codes could be tested using different layer of tests than Selenium tests. 

However you have some options, see https://saucelabs.com/blog/options-for-validating-http-codes-in-selenium.

**Comment by cardonator** [comment]
Thanks, I had read both of those links before. They are kind of annoying responses and here's why:

I have a page that requires the _user_ to pass a valid client cert. My test should expect an HTTP response requesting a client cert. That's user actionable even though the code itself is not technically what the user sees. At any rate, this was a convenience thing. Of course there are 50 ways to solve it. It would just be nice if it was in the same package I'm already using for UI acceptance. Thanks for the quick reply!
