### ISSUE TITLE
Not loading files correctly

### ISSUE THREAD

**Issue by angular013** [facebook/php-webdriver#474]
So i installed using composer and when i try to run my script it gives error:

Fatal error: Class 'RemoteWebDriver' not found in E:\xampp\htdocs\new_job\selenium\daily.php on line 11

This is my code ;

`<?php
// An example of using php-webdriver.

require 'vendor/autoload.php';

// start Firefox with 5 second timeout
$host = 'http://localhost:4444/wd/hub'; // this is the default
//$capabilities = DesiredCapabilities::firefox();
//$driver = RemoteWebDriver::create($host, $capabilities, 5000);

$driver = RemoteWebDriver::create($host, DesiredCapabilities::firefox());

// navigate to 'http://docs.seleniumhq.org/'
$driver->get('https://www.amazon.com/gp/goldbox');

// adding cookie
$driver->manage()->deleteAllCookies();
$driver->manage()->addCookie(array(
  'name' => 'cookie_name',
  'value' => 'cookie_value',
));
$cookies = $driver->manage()->getCookies();

// wait at most 10 seconds until at least one result is shown
$driver->wait(10)->until(
  WebDriverExpectedCondition::presenceOfAllElementsLocatedBy(
    WebDriverBy::className('top-list')
  )
);

$sString = $driver->getPageSource();

// close the Firefox
$driver->quit();
print_r($sString);

?>`

**Comment by angular013** [comment]
So i used this on top now as stated in some old issue  ;

namespace Facebook\WebDriver;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;

now a new error comes:

Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\SessionNotCreatedException' with message 'Unable to create new service: GeckoDriverService Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z' System info: host: 'SHAYAN-PC', ip: '192.168.202.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_141' Driver info: driver.version: unknown' in E:\xampp\htdocs\new_job\selenium\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:154 Stack trace: #0 E:\xampp\htdocs\new_job\selenium\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throwException(33, 'Unable to creat...', Array) #1 E:\xampp\htdocs\new_job\selenium\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand)) #2 E:\xampp\htdocs\new_job\selenium\daily.php(14): Facebook\WebDriver\Remote\RemoteWebDriver::creat in E:\xampp\htdocs\new_job\selenium\vendor\facebook\webdriver\lib\Exception\WebDriverException.php on line 154

**Comment by angular013** [comment]
so i was using the wrong localhost port in the code , now i am using the same port as my Xamp server but now another error came:

Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\WebDriverException' with message 'JSON decoding of remote response failed. Error code: 4 The response: '<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> <html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"> <head> <title>Bad request!</title> <link rev="made" href="mailto:admin@example.com" /> <style type="text/css"><![CDATA[/*></style> </head> <body> <h1>Bad request!</h1> <p> Your browser (or proxy) sent a request that this server could not understand. </p> <p> If you think this is a server error, please contact the <a href="mailto:admin@example.com">webmaster</a>. </p> <h2>Error 400</h2> <address> <a href="/">localhost</a> in E:\xampp\htdocs\new_job\selenium\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php on line 292

**Comment by mfestrada** [comment]
@angular013, 2 different things: 

Your original issue with the SessionNotCreatedException error is because your system's PATH variable was missing _geckodriver_.  Downloading that and adding the containing folder to your PATH will solve your issue.  You can download it here: https://github.com/mozilla/geckodriver/releases

Secondly, the second error is happening because you changed the localhost port given in example.php. 
 4444 is the port that's normally used for selenium-specific traffic between hubs and nodes.  When you attempted to run the example, you should have had a selenium-server running on your machine as well.  

Try walking through https://github.com/facebook/php-webdriver#getting-started again.

**Comment by OndraM** [comment]
Thanks @mfestrada for comprehensive answer!
