### ISSUE TITLE
window.onbeforeunload triggers UnexpectedAlertOpenException

### ISSUE THREAD

**Issue by mlantz** [facebook/php-webdriver#475]
### What are you trying to achieve? (Expected behavior)
Utilizing Laravel's Dusk package I'd like to have a test which can confirm that the `window.onbeforeunload` dialog pops up. I need to then close this dialog.

### What do you get instead? (Actual behavior)
Dusk throws this exception: Facebook\WebDriver\Exception\UnexpectedAlertOpenException 

### How could the issue be reproduced? (Steps to reproduce)
If you take the following HTML example: 

```html
<!DOCTYPE html>
<html>
<body onbeforeunload="return myFunction()">

<p>Close this window, press F5 or click on the link below to invoke the onbeforeunload event.</p>

<a href="https://www.w3schools.com">Click here to go to w3schools.com</a>
      
<script>
function myFunction() {
    return "Write something clever here...";
}
</script>

</body>
</html>
``` 

And have a Laravel Dusk test similar to:

```php
public function testDialogForExiting()
{
        $this->browse(function (Browser $browser) {
            $browser->click('Click here to go to w3schools.com');
            $browser->driver->switchTo()->alert()->dismiss();
       });
}
```

Running this test will simply call the above mentioned exception and will not let the tests pass since the dialog cannot be controlled.

### Details

* Php-webdriver version: 1.4.1
* PHP version: 7.1
* Selenium server version: none
* Chrome driver: 2.28.455517 (included with https://github.com/laravel/dusk)
* Operating system: macOS 10.12.6
* Browser used + version: Chrome 60

**Comment by OndraM** [comment]
Hi @mlantz , my guess is that you should not *dismiss* (= cancel) the alert but rather *accept* (= confirm).

Try:
```php
$browser->driver->switchTo()->alert()->accept();
```
and let us know if it works.

If not, please post the complete testcase (incl. the steps you do after you try to accept the modal), fill exception stacktrace and chromeserver logs.

Thanks :)

**Comment by mlantz** [comment]
Fixed it! Thanks. It turned out I had waitForLocation happening before so it was a conflict of steps. Thanks.
