### ISSUE TITLE
No mention of java being a prerequisite to execute the selenium server?

### ISSUE THREAD

**Issue by uberhacker** [facebook/php-webdriver#481]
The README.md is missing a mention about the java executable being a requirement to run the selenium server.  Shouldn't there be a link to download a specific version of java?

**Comment by OndraM** [comment]
Hi, it is mentioned there, in part "Getting started" https://github.com/facebook/php-webdriver#getting-started

> All you need as the server for this client is the selenium-server-standalone-#.jar file provided here: http://selenium-release.storage.googleapis.com/index.html

**Comment by uberhacker** [comment]
That mentions the selenium server, not the java executable required to run the server.  All I'm saying is the documentation shouldn't assume the user already has java installed.

**Comment by OndraM** [comment]
@uberhacker Oh, I see. I guess most of the people will have it, but you are right, I will update it to mention the need of Java there. 

Thanks for the suggestion!

**Comment by OndraM** [comment]
Readme updated, thanks!
