### ISSUE TITLE
Missing 'handle' parameter

### ISSUE THREAD

**Issue by acs047** [facebook/php-webdriver#486]
Hi, 

when I'm trying to set an html element with a value, so i'm calling this 
$this->findElement(WebDriverBy::id("email"))-<senKeys($email);

However when I run it I get this error: 
PHPUnit_Extensions_Selenium2TestCase_WebDriverException: Missing 'handle' parameter
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'PC-AB', ip: '192.168.1.175', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown

\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase\Driver.php:165
\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase\Driver.php:175
\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase\CommandsHolder.php:100
\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase\SessionStrategy\Shared.php:82
\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase\SessionStrategy\Shared.php:82
\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase.php:296
\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase.php:337
\siawise5\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase.php:314

* Php-webdriver version: 1.4
* PHP version: 5.6.31
* Selenium server version: 3.6.0
* Operating system: WIN64
* Browser used + version: firefox 56.0

**Comment by OndraM** [comment]
Hi, according to the exception, you use phpunit-selenium, which is completely different library than this one (php-webdriver) - see https://github.com/giorgiosironi/phpunit-selenium
