### ISSUE TITLE
Failed to wait for extension background page

### ISSUE THREAD

**Issue by fllprbt** [facebook/php-webdriver#487]
### What are you trying to achieve? (Expected behavior)
I am using Selenium with the latest Chrome driver. I want to use a proxy with authorization and considering that this behavior is not supported I am following your guide: https://github.com/RobinDev/Selenium-Chrome-HTTP-Private-Proxy

### What do you get instead? (Actual behavior)
Generally, it works. After hours of work at some point I am getting the following fatal error. Please note, that I am making many plugins for different proxies without any issue. 
```
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnknownServerException: unknown error: failed to wait for extension background page to load: chrome-extension://nknfhemedcefohicgiceepeoabnocgpc/_generated_background_page.html
from timeout: Timed out receiving message from renderer: 10.000
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.9.0-3-amd64 x86_64) (WARNING: The server did not provide any stacktrace information)
```

### How could the issue be reproduced? (Steps to reproduce)
The code is pretty much the same with the "how to use it" from Selenium Chrome HTTP Private Proxy and I cannot think of any way to reproduce. 

* Php-webdriver version: 1.4
* PHP version: 7.0
* Selenium server version: 3.6.0 (Latest)
* Operating system: Debian 9
* Browser used + version:  Chrome v.61

I am not sure if its related to your code, (probably not) but I 'd like to hear your input.

**Comment by OndraM** [comment]
Hi,
to make us able to help you with the issue, could you please:
1. paste the PHP code you use, so the issue could be reproducible
2. ensure you use latest [chromedriver](https://sites.google.com/a/chromium.org/chromedriver/) - make sure command `chromedriver --version` returns something like 2.33.

Thanks :)

**Comment by InnocentRabib** [comment]
same problem. any solution?
