### ISSUE TITLE
executeScrpt() not working correcly 

### ISSUE THREAD

**Issue by acs047** [facebook/php-webdriver#488]
Hi, 

I'm trying to set the values of two ckeditor values and to do that I'm doing using executeScript like this: 

```php
$this->driver->executeScript('$("#elem1").val("TESTE 1");');
$this->driver->executeScript('$("#elem2").val("Teste Funcional");');
```
well when I run the test sometimes it works and puts de values on the two elements, other times just on one of the elements. Can someone help? 

* Php-webdriver version: 1.4
* PHP version: 5.6
* Selenium server version: 3.6.0
* Operating system: Win64 
* Browser used + version: Firefox 56.0

**Comment by OndraM** [comment]
Hi, could you please provide the HTML code and whole testcase you are executing?

Also try this with Selenium 3.4 to see if it behaves the same.

Thanks :)

**Comment by acs047** [comment]
I change the version of the selenium to 3.4 and change my code to this: 

`$this->driver->executeScript('CKEDITOR.instances["elem1"].setData("TESTE ");'); $this->driver->executeScript('CKEDITOR.instances["elem2"].setData("Teste Funcional ");');`

It seems to have fix it
