### ISSUE TITLE
`WebDriverBy::cssSelector('.foo')`  does not function as  `WebDriverBy::className('foo')`

### ISSUE THREAD

**Issue by salarmehr** [facebook/php-webdriver#499]
When I select an element with `WebDriverBy::cssSelector('.foo')`  and `WebDriverBy::className('foo')`, I think both should work identically. However `click` method only works for the second one. Can somebody clarify this. Is it a bug?

**Comment by salarmehr** [comment]
Oh, it's so weird. The issue only happens in Edge

**Comment by OndraM** [comment]
Hi, to make us able to help you, please us the prepared template for new issue and fill all the fields - especially reproducible code and version of browser, selenium etc. Thanks for your cooperation!

**Comment by salarmehr** [comment]
I close it for now until I create a more details issue for it.
