### ISSUE TITLE
How can I configure Firefox 58 profile for downloading files?

### ISSUE THREAD

**Issue by lgraziani2712** [facebook/php-webdriver#505]
### What are you trying to achieve? (Expected behavior)

Download a file automatically to a predefined folder.

### What do you get instead? (Actual behavior)

The action window asking me what to do.

### How could the issue be reproduced? (Steps to reproduce)

This is my configuration

```php
$profile = new FirefoxProfile();

$profile->setPreference('browser.download.folderList', 2);
$profile->setPreference('browser.download.manager.showWhenStarting', false);
$profile->setPreference('browser.download.dir', __DIR__.'/temp');
$profile->setPreference('browser.helperApps.neverAsk.saveToDisk', 'application/pdf');

$caps = DesiredCapabilities::firefox();

$caps->setCapability(FirefoxDriver::PROFILE, $profile);
```

By the way, I tried to modify those preferences in the about:config page. `browser.download.manager.showWhenStarting` and `browser.download.dir` didn't exist, I had to create them. The popup windows still appeared 😢 

### Details

* Php-webdriver version: 1.5.0
* PHP version: 7.1
* Selenium server version: 3.7.0
* Operating system: Windows 8.1
* Browser used + version: Firefox 58.0b5 (64-bit) Developer Edition

**Comment by lgraziani2712** [comment]
Ok. I found my error. I had this header configured for sending pdfs:

```php
header('Content-Disposition: attachment; filename="filename.pdf"');
```

Sadly, the `attachment` option makes Firefox always open the Save as window. Changing it to `inline` solves the problem.

By the way, for Firefox 57++, this is the correct configuration:

```php
$profile = new FirefoxProfile();
$caps = DesiredCapabilities::firefox();

$profile->setPreference('browser.download.folderList', 2);
$profile->setPreference('browser.download.dir', __DIR__.'/temp');
$profile->setPreference('browser.helperApps.neverAsk.saveToDisk', 'application/pdf');
$profile->setPreference('pdfjs.enabledCache.state', false);

$caps->setCapability(FirefoxDriver::PROFILE, $profile);

RemoteWebDriver::create('http://localhost:4444/wd/hub', $caps);
```

PS: on Windows, the browser.download.dir must have `\` instead of `/` for the path!

Cite from: https://stackoverflow.com/questions/47632718/how-to-download-a-file-with-the-php-webdriver-for-selenium-on-firefox-58

**Comment by olleharstedt** [comment]
@lgraziani2712 Can you perhaps explain your last option, `enabledCache.state` and why it have to be `false`?

**Comment by lgraziani2712** [comment]
@olleharstedt If I'm not mistaken, it disables the Firefox's PDF viewer: https://bugzilla.mozilla.org/show_bug.cgi?id=1429160#c9

**Comment by olleharstedt** [comment]
@lgraziani2712 I see. Thank you!

**Comment by olleharstedt** [comment]
NB: I also had to use

```lang=php
$profile->setPreference('browser.download.panel.shown', false);
```

to make it work.
