### ISSUE TITLE
Start Firefox in headless mode

### ISSUE THREAD

**Issue by olleharstedt** [facebook/php-webdriver#506]
### What are you trying to achieve? (Expected behavior)
As with Chrome, I want to be able to start Firefox in headless mode.

### What do you get instead? (Actual behavior)
Can't find any method similar to the ChromeOptions->addArguments(); Can I use setPreference()?

### How could the issue be reproduced? (Steps to reproduce)

```php
// You can insert your PHP code here (or remove this block if it is not relevant for the issue).
```

### Details

* Php-webdriver version: 
* PHP version: 
* Selenium server version: 
* Operating system: 
* Browser used + version:

**Comment by olleharstedt** [comment]
Possible solution: Use `export MOZ_HEADLESS=1` before running selenium.

**Comment by OndraM** [comment]
Hi, I believe you can pass the settings via desired capabilities:

```php
$capabilities = DesiredCapabilities::firefox();

$capabilities->setCapability(
    'moz:firefoxOptions',
   ['args' => ['-headless']]
);

$driver = RemoteWebDriver::create($host, $capabilities);
```

@olleharstedt Could you please try this solution as well? I will add it to the wiki then.

**Comment by olleharstedt** [comment]
Thanks, I'll try this.

**Comment by lgraziani2712** [comment]
I can confirm this works.

Thank you!
