### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead

### ISSUE THREAD

**Issue by NanheKumar** [facebook/php-webdriver#511]
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead

**Comment by OndraM** [comment]
Hi, this is because guzzle is part of dependency of php-coveralls library. It should be fixed with its next release, and this has no impact on the library usage. Also php-coveralls is just development dependency, so you should not be seeing this warning at all.
