### ISSUE TITLE
Take element screenshot not implemented in php-webdriver

### ISSUE THREAD

**Issue by sapzape** [facebook/php-webdriver#513]
As per spec: https://w3c.github.io/webdriver/webdriver-spec.html#dfn-take-element-screenshot
Take element screenshot is not implemented in php-webdriver. It should use the following endpoint:

GET /session/{session id}/element/{element id}/screenshot

It provides a guide, but I think the method implementation is more efficient in usability.
(guide : https://github.com/facebook/php-webdriver/wiki/taking-full-screenshot-and-of-an-element)

If you agree with the need for implementation, can I implement it?

**Comment by OndraM** [comment]
Implemented in #701 :tada:
