### ISSUE TITLE
Misleading statement in doc due to typo.

### ISSUE THREAD

**Issue by unerem** [facebook/php-webdriver#516]
What exists:
```If none element matches when using the findElements() method, an empty array is returned (but no exception is thrown, unlike when using findElements() method).```
Should be :
```If none element matches when using the findElements() method, an empty array is returned (but no exception is thrown, unlike when using findElement() method).```
https://github.com/facebook/php-webdriver/wiki/Finding-an-element

**Comment by OndraM** [comment]
Nice finding, I fixed it in the wiki.

Thank you
