### ISSUE TITLE
Possible DoS using firefox profiles

### ISSUE THREAD

**Issue by prodigysml** [facebook/php-webdriver#519]
### What are you trying to achieve? (Expected behavior)
Testing for XXE vulnerability in the Firefox extension loading. Should disallow entities

### What do you get instead? (Actual behavior)
Does not disallow entities and processes them

### How could the issue be reproduced? (Steps to reproduce)
To be very honest, I am not 100% sure of the workflow for this vulnerability's scenario (due to lack of knowledge of how to use the software, sorry for any mistakes). Basically when the Firefox profile is being encoded, all of the extensions are being installed using the installExtensions function
https://github.com/facebook/php-webdriver/blob/139980fb59bb0e48e47a1bc515ee4fb6e6848780/lib/Firefox/FirefoxProfile.php#L201
This extracts the extension's XPI file into a temporary directory and then uses `simplexml_load_file` to load in the XML (in order to extract the version number). If the `install.rdf` file contains a valid XXE payload (like the billion laughs attack https://en.wikipedia.org/wiki/Billion_laughs_attack), this can cause a DoS scenario (and possibly even code execution). 
https://github.com/facebook/php-webdriver/blob/139980fb59bb0e48e47a1bc515ee4fb6e6848780/lib/Firefox/FirefoxProfile.php#L209

### Remediation
Prior to loading any xml, disable entities ensuring that the above-mentioned attacks will no longer be possible.
`libxml_disable_entity_loader(true);`

### Details

* Php-webdriver version: 1.5.0
* PHP version: 7.2.0
* Selenium server version: 3.8.1
* Operating system: Ubuntu 16.04
* Browser used + version: Firefox

**Comment by OndraM** [comment]
I may be mistaken, but this feature is specific for Firefox prior Firefox 56 (which only supports web extensions), isn't it?

Meaning when people will primarily use the new Firefoxes, there won't be an attack vector for this.

Sure I may use the ` libxml_disable_entity_loader(true);`, but I would rather remove the whole extension loading feature altogether (once we gain #469), because it won't be anyhow useful.
