### ISSUE TITLE
Switch to iframe without name or id

### ISSUE THREAD

**Issue by ameoba32** [facebook/php-webdriver#524]
### What are you trying to achieve? (Expected behavior)
Switch to iframe that has no ID or NAME attribute. I do not control the application, so can't assign ID.  Guess following code could solve the issue, but it does not work

```php
$browserClient->switchTo()->frame(WebDriverBy::cssSelector('.box iframe'));
```

### What do you get instead? (Actual behavior)
Catchable fatal error: Object of class Facebook\WebDriver\WebDriverBy could not be converted to string in /app/docroot/my/tests/vendor/facebook/webdriver/lib/Remote/RemoteTargetLocator.php on line 69

### Details
* Php-webdriver version: 1.5.0
* PHP version: 5.5
* Selenium server version: 3.8.1 (docker image selenium/standalone-chrome)
* Operating system: Linux/docker
* Browser used + version: chrome=63.0.3239.132

**Comment by ameoba32** [comment]
One workaround seems to be
```php
    $browserClient->executeScript("document.getElement('iframe').setAttribute('id','pinFrame');");
    $browserClient->switchTo()->frame('pinFrame');
```

**Comment by ilya-catalyst** [comment]
Have you tried smth like:

        $my_frame = $this->byClassName("iframePage");
        $this->frame($my_frame);

or css selector in your case

**Comment by ameoba32** [comment]
@ilya-catalyst , thanks, but it does not work. in frame() code it gets ID of iframe and uses it down the road.  I am quite happy with JS hack above.

**Comment by staudenmeir** [comment]
`frame()` also accepts a `WebDriverElement` instance:

```php
$iframe = $browserClient->driver->findElement(WebDriverBy::cssSelector('.box iframe'));

$browserClient->switchTo()->frame($iframe);
```
