### ISSUE TITLE
php-webdriver Not working on server even working fine on local machine

### ISSUE THREAD

**Issue by mohanmasters** [facebook/php-webdriver#526]
### What are you trying to achieve? (Expected behavior)
I want to run selenium on aws with firefox and chrome browser  

### What do you get instead? (Actual behavior)
 I have installed selenium 3.8.1 on my local machine with geckodriver and chromedriver and it is working fine when i hit the page from command line and browser but when i am install same configuration on aws i am getting following error.

PHP Fatal error:  Uncaught exception 'Facebook\WebDriver\Exception\WebDriverCurlException' with message 'Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","acceptSslCerts":false}}

 -->

### How could the issue be reproduced? (Steps to reproduce)

namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;

require_once('vendor/autoload.php');

// start Firefox with 5 second timeout

$host = 'http://52.66.162.145:4444/wd/hub'; // this is the default

#$driver = RemoteWebDriver::create($host, DesiredCapabilities::firefox());
#$capabilities = DesiredCapabilities::firefox();
#$driver = RemoteWebDriver::create($host, $capabilities, 5000);
$desired_capabilities = DesiredCapabilities::chrome();
$desired_capabilities->setCapability('acceptSslCerts', false);
$driver = RemoteWebDriver::create($host, $desired_capabilities);
// navigate to 'http://www.seleniumhq.org/'
$driver->get('http://www.seleniumhq.org/');

// adding cookie
$driver->manage()->deleteAllCookies();

$cookie = new Cookie('cookie_name', 'cookie_value');
$driver->manage()->addCookie($cookie);

$cookies = $driver->manage()->getCookies();
print_r($cookies);

// click the link 'About'
$link = $driver->findElement(
    WebDriverBy::id('menu_about')
);
$link->click();

### Details

* Php-webdriver version: 
* PHP version:  php 5.6
* Selenium server version: 3.8.1 and 3.6 
* Operating system:  ubuntu
* Browser used + version:  mozila 58 and chrome

**Comment by OndraM** [comment]
Please try Chrome to see if it works. If so, you may be impacted by #469 . If it will not work either, the problem must be somewhere else.
