### ISSUE TITLE
Safari only: WebDriverSelect->selectByVisibleText not working

### ISSUE THREAD

**Issue by bartonhammond** [facebook/php-webdriver#527]
### What are you trying to achieve? (Expected behavior)
Use WebDriverSelect and selectByVisibleText within Safari browser (it works fine FF & Chrome)

### What do you get instead? (Actual behavior)
No option is selected

### How could the issue be reproduced? (Steps to reproduce)

```php
        $webDriverSelect = new WebDriverSelect($this->find(self::$_selectors['category']));
        $webDriverSelect->selectByVisibleText("My Music");
```

### Details

* Php-webdriver version: ^1.5
* PHP version: 7.1.10
* Selenium server version: ^3.6
* Operating system: OSx 10.11.6
* Browser used + version: Safari 11.0.2 (11604.4.7.1.4)

### Interactive session with `psysh`
<img width="1435" alt="screen shot 2018-02-02 at 1 14 34 pm" src="https://user-images.githubusercontent.com/1282364/35750606-29c506a8-081b-11e8-9591-c7bc2a63479f.png">

**Comment by OndraM** [comment]
@bartonhammond Hi, could you please provide the HTML snippet where this is reproducible? My guess is this may be related to the dash or something else in the HTML source.
