### ISSUE TITLE
standalone selenium server is not running

### ISSUE THREAD

**Issue by flik** [facebook/php-webdriver#531]
### What are you trying to achieve? (Expected behavior)
want to run java selenium server SIMPLE

### What do you get instead? (Actual behavior)
```
sudo java selenium-server-standalone-3.9.1.jar
Error: Could not find or load main class selenium-server-standalone-3.9.1.jar
```

### How could the issue be reproduced? (Steps to reproduce)

```php
sudo java selenium-server-standalone-3.9.1.jar
Error: Could not find or load main class selenium-server-standalone-3.9.1.jar
```

### Details

* Php-webdriver version:  https://github.com/facebook/php-webdriver
* PHP version:  PHP 7.X
* Selenium server version:  selenium-server-standalone-3.9.1.jar

* Operating system: Ubuntu 16
* Browser used + version:  crome

**Comment by OndraM** [comment]
Hi, please see readme about information how to start Selenium server: https://github.com/facebook/php-webdriver#getting-started
