### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Facebook\WebDriver\Remote\DesiredCapabilities' not found

### ISSUE THREAD

**Issue by flik** [facebook/php-webdriver#537]
### What are you trying to achieve? (Expected behavior)
running your example.php

### What do you get instead? (Actual behavior)
Fatal error: Uncaught Error: Class 'Facebook\WebDriver\Remote\DesiredCapabilities' not found in D:\xampp\htdocs\php-webdriver\example.php:9 Stack trace: #0 {main} thrown in D:\xampp\htdocs\php-webdriver\example.php on line 9

### How could the issue be reproduced? (Steps to reproduce)

```php
<?php
// An example of using php-webdriver.
namespace Facebook\WebDriver;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
require_once('vendor/autoload.php');
// start Firefox with 5 second timeout
$host = 'http://localhost:4444/wd/hub'; // this is the default
$capabilities = DesiredCapabilities::firefox();
$driver = RemoteWebDriver::create($host, $capabilities, 5000);
// navigate to 'http://www.seleniumhq.org/'
$driver->get('http://www.seleniumhq.org/');
// adding cookie
$driver->manage()->deleteAllCookies();
$cookie = new Cookie('cookie_name', 'cookie_value');
$driver->manage()->addCookie($cookie);
$cookies = $driver->manage()->getCookies();
print_r($cookies);
// click the link 'About'
$link = $driver->findElement(
    WebDriverBy::id('menu_about')
);
$link->click();
// wait until the page is loaded
$driver->wait()->until(
    WebDriverExpectedCondition::titleContains('About')
);
// print the title of the current page
echo "The title is '" . $driver->getTitle() . "'\n";
// print the URI of the current page
echo "The current URI is '" . $driver->getCurrentURL() . "'\n";
// write 'php' in the search box
$driver->findElement(WebDriverBy::id('q'))
    ->sendKeys('php');
// submit the form
$driver->findElement(WebDriverBy::id('submit'))
    ->click(); // submit() does not work in Selenium 3 because of bug https://github.com/SeleniumHQ/selenium/issues/3398
// wait at most 10 seconds until at least one result is shown
$driver->wait(10)->until(
    WebDriverExpectedCondition::presenceOfAllElementsLocatedBy(
        WebDriverBy::className('gsc-result')
    )
);
// close the Firefox
$driver->quit();

```

### Details

* Php-webdriver version:  "facebook/webdriver": "dev-master"
* PHP version: 7.x
* Selenium server version:  selenium-server-standalone-3.9.1.jar

* Operating system: windows
* Browser used + version: crome

**Comment by OndraM** [comment]
Hi,
you apparently did not install project dependencies via Composer (and also removed the autoloading from the example.php).

Please refer to "Installation" section of readme: https://github.com/facebook/php-webdriver#installation

**Comment by flik** [comment]
please do not close this issue. I have installed all dependencies vi composer. here are output of composer show:
```bash
feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver
$ composer show

facebook/webdriver           dev-master 2aa1653 A php client for WebDriver
phpunit/php-code-coverage    1.2.13             Library that provides coll...
phpunit/php-file-iterator    1.3.4              FilterIterator implementat...
phpunit/php-text-template    1.1.4              Simple template engine.
phpunit/php-timer            1.0.5              Utility class for timing
phpunit/php-token-stream     1.2.1              Wrapper around PHP's token...
phpunit/phpunit              3.7.28             The PHP Unit Testing frame...
phpunit/phpunit-mock-objects 1.2.3              Mock Object library for PH...
symfony/yaml                 v2.3.7             Symfony Yaml Component

feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver
$
```

**Comment by Baker-007** [comment]
I am also facing the same problem, Fatal error: Uncaught Error: Class 'Facebook\WebDriver\Remote\DesiredCapabilities' not found .... Had set the dependencies earlier as well !!!. So what is the resolution bty now ?

**Comment by Jammin-Coder** [comment]
> I am also facing the same problem, Fatal error: Uncaught Error: Class 'Facebook\WebDriver\Remote\DesiredCapabilities' not found .... Had set the dependencies earlier as well !!!. So what is the resolution bty now ?

@Baker-007 I had the same problem. I had to add this line `require_once('vendor/autoload.php');` and it fixed the issue.  
I would try that.

**Comment by rounding-synonymous** [comment]
@OndraM https://phps.space/questions/what-is-the-best-way-to-handle-page-reload-in-selenium
