### ISSUE TITLE
Open a new tab does not update getWindowHandles()

### ISSUE THREAD

**Issue by q-jack** [facebook/php-webdriver#553]
What are you trying to achieve? (Expected behavior)
I woul like to open a new tab in chrome and switch between the new tabs

// using the browser shortcut to create a new tab
$handles = $wd->getWindowHandles();
var_dump($handles);
$wd->getKeyboard()->sendKeys(
array(WebDriverKeys::CONTROL, 't'),
);
$handles = $wd->getWindowHandles();
var_dump($handles);

What do you get instead? (Actual behavior)
There is a new tab but the getWIndowsHandles function delivers just one handle. So I cant switch to another handle

Details
Php-webdriver version: 1.5.0 ( lmc steward 2.3)
PHP version: 7.0.13
Selenium server version: 3.8.1
Operating system: windows 10
Browser used + version: chrome Version 64.0.3282.186

**Comment by domagala** [comment]
Hi, I am experiencing the same. Does anyone have some feedback on this issue?

**Comment by holyczech** [comment]
Hi, I am using javascript to open new tab:
```
$result = $driver->executeScript("window.open('about:blank','_blank');", array());
$handles = $driver->getWindowHandles();
print_r($handles);
```

```
Array
(
    [0] => CDwindow-188BB450509BB168A6930650A970BC86
    [1] => CDwindow-7FD87F7A121DC3CE3D7F76EA96E7D2C0
)
```

**Comment by dryan-curve** [comment]
I experienced a similar issue, but realized it was a timing issue. Was able to resolve the issue with a sleep, and eventually a custom wait function.

**Comment by OndraM** [comment]
I just checked unit tests for this case - it seems everything is working properly...  Make sure you use something like `$driver->wait()->until(WebDriverExpectedCondition::numberOfWindowsToBe(2));` before you try to switch to the new window - like we do [in tests](https://github.com/facebook/php-webdriver/blob/1ad0697c6ada89b21e4a768b04ca82a89fc6a0a6/tests/functional/RemoteWebDriverTest.php#L139)
