### ISSUE TITLE
How to avoid implicit timeout with WebDriver::findElements()

### ISSUE THREAD

**Issue by LionelLaffineur** [facebook/php-webdriver#554]
### What are you trying to achieve? (Expected behavior)
Trying to avoid the implicit timeout with WebDriver::findElements()

### What do you get instead? (Actual behavior)
Even if I set the implicit timeout to zero (WebDriver::manage()->timeouts()->implicitlyWait(0)), calling WebDriver::findElements() keeps waiting instead of exiting directly as it does with WebDriver::findElement().

### How could the issue be reproduced? (Steps to reproduce)
```php
$webdriver->manage()->timeouts()->implicitlyWait(0);
$webdriver->findElements(WebDriverBy::xxxx());
```
Using implicitlyWait(0) before findElement(), it exits directly throwing NoSuchElementException.
I would like to do the same with findElements().

### Details
* Php-webdriver version: facebook/webdriver, 1.5.0
* PHP version: PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
* Selenium server version: elgalu/docker-selenium latest (3.11.0-p3)
* Operating system: Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
* Browser used + version: Chrome stable: 65.0.3325.162, Chromedriver: 2.37.543619 (a237acd3116cac3b3f0da42a000502ce3fafcb23)
* https://github.com/elgalu/docker-selenium/releases/tag/3.11.0-p3

**Comment by OndraM** [comment]
This is proper behavior of `findElemens`. Unlike `findElement`, it *does not* throw an exception if none element is found (and returns empty array instead).

If you for some reason need to exit if `findElemens` does not find any element, you can throw the exception by yourselves:

```php
$elements = $webdriver->findElements(WebDriverBy::xxxx());
if (count($elements) === 0) {
    throw new \Exception(...);
}
```
