### ISSUE TITLE
to find elements with xpath methods

### ISSUE THREAD

**Issue by jkeilla** [facebook/php-webdriver#555]
### What are you trying to achieve? (Expected behavior)
I need to use xpath methods to find the elements of a PivotTable.

### What do you get instead? (Actual behavior)
Fatal error:  Uncaught Facebook\\WebDriver\\Exception\\NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//tr[td[1] = "Nome do Depositante: "]/td[2]/font[1]"}

### How could the issue be reproduced? (Steps to reproduce)
I tried to use this code: 

```php
$nome_depositante = $driver->findElement(
	WebDriverBy::xpath('//tr[td[1]="Nome do Depositante: "]/td[2]/font[1]')
)->getText(); // get the font tag from column 2 of the line where you have the term "depositor name" in the first column 
```

### Details

* Php-webdriver version: 1.5
* PHP version: 7.0.25
* Selenium server version: 3.3.1
* Operating system: Linux Mint 18.3
* Browser used + version: Chrome 65.0.3325

**Comment by staudenmeir** [comment]
What does your HTML look like?

**Comment by jkeilla** [comment]
<table width="780px" border="0">
	
	<tbody><tr>
		<td align="center" colspan="6">
			<font class="normal">
				
				<b>Depósito de pedido nacional de Patente</b>
				
			</font>
		</td>
	</tr>
	<tr>
		<td align="right" width="160">
			<font class="alerta"> 
				(21)
			</font>
			<font class="normal">Nº do Pedido:</font>&nbsp; 
			
		</td>
		<td align="left">
			<font class="marcador"> 
				BR 10 2019 008779 0 
			</font>
			
		</td>
		
		<td align="right" rowspan="3">
			
			
			
			
		</td>
		
	</tr>
	<tr>
		<td align="right">
			<font class="alerta">(22)</font>&nbsp;
			<font class="normal">Data do Depósito:</font>
		</td>
		<td align="left">
			<font class="normal">&nbsp;
				30/04/2019
			</font>
		</td>
		<td align="left"></td>
	</tr>
	<tr>
		<td align="right">
			<font class="alerta">(43)</font>&nbsp;
			<font class="normal">Data da Publicação:</font>
		</td>
		<td align="left">
			<font class="normal">&nbsp; 
				-		
			</font>
		</td>
		<td align="left"></td>
	</tr>
	<tr>
		<td align="right">
			<font class="alerta">(47)</font>&nbsp;
			<font class="normal">Data da Concessão:</font>
		</td>
		<td align="left">
			<font class="normal">&nbsp; 
				-
			</font>
		</td>
		<td valign="middle" align="right" rowspan="8">
			
		</td>
	</tr>
	
	<tr>
		<td align="right">
			
			<font class="alerta">(71)</font>&nbsp;
			<font class="normal">Nome do Depositante:</font> 
			
		</td>
		<td align="left">
			<font class="normal">&nbsp; 
				ASSOCIAÇÃO EDUCACIONAL DE CIÊNCIAS DA SAÚDE - AECISA (BR/PE)
			</font>
		</td>
		<td align="left"></td>
	</tr>
	
	
</tbody></table>


The problem is that sometimes other tr? Appears before the line I want to pick up.

**Comment by staudenmeir** [comment]
Specify the exact element that contains "Nome do Depositante:":

```php
$nome_depositante = $driver->findElement(
    WebDriverBy::xpath('//tr[td[1][font[2][text()="Nome do Depositante:"]]]/td[2]/font[1]')
)->getText();
```

**Comment by jkeilla** [comment]
Thank you :)

**Comment by staudenmeir** [comment]
Please close the issue.
