### ISSUE TITLE
how can i set userAgent for Opera?

### ISSUE THREAD

**Issue by tyTYtyChan** [facebook/php-webdriver#561]
### What do you get instead? (Actual behavior)

           $capabilities=[
                WebDriverCapabilityType::BROWSER_NAME => 'operablink',
                'chromeOptions'=> [
                    'binary' => 'E:\Opera\launcher.exe',
                    'args' => ['--user-agent=not work!'] //how can i set userAgent for Opera? help me pls
                ]
            ];

### How could the issue be reproduced? (Steps to reproduce)

```php
// You can insert your PHP code here (or remove this block if it is not relevant for the issue).
```

### Details

* Php-webdriver version: 
* PHP version: 
* Selenium server version: 
* Operating system: 
* Browser used + version:

**Comment by edvardpotter** [comment]
Could you open opera?
