### ISSUE TITLE
Help for generate report of testcase

### ISSUE THREAD

**Issue by dipenpatel235** [facebook/php-webdriver#562]
### What are you trying to achieve? (Expected behavior)
i have setup selenium server and facebook php web driver client.
now using php code i have write test case and work fine.

now i want to generate report of that created test case .
so how i can generate test case report from php.

### What do you get instead? (Actual behavior)
DOn't know what i need to write in php code to generate test report.
testng is useful but for java. i don't know how to do in php.

### Details
* PHP version: 5.6
* Selenium server version: 3.11
* Operating system: Ubuntu
* Browser used + version: firefox + 56.00

**Comment by OndraM** [comment]
You can use php-webdriver via some testing framework which will generate test reports. 

See README: https://github.com/facebook/php-webdriver#testing-framework-integration
