### ISSUE TITLE
click on the list of items | stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by DmitrySkibitsky** [facebook/php-webdriver#563]
Help. The task is to click on all the items in the list in turn.
On the second element in the list, call $element->click(); crashes.

HTML
```html
<li class=" advancedLi li_lv_1" 
id="productCompare_Manufacturer_AMMANN"
onclick="selectManufacturer('AMMANN'); selectModel(null)"></li>
<li class=" advancedLi li_lv_1" 
id="productCompare_Manufacturer_AMMANN2"
onclick="selectManufacturer('AMMANN2'); selectModel(null)"></li>
... ... ...
```

php
```php
$this->elements = $this->driver->findElements(WebDriverBy::className('advancedLi'));
foreach ($this->elements as $element) {
    $element->click();
}
```
console error
```php
Facebook/WebDriver/Exception/StaleElementReferenceException with message 
'stale element reference: element is not attached to the page document
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.35 (0),platform=Linux 4.16.2-1-MANJARO x86_64)'

```

* Php-webdriver version: latest
* PHP version: 7.2.4
* Selenium server version: 3.11.0
* Operating system: Linux 4.16.2-1-MANJARO x86_64
* Browser used + version: chrome=65.0.3325.181

**Comment by DmitrySkibitsky** [comment]
I will be grateful if you give an example of how this can be done.

**Comment by DmitrySkibitsky** [comment]
@klimart , One more question. It does not concern the problem. I want to know the opinion of another person. I have an assignment to write a parser. The parser works in this way: a direct link to the product is entered, the data is dragged into the database. And this site is all built on ajax queries. [(if you want to look at the page of the site)](https://catalog.mann-filter.com/EU/rus/catalog/MANN-FILTER%20Katalog%20Europa/%D0%A2%D1%80%D0%B0%D0%BD%D1%81%D0%BF%D0%BE%D1%80%D1%82%D0%BD%D1%8B%D0%B5%20%D1%81%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B2%D0%B0/%D0%9B%D0%B5%D0%B3%D0%BA%D0%BE%D0%B2%D1%8B%D0%B5%20%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D0%B8%20+%20%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D0%B8-%D1%84%D1%83%D1%80%D0%B3%D0%BE%D0%BD%D1%8B/ARO/ARO%2010/1.4%20(T101284)/%D0%A1%D0%BC%D0%B0%D0%B7%D0%BE%D1%87%D0%BD%D0%BE%D0%B5%20%D0%BC%D0%B0%D1%81%D0%BB%D0%BE/W%2075~3) Any action on tabs and sub-items on these tabs is a separate query . So I decided to do it using php-webdriver + selenium. I've already found how to start a selenium on vps and at the same time so that you can work with the browser. But I doubt how much reasonable this idea is.

**Comment by DmitrySkibitsky** [comment]
@klimart 
On the second element in the list, call $element->click(); crashes.
```php
Facebook/WebDriver/Exception/UnknownServerException with message 'unknown error: Element <li class=" advancedLi li_lv_1" id="productCompare_Manufacturer_GEHL" onclick="selectManufacturer('GEHL'); selectModel(null)">...</li> is not clickable at point (503, 500). Other element would receive the click: <div class="cc_banner cc_container cc_container--open">...</div>
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.16.2-1-MANJARO x86_64)'

```

**Comment by klimart** [comment]
Regarding this error, I have similar in cases when some popup covers
required element you want to click, it can be search suggestions in my
case.
Regarding technology stack, it will work for you and this stack can resolve
any scraping needs

**Comment by DmitrySkibitsky** [comment]
@klimart , Thank you. So far I have found another solution. Gathered the parameters for the js method which is onclick and passed it on execution in turn with a delay. But it would be safer to click. Since there I can control the appearance of the block on the page. Although if executeScript assumes that operations after this method will start only after executeScript is finished then this option looks reliable.

**Comment by cprn** [comment]
AFAIU this issue is exactly what it says. Between your search and 2nd click something changes the DOM of the website (most probably the 1st click does) therefore the reference for the 2nd item you acquired as a result of `findElements()` method wasn't a part of DOM any more. You need to get new reference for each element in the loop (search for them again). This is unfortunately common for SPAs.

**Comment by DmitrySkibitsky** [comment]
@cprn I just noticed that it takes the coordinates for the click. In this case, it is true that it will not be able to get to the right element in any case. There, each click deploys a nested list and changes the position of the next item in the list of those that you want to click on. Thank you.

**Comment by cprn** [comment]
Can we assume this was a website specific issue and the driver behaves correctly then? Can this be closed?

**Comment by DmitrySkibitsky** [comment]
@cprn yes, close
