### ISSUE TITLE
loosing browser session if the any exception comes

### ISSUE THREAD

**Issue by viktorgreamer** [facebook/php-webdriver#566]
if i try to work with php facebook webdriver sometimes session losts from exception.
for instanse "element is not visible exception" . but browser is still working and waiting for commands. and there are no ways to remote it and close via program because it starts new session and new browser. how can i get old session and start browser from old session?

`
$old_session = '2b332be4e52cac08232e24d62a5610d6';
 $driver = RemoteWebDriver::createBySessionID($old_session, 'http://localhost:9515/');
`

`
JSON decoding of remote response failed.
Error code: 4
The response: 'unknown command: /session/2b332be4e52cac08232e24d62a5610d6/url'`

* Php-webdriver version: 1.4
* PHP version: 5,6
* Selenium server version: 
* Operating system: windows 8
* Browser used + version:  chromedriver 2.3

**Comment by viktorgreamer** [comment]
sorry , $host = 'http://localhost:9515' without slash)))))

**Comment by OndraM** [comment]
Hi, you can encapsulate the call in try-catch statement, so that you catch the exception, process it and continue the rest of the command. Have a look at some PHP tutorial on exceptions handling, as this topic is a little bit complex and not related to php-webdriver.

**Comment by viktorgreamer** [comment]
> Hi, you can encapsulate the call in try-catch statement, so that you catch the exception, process it and continue the rest of the command. Have a look at some PHP tutorial on exceptions handling, as this topic is a little bit complex and not related to php-webdriver.

Hi thanks)) I have resolved the issue.
