### ISSUE TITLE
enable chrome console log

### ISSUE THREAD

**Issue by cpintea** [facebook/php-webdriver#570]
### What are you trying to achieve? (Expected behavior)
To enable chrome console loging when browser is started by chrome drive

### What do you get instead? (Actual behavior)
the "chrome_debug.log" file in  User Data is empty

### How could the issue be reproduced? (Steps to reproduce)

```php
// You can insert your PHP code here (or remove this block if it is not relevant for the issue).
```
call : url_setopt($curl, CURLOPT_POSTFIELDS, json_encode($parameters));
with 
{"desiredCapabilities":{"tags":["CPI","PHP 5.6.32"],"browser":"firefox","ignoreZoomSetting":false,"name":"Behat feature suite","chrome.switches":["--enable-logging","--v=4"],"chrome.extensions":[],"chromeOptions":{"args":["--enable-logging","--v=4"],"extensions":[]},"browserName":"chrome"}}
or

### Details

* Php-webdriver version: 
* PHP version: 5.6.32
* Selenium server version: 3.3.1
* Operating system:  Windows 8
* Browser used + version:  Chrome latest

The capabilities "parameters" values are set in a behat config file. Is this the correct format? The curl_setopt return TRUE.

**Comment by mb0000** [comment]
Just as an observation.....

After a lot of effort debugging and comparing with the "official" Java WebDriver suite, I see that this PHP WebDriver implements none of the Logging preference classes.

With the Chrome Driver, you can access the browser's Console Log by using the non-standard setCapabilities call:
`$chromeCapabilities->setCapability( 'loggingPrefs', ['browser' => 'ALL'] );`
Then, a call to 
`$chromeDriver->manage()->getLog( 'browser' )`
returns the console log.

**Comment by qozle** [comment]
For me, this is only returning an empty array.  I'm calling it after I'm running some async javascript in the browser (which def does some `console.log()`s) with the `$driver->executeAsyncScript()` method.  I even added in a `sleep(10)` after to make sure it would have time to run.  Could the reason I'm getting nothing back be because of the async js?

```
//  Set chromium to run headlessly  
$chromeOptions = new ChromeOptions();
//  NOTE make sure to check debugging address
$chromeOptions->addArguments(['--headless', '--disable-gpu', 'start-maximized', '--no-sandbox', '--verbose']);
		
$desiredCapabilities = DesiredCapabilities::chrome();
$desiredCapabilities->setCapability(ChromeOptions::CAPABILITY_W3C, $chromeOptions);
$desiredCapabilities->setCapability('loggingPrefs', ['browser'=>'ALL']);
$desiredCapabilities->setPlatform('Linux');
$driver = RemoteWebDriver::create($chromeDriverServer, $desiredCapabilities);

//  navigate to the layout file and execute some JS on it
$driver->get($layoutFileLocation);	

....

$jsFile = fopen('grader.js', 'r');
$js = fread($jsFile, filesize('grader.js'));
fclose($jsFile);	
		
//  Read the spam dictionary file
$spamFile = fopen('./spam/big-spam-list.txt', 'r');
$spamList = fread($spamFile, filesize('./spam/big-spam-list.txt'));
fclose($spamFile);

$emailStats = $driver->executeAsyncScript($js, [$spamList]);
		
		
sleep(10);
$logs = $driver->manage()->getLog('browser');
var_dump($logs);
$driver->quit();
die();
```
