### ISSUE TITLE
Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\UnknownCommandException' with message 'GET /session/e91eb1d6-0347-410a-a0e7-212e8a77c954/element//displayed

### ISSUE THREAD

**Issue by gohelkiran** [facebook/php-webdriver#580]
### What are you trying to achieve? (Expected behavior)
check element is displayed or not

### What do you get instead? (Actual behavior)
getting an exception UnknownCommandException

 Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\UnknownCommandException' with message 'GET /session/e91eb1d6-0347-410a-a0e7-212e8a77c954/element//displayed Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z' System info: host: 'WIN-SR99V6JM70G', ip: '10.0.0.249', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_171' Driver info: driver.version: unknown' in E:\webenvoy\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:106 Stack trace: #0 E:\webenvoy\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throwException(9, 'GET /session/e9...', Array) #1 E:\webenvoy\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(535): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand)) #2 E:\webenvoy\vendor\facebook\webdriver\lib\Remote\RemoteExecuteMethod.php(40): Facebook\WebDriver\Remote\RemoteWebDriver->execute('i in E:\webenvoy\vendor\facebook\webdriver\lib\Exception\WebDriverException.php on line 106

### How could the issue be reproduced? (Steps to reproduce)
start selenium node and run test on firefox browser

```php
 if($element) {
	if($element->isDisplayed()) {
		try{
			$element->click();
		}
	}
}
// You can insert your PHP code here (or remove this block if it is not relevant for the issue).
```

### Details

* Php-webdriver version:  1.2
* PHP version:   5.5.9
* Selenium server version:  3.12.0
* Operating system: Windows Server 2008 R2
* Browser used + version:  Firefox 60.0.1

**Comment by OndraM** [comment]
Hi, sorry - this is part of #469, latest Firefox is not yet supported, as it only supports new W3C protocol. Sed the referenced issue for workarounds.
