### ISSUE TITLE
Error when uploading large files greater than 100mb

### ISSUE THREAD

**Issue by travisblue1234** [facebook/php-webdriver#581]
Hi please help. I have an error with the driver when uploading large files. This is working with small files like 1 mb but when trying to upload more than 100 mb it doesnt work anymore.  I am using the sendkeys method to the file input field.

`Fatal error: Uncaught Facebook\WebDriver\Exception\UnknownServerException: Failed parsing JSON source: JsonReader at line 1 column 99587884 path $.file to Json in C:\xampp\htdocs\driver\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:114 Stack trace: #0 C:\xampp\htdocs\driver\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(326): Facebook\WebDriver\Exception\WebDriverException::throwException(13, 'Failed parsing ...', Array) #1 C:\xampp\htdocs\driver\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(547): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand)) #2 C:\xampp\htdocs\driver\vendor\facebook\webdriver\lib\Remote\RemoteExecuteMethod.php(40): Facebook\WebDriver\Remote\RemoteWebDriver->execute('uploadFile', Array) #3 C:\xampp\htdocs\driver\vendor\facebook\webdriver\lib\Remote\RemoteWebElement.php(446): Facebook\WebDriver\Remote\RemoteExecuteMethod->execute('uploadFile', Array) #4 C:\xampp\htdocs\driver\vendor\facebook\webdriver\lib in `

**Comment by OndraM** [comment]
Hi, this seems like an issue in Selenium - it probably runs out of memory.

You will have to adjust Java settings or use some different way to upload the file - see https://github.com/SeleniumHQ/selenium/issues/5354#issuecomment-360719369

**Comment by kirilkirkov** [comment]
@travisblue1234 Did you find a solution about uploading of big files? @OndraM  ? In my tests i need to upload files between 300 and 500MB ?

sudo docker run -d -p 4444:4444 -e SE_JAVA_OPTS="-Xmx4G -Xms4G" -e JAVA_OPTS="-Xmx4G -Xms4G" -p 5900:5900 --shm-size=2g --restart=always selenium/standalone-chrome:latest

This does not allow me to do that. I receive error - file not found..

```
        $fileInput = $this->driver->findElement(WebDriverBy::id("edit-Origin{$field_index}"));
        $fileInput->setFileDetector(new LocalFileDetector());
        $fileInput->sendKeys($track_location);
```
