### ISSUE TITLE
Simulate real user mouse mouvements

### ISSUE THREAD

**Issue by apirahim** [facebook/php-webdriver#582]
### What are you trying to achieve? (Expected behavior)
Simulate a real user mouse movements
### What do you get instead? (Actual behavior)
A bot mouse mouvements

### How could the issue be reproduced? (Steps to reproduce)

```php
$driver->get('website.com');
$username_element = $driver->findElement(WebDriverBy::xpath("//input[@name='username']"));
$driver->getMouse()->mouseMove($username_element->getCoordinates());
```

### Details
I would like to simulate a real user mouse mouvements, and by that I mean when the mouse move pixel per pixel until it reach it's location, but instead selenium just show up at that specific element

the problem is when you provide selenium the WebDriverCoordinates, it's not like (x,y) location but it's something else instead

how can I tell selenium to move to that location scanning every pixel in it's way ( kind of like drag and drop) 

* Selenium server version: selenium-server-standalone-3.11.0
* Operating system:  win 10
* Browser used + version:  chrome

**Comment by cprn** [comment]
This is an upstream feature request. This project is for glue between PHP and `selenium-server-standalone` only (selenium server is what talks with webdriver). What you're asking for could be (in theory maybe?) implemented in webdriver itself but I don't think it's [W3C compliant](https://www.w3.org/TR/webdriver/) so there's no guarantee all browsers would oblige.
