### ISSUE TITLE
.phar out request

### ISSUE THREAD

**Issue by GregJohnStewart** [facebook/php-webdriver#586]
Would be nice to see this library packaged as a .phar for easily using it in places where one can't use composer. Would love to use this, but can't due to the fact I am not using composer :/

**Comment by cprn** [comment]
You might want to use [clue/phar-composer](https://github.com/clue/phar-composer).

**Comment by GregJohnStewart** [comment]
While I was successful in making a phar (thanks a ton for the suggestion @cprn !), it would still be nice to see the phar with the releases, since it does not seem to be terribly difficult.

**Comment by GregJohnStewart** [comment]
Created PR #588

**Comment by OndraM** [comment]
This project is a library - it is useless as a standalone application (in contrast of phpunit, phpstan, Robo, which could be used as standalone tools), so I don't see a reason for a phar.

What is your usecase? Why can't you use Composer?

**Comment by GregJohnStewart** [comment]
It's just a nice way to package the library. I can put the whole directory in my project, and have to include all the files in git, or I can have a nicely packaged phar to reference in one place, and as one file.

My usecase is that my web hosting service does not support composer, and to set it all up locally just for the testing side of things seems silly.

**Comment by OndraM** [comment]
Phar is not intended for packing libraries, but for packing whole applications (or tools) which are supposed to be used and distributed as a standalone and most often exedcutable package. And this is not a typical case for library of this kind - you will need Composer to resolve dependencies according to your actual runtime (php 5 / php 7), you will also usually need to install other dependencies via Composer (like PHPUnit etc.).

While there may be some limited usecase for phar, I don't see the overhead (to prepare and build phar every single release and to maintain it) worth the benefits, sorry.

Also installing Composer is quite easy, and as it is defacto standard of PHP dependencies management (almost all libraries use it), I very much recommend using it, as it makes all PHP development much easier ;-).
