### ISSUE TITLE
extensions not working on chrome

### ISSUE THREAD

**Issue by michondr** [facebook/php-webdriver#587]
### What are you trying to achieve? (Expected behavior)
to be able to visit site of extension by going to its options page

### What do you get instead? (Actual behavior)
Error 20 (net::ERR_BLOCKED_BY_CLIENT): Requests to the server have been blocked by an extension."

### How could the issue be reproduced? (Steps to reproduce)
just by creating driver in this fashion:
```php
private function createDriver(Config $config): RemoteWebDriver
    {
        //not working - can't load proxy extension, and we can't connect to extension site
        $capabilities = DesiredCapabilities::chrome();

        $options = new ChromeOptions();
        $options->addExtensions([__DIR__.'/chrome_proxy_auto_auth.crx']);

        $capabilities->setCapability(ChromeOptions::CAPABILITY, $options);

        $options->addArguments(['--proxy-server=217.16.177.12:5000']);
        
        $driver = RemoteWebDriver::create(self::SERVER_HOST, $capabilities);

        $driver->get('chrome-extension://ggmdpepbjljkkkdaklfihhngmmgmpggp/options.html');

        echo $driver->getPageSource();
// here the driver cant lad page and returns an error that the page is blocked
        $driver->quit();
        die;
    }

```

### Details
This certainly is a problem, as the same logic works when connecting to the same selenium hub from python 
It acts the same as launching chromium-browser console with --headless option, where extensions do not work. But nodes run in xvfb, so I see no reason why this should not work
 
* Php-webdriver version: facebook/webdriver 1.6.0  
* PHP version: PHP 7.1.19-1
* Selenium server version: selenium-server-standalone-3.9.0
* Operating system: Ubuntu 16.04
* Browser used + version: Chromium 66.0.3359.181 Built on Ubuntu , running on Ubuntu 16.04
![image](https://user-images.githubusercontent.com/29277166/42722530-c4fdc25c-874d-11e8-8066-8fefbafe6576.png)

**Comment by commanddotcom** [comment]
`addExtensions` method doesn't work for me as well. I have try loading different crx-file but none of them was displayed on the page `chrome://extensions/` and none of them was mentioned on the page `chrome://version/`

**Comment by OndraM** [comment]
Hi, I tried the same code and installing the same extension. It seems to be working now. 

In case this issue persist, please try with latest chrome + chromedriver and let us know.

(BTW - the error "ERR_BLOCKED_BY_CLIENT" does not necessarily mean there is something blocking the url - this error occurs when the extension is not installed and you are trying to visit its options page via the `chrome-extension://ggmdpepbjljkkkdaklfihhngmmgmpggp/options.html` url).
