### ISSUE TITLE
Add PHPDoc with @throws to RemoteWebDriver.execute method

### ISSUE THREAD

**Issue by itaibh** [facebook/php-webdriver#592]
### What are you trying to achieve? (Expected behavior)
In the IDE (PhpStorm) I'm calling the `execute` method of a `RemoteWebDriver`. I know it is possible an exception will be thrown and want to be ready for it. However, when I add a `catch` clause with `WebDriverException` the IDE complains that there is no need to catch that exception since nothing throws it, while I see the `throws` two levels in.

### What do you get instead? (Actual behavior)
The IDE shouldn't complain about the existing `WebDriverException`, and should complain when it isn't handled.

### How could the issue be reproduced? (Steps to reproduce)
```php
...
try {
    $remoteWebDriver->execute("return 'test';");
} catch (WebDriverException $ex) { // In PhpStorm this line shouldn't be marked with a warning.
}
...
```

### Details
* Php-webdriver version: 1.6.0

I added the relevant PHPDoc in PR #591, but it asks me to sign something and I just don't feel like it.

**Comment by OndraM** [comment]
Thanks @itaibh for the suggestion! We hope to have this fixed as part of future php-webdriver 2.0.
