### ISSUE TITLE
getLog("browser") returns an empty array

### ISSUE THREAD

**Issue by leviv** [facebook/php-webdriver#594]
### What are you trying to achieve? (Expected behavior)

When calling `getLog("browser")` I expect the webdriver to return an array containing all of the browser logs.

### What do you get instead? (Actual behavior)

The browser returns an empty array. I am able to call `getLog("server")` and get a nonempty array, but `getLog("browser")` is always empty no matter how many entries are in the console log

### How could the issue be reproduced? (Steps to reproduce)

I am using the code below:

```php
$logs = $this->webDriver->manage()->getLog("browser");
var_dump($logs);
```

### Details

* Php-webdriver version: 1.6.0
* PHP version: PHP 7.2.8
* Selenium server version: Selenium 3.13.0
* Operating system: MacOS High Sierra 10.13.4
* Browser used + version: Google chrome Version 67.0.3396.99

**Comment by amhoho** [comment]
please try it:
```php
$caps->setCapability( 'loggingPrefs', ['browser' => 'ALL']);
var_dump($driver->manage()->getLog('driver'));
```

**Comment by ricardoperovano** [comment]
Is it possible to listen to this logs ?

**Comment by OndraM** [comment]
This does not seems like an issue of php-webdriver.
