### ISSUE TITLE
chromewebdriver not works for me

### ISSUE THREAD

**Issue by andervilo** [facebook/php-webdriver#610]
I am try execute this code
        $host = 'http://localhost:4444/wd/hub';
        $capabilities = DesiredCapabilities::chrome();
        $driver = RemoteWebDriver::create($host, $capabilities, 5000);
        $driver->get('https://www.google.com.br/');
        $driver->quit();
this open a chrome window but the code return de message: Maximum execution time of 30 seconds exceeded

so this not works for me

**Comment by exfriend** [comment]
Not related to webdriver.

http://php.net/manual/en/function.set-time-limit.php

**Comment by OndraM** [comment]
Also the report does not contain information which are needed to understand the problem. @andervilo  Please us the template provided when creating new issue and fill all the fields. Otherwise it is not possible for others to help you.
