### ISSUE TITLE
JSON decoding of remote response failed. Error code: 4 The response: '' [code: 0]

### ISSUE THREAD

**Issue by Evolutiounx** [facebook/php-webdriver#619]
### What are you trying to achieve? (Expected behavior)
So I have this script loading facebook pages and I'm trying to load this page with;
`$driver->get("https://www.facebook.com/pg/" . $facebookPage . "/ads/?country=1&ref=page_internal");"`
and then execude some more code after it
Let's pretend it's loading http://www.google.com because in this case I don't think it makes any difference what page I'm loading.

### What do you get instead? (Actual behavior)
So basically after loading for example 100 facebook pages I randomly get this error `JSON decoding of remote response failed. Error code: 4 The response: '' [code: 0]`
exacly after running this line of code `$driver->get("https://www.facebook.com/pg/" . $facebookPage . "/ads/?country=1&ref=page_internal");"`
but this line of code ran 100 times before on a bunch of different facebook pages so I have no idea on why I get this error only on the 100th time , or on the 12th time, or on the 26th time, it's kinda random, also it's not the facebook page problem since I ran driver->get on a specific page several times before without any problems and on the 13th crawling that same page it could give me that error even know it got that page 13 times before, it's completely random

I've been trying to figure out what the error even means and I think it's because it can't get the raw code of the page I'm trying to get? But I have it recording a video of the screen of the machine loading that specific page fine but I still get that error code, what do you think it could be?

Also if there's no way to solve this error is there a way to run a specific code after I get that error on the script? Because the script stops after getting that error and if I could run a code after failing I could just resume the test by initializing it again sicne I record every step on a database and that would kinda fix the problem

### How could the issue be reproduced? (Steps to reproduce)

2 videos that randomly stopped on a page after getting several pages fine before:

[http://s3-us-west-1.amazonaws.com/027a15f2-530d-31e5-f8cc-7ceaf6355377/191584eb-8154-6735-70f6-b3ae70927bfe/play.html?add7ec6239e6f89eba9d05a3e394073f
](http://s3-us-west-1.amazonaws.com/027a15f2-530d-31e5-f8cc-7ceaf6355377/191584eb-8154-6735-70f6-b3ae70927bfe/play.html?689c7959ae5e8d1a300d823a47e402a8)

[http://s3-us-west-1.amazonaws.com/027a15f2-530d-31e5-f8cc-7ceaf6355377/191584eb-8154-6735-70f6-b3ae70927bfe/play.html?add7ec6239e6f89eba9d05a3e394073f
](http://s3-us-west-1.amazonaws.com/027a15f2-530d-31e5-f8cc-7ceaf6355377/191584eb-8154-6735-70f6-b3ae70927bfe/play.html?add7ec6239e6f89eba9d05a3e394073f
)
(skip to the end of the videos to see that the page loads fine even know I get an error on the script)

`$driver->get("https://www.facebook.com/pg/" . $facebookPage . "/ads/?country=1&ref=page_internal");
`
I think this is the only code relevant to this case since it happens after I run that line several times and the specific error comes from that line, I would paste here the whole code but it's too damn long, 2320 lines to be exact.
Also I'm 100% sure the error is causing after that line because I have an echo after that line and it doesn't echo, so it's 100% being caused by that line.

### Details

* Php-webdriver version: No idea how to check this but I got it with composer 3 months ago I think
* PHP version: PHP 7.2.11
* Selenium server version: 3.5.3
* Operating system: LINUX
* Browser used + version: chrome, latest version

**Comment by OndraM** [comment]
Hi, thanks for the report, but there doesn't seem to be a steps how to reproduce the issue. Without reproducible testcase we are unable to help and trace the issue, if there is any.

But my guess is some network issue on your infrastructure. However if you are able to provide exact steps how we can reproduce the issue, please open new issue. Also make sure to use latest version of Selenium server, php-webdriver, chrome and chromedriver.

Thanks
