### ISSUE TITLE
WebDriver wait with IgnoreExceptions

### ISSUE THREAD

**Issue by OneEyedSpaceFish** [facebook/php-webdriver#623]
### What are you trying to achieve? (Expected behavior)
While handling stale element exceptions
(A JavaScript in a tested page conditionally overwrites the DOM element list in the page causing `StaleElementExceptions`)

A workaround solution in java for click() is:
```java
new WebDriverWait(driver, timeout)
        .ignoring(StaleElementReferenceException.class)
        .until((WebDriver d) -> {
            d.findElement(By.id("LINK")).click();
            return true;
        });
```

Or
```java
new WebDriverWait(driver, timeout).ignoring(StaleElementReferenceException.class).until(ExpectedConditions.elementToBeClickable(By.id("LINK")));
driver.findElement(By.id("LINK")).click();
```

### What do you get instead? (Actual behavior)
This, in PHP is a pain.
We are using Codeception, and in a module that uses php-webdriver we are extending each method that interacts with the webpage (see, click, select, grab, etc.) and wrapping it around a try->catch mechanism, that would retry in case of `StaleElementException` was thrown.

```php
    /**
     * @param WebDriverElement $element
     * @param bool $retry
     */
    public function clickWebDriverElement(WebDriverElement $element, bool $retry = true): void
    {
        try {
            $element->click();
        } /** @noinspection PhpRedundantCatchClauseInspection */ catch (StaleElementException $exception) {
            if ($retry) {
                $this->debug('Stale element reference exception occurred, retrying');
                $this->reloadPage();
                $this->clickWebDriverElement($element, false);
            }

            $this->fail("Failed to click element '{$element->getID()}' due to stale element reference exception");
        }
    }
```

I've been wondering if there's a better way to deal with this issue?

### Details
* Php-webdriver version: 1.6.0
* PHP version:  PHP 7.2 (With Codeception 2.5.2)
* Selenium server version: 3.141.59
* Operating system: Docker/Debian based container
* Browser used + version: Google Chrome: 71.0.3578.98 / ChromeDriver: 2.45

**Comment by cprn** [comment]
It's not really a bug. Stale element exception happens when you try to use a search result containing DOM node that changed after it was found (e.g. it doesn't exist any more). It means you need to call `findElement()` again and obtain a fresh search result, not `reloadPage()`.

Since you know tested website changes DOM a lot, maybe try to find those parts of your code that pass around stale elements and replace them with `findElement($conditions)->click()` chain instead? For example when iterating over a collection of elements you should look for specific element again in each iteration or if you deal with a detached DOM node maybe you need to [wait](https://github.com/facebook/php-webdriver/wiki/HowTo-Wait) until it's available.

**Comment by OneEyedSpaceFish** [comment]
@cprn Thanks for your quick & detailed response!

You are correct, this is not a bug, but more of a feature request / depending if you have a workaround.

Since the DOM changes a lot, even `findElement($conditions)->click()` resulted in an occasional stale element issue. My suspicion at the time was because that chain is not truly simultaneous, first, we pre-fetch the element, then we are trying to execute actions on it. The less time elapses between those two actions, the less likely is to encounter a stale element issue, but it's still possible / happens. (but I could be very well wrong here)

I had a look around, and it seems that the workaround using the java solution is to combine your two suggestions by waiting till a findElement + click() action had occurred whilst ignoring all StaleElementExceptions. 

This gets even more complicated where we are fetching a list of options and then executing a series of checks on it, and depending on their state, setting them accordingly, or when we are retrieving the contents of a field.

For whatever reason (although this still occurs) while trying to interact with the website, and if a StaleElement issue occurred, a retry, then if it's getting thrown again, then a full reload page solution seemed to be resulting in fewer failures, although I am fully aware that this is a sub-optimal nuclear option, and gets even more complicated as we have to use the same mechanism to fetch all non-persistent data from all options and fields so they could be re-entered during the recovery mechanism. Not to mention, that this still doesn't solve the issue, just lessen the impact (somewhat).

I found this online https://facebook.github.io/php-webdriver/master/WebDriverExpectedCondition.html#method_refreshed although this still doesn't seem to be a fully implementable solution, as I've said, sometimes we need to just simply fetch data from the website. Or do more advanced assertions on the given element that it is available to us using `WebDriverExpectedCondition`.

What do you think?

**Comment by cprn** [comment]
Yes, you're right about finding a node and clicking it not being simultaneous actions, even when `findElement()` and `click()` are chained together, but they can't really be. I don't think the Java solution you've found makes them simultaneous either. AFAIK there's no way to **lock** DOM for read and write to make the action atomic, i.e. prevent DOM changes while you're using it - there are no DOM transactions. Something like that got proposed around 2012 but AFAIK it never entered the standard. Selenium project was initiated long time ago (15 years?) to aid the website development process by automatic functional testing and this is its primary purpose. In order to test a website it needs to be testable, therefore, sometimes you need to rewrite part of it to work with your testing framework, that includes functional testing and Selenium. When you talk about fetching data from a website for me it's a clue a different tool might do a better job. I don't know what to recommend, I'm not using Selenium to fetch data from a 3rd party JavaScript-heavy websites.

**Comment by OneEyedSpaceFish** [comment]
>  I don't think the Java solution you've found makes them simultaneous either

Correct, although to me it seems to be a better workaround [to have the ability to use `findElement($conditions)->click()` in `wait()` ignoring all `StaleElementExceptions` till either it times out, or the action success]

This is not essential to me, as I could just implement my own wrapper around `findElement($conditions)->click()` chain, but I reckon the functionality what the php-webdriver lacks compared to the Java solution is to ignore exceptions could be useful for other users.

> When you talk about fetching data from a website for me it's a clue a different tool might do a better job.

Testing is mostly done the traditional way, although the website that's being tested contains persistent options that are being changed depending on the test scenario, and those options then being cleaned up after a test run. Other than some of our more advanced assertions, it's mostly this 'cleanup' functionality that needs to hydrate the apps state to determine what needs reverting back to the default option - to prevent the next test run from failing due to different settings.

The tests are designed to behave in more-or-less end to end testing fashion.


We are running a Codeception in a docker environment with a standalone Chrome / Headless / Firefox (although that's been having a sick 'day' due to the w3c support issue) container.

This then is deployed, run in every x minutes, and monitored by a third-party app, and if the set thresholds are reached, then ops are getting alerted due to a suspected outage.

Is there a more suited tool that you think would suit us better / compliment our current setup/selenium?

>   In order to test a website it needs to be testable, therefore, sometimes you need to rewrite part of it to work with your testing framework, that includes functional testing and Selenium.

Very true, most of the issue lies that the web app that's being tested has been made a long time ago, and then it's got build upon. Some effort had been made to rewrite some functionality, but not all of the issues could've been corrected without rewriting most of it.

As per a real-life scenario, this is a process of both incrementally improving the core application, and the test's capabilities to recover from those 'expected' issues.

Once again, thank you for your help, I'll try to have a wrapper for `findElement()->click()` and any other web driver actions to try to mitigate the risk of StaleElement issues anyway.
This will take a while as I'm currently pre-occupied with a different project, but I'll post the result, just in case someone stumbles upon this thread in the feature.

**Comment by cprn** [comment]
What you've described makes a lot of sense and no, unfortunately I can't think of any better suited tool. :/ I also feel your pain of working with legacy code.

Maybe we could extend `Facebook\WebDriver\WebDriverWait` with the `ignoring($exception::class)` method so it could be used in the same way as in Java. It's doable, would require a rewrite of the `catch` block in `until()` to catch all exceptions (currently it only handles `NoSuchElementException`) and then compare the type of caught exception with an argument passed to `ignoring()`.

**Comment by OneEyedSpaceFish** [comment]
:+1: 

I'll have a look to determine how big of an effort this would this would take.
If it's doable in a reasonable amount of time, I'll try to jump on this soon-ish, unless any other peep would want to pick this up beforehand.

I'll keep you / and the other / updated.

**Comment by OndraM** [comment]
Closing this issue for now - however if anyone is interested, you are more than welcome to send a PR addresing this issue :+1:
