### ISSUE TITLE
Invalid null cookie field values being sent to driver.

### ISSUE THREAD

**Issue by JorisVanEijden** [facebook/php-webdriver#626]
### What are you trying to achieve? (Expected behavior)
Prevent cookies with null field values from being sent to drivers.

### What do you get instead? (Actual behavior)
Cookies with null values are accepted for path, domain, expiry, secure and httpOnly.

### How could the issue be reproduced? (Steps to reproduce)
Add a cookie with null values (default in webdriver) for properties.

```php
$webdriver->manage()->addCookie('name', 'value');
```
The command sent to the driver does not have the null values for cookie properties removed.

### Details
Both 
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol 
and 
https://w3c.github.io/webdriver/#add-cookie 
imply that cookie properties that are null should be absent rather than present with a null value.

Chromedriver 2.46 actually rejects null values for these cookie parameters.
```bash
[Facebook\WebDriver\Exception\UnrecognizedExceptionException] invalid argument: invalid 'expiry' 
(Session info: chrome=72.0.3626.81)
(Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.9.125-linuxkit x86_64)
```
See https://chromium.googlesource.com/chromium/src/+/c83119b466cfd63fd1eb616ee86b22ede5db3c4e%5E%21/

* Php-webdriver version:  1.6.0
* PHP version: 7.2

**Comment by reinholdfuereder** [comment]
I think @JorisVanEijden's PR https://github.com/facebook/php-webdriver/pull/627 addresses this issue?
