### ISSUE TITLE
BrowserStack & Safari/Mojave problem

### ISSUE THREAD

**Issue by sergeolkhovik** [facebook/php-webdriver#628]
### What are you trying to achieve? (Expected behavior)
I'm using this webdriver to run some web UI tests on different browsers in BrowserStack.
All different combinations (Safari/High Sierra, FF/Mojave, Chrome/Mojave) work OK except exactly Safari/Mojave.

### What do you get instead? (Actual behavior)
I'm getting 'Session not started or terminated' response from BrowserStack after I launch session and then try to open some URL.

### How could the issue be reproduced? (Steps to reproduce)
If you have account at BrowserStack, then something like:

```php
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\WebDriverBy;

$wd = RemoteWebDriver::create('http://USER:PASSWORD@hub.browserstack.com/wd/hub', [
  'os' => 'OS X', 'os_version' => 'Mojave', 'browser' => 'Safari', 'browserstack.local' => 'false', 'browserstack.debug' => true
]);
$wd->get('http://r52.pnwsoft.com/video/autotest?spec=d%2FOS+X%2FMojave%2FSafari');
```

### Details
When I add a line to dump reponse output like

        $response = $executor->execute($command); error_log("WebDriver response: " . print_r($response, true));

then I see that response contains session ID:
```
Facebook\WebDriver\Remote\WebDriverResponse Object
(
    [status:Facebook\WebDriver\Remote\WebDriverResponse:private] => 0
    [value:Facebook\WebDriver\Remote\WebDriverResponse:private] => Array
        (
            [sessionId] => 38b191d94b1a1e20dd91065ba7a963cc7a5c9212
            [capabilities] => Array
                (
                    [browserVersion] => 12.0
                    [acceptInsecureCerts] =>
                    [browserName] => Safari
                    [platformName] => macOS
                    [setWindowRect] => 1
                )

        )

    [sessionID:Facebook\WebDriver\Remote\WebDriverResponse:private] =>
)
```

but either there's something wrong with this data or not enough, I don't know; anyway next request to open needed URL does nothing, WebDriver throws exception about timeout (in video recorded by BrowserStack I see that Safari window is open and nothing happens then).
If I try with Chrome/Mojave, then response is like this:

```
Facebook\WebDriver\Remote\WebDriverResponse Object
(
    [status:Facebook\WebDriver\Remote\WebDriverResponse:private] => 0
    [value:Facebook\WebDriver\Remote\WebDriverResponse:private] => Array
        (
            [mobileEmulationEnabled] =>
            [hasTouchScreen] => 1
            [platform] => MAC
            [acceptSslCerts] =>
            [goog:chromeOptions] => Array
                (
                    [debuggerAddress] => localhost:50049
                )

            [acceptInsecureCerts] =>
            [webStorageEnabled] => 1
            [browserName] => chrome
            [takesScreenshot] => 1
            [javascriptEnabled] => 1
            [setWindowRect] => 1
            [unexpectedAlertBehaviour] => ignore
            [applicationCacheEnabled] =>
            [rotatable] =>
            [networkConnectionEnabled] =>
            [chrome] => Array
                (
                    [chromedriverVersion] => 2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5)
                    [userDataDir] => /var/folders/3y/zz_w6_s56sl__vcrf3r5bhzr0000hr/T/.org.chromium.Chromium.Nq3lxp
                )

            [takesHeapSnapshot] => 1
            [pageLoadStrategy] => normal
            [databaseEnabled] =>
            [handlesAlerts] => 1
            [version] => 71.0.3578.80
            [browserConnectionEnabled] =>
            [nativeEvents] => 1
            [webdriver.remote.sessionid] => 039a622b26cbed92017e853841992162eff46b35
            [locationContextEnabled] => 1
            [cssSelectorsEnabled] => 1
        )

    [sessionID:Facebook\WebDriver\Remote\WebDriverResponse:private] => 039a622b26cbed92017e853841992162eff46b35
)
```

In addition I checked Safari/Mojave with BrowserStack via C# with the code like this:

```
using System;
using OpenQA.Selenium;
using OpenQA.Selenium.Remote;

namespace browserstack_safari
{
    class Program
    {
    static void Main(string[] args) {
      IWebDriver driver;
      DesiredCapabilities capability = new DesiredCapabilities();
      capability.SetCapability("browser", "Safari");
      capability.SetCapability("browser_version", "12.0");
      capability.SetCapability("os", "OS X");
      capability.SetCapability("os_version", "Mojave");
      capability.SetCapability("resolution", "1024x768");
      capability.SetCapability("browserstack.user", "USER");
      capability.SetCapability("browserstack.key", "PASSWORD");

      driver = new RemoteWebDriver(
        new Uri("http://hub-cloud.browserstack.com/wd/hub/"), capability
      );
      Console.WriteLine("Session " + ((RemoteWebDriver)driver).getSessionId());
      driver.Navigate().GoToUrl("http://r52.pnwsoft.com/video/autotest?spec=d%2FOS+X%2FMojave%2FSafari");
      // await Task.Delay(2000);
      // Task.Delay(2000).Wait();
      System.Threading.Thread.Sleep(new TimeSpan(0, 0,12));
      Console.WriteLine(driver.Title);

      driver.Quit();
    }
    }
}
```

And that works fine, also I tested with https://code.google.com/archive/p/php-webdriver-bindings/ - and that worked fine (but crashes on other tests like Samsung S9 or Note).

If I can help you with tests or additional debug please let me know, really want this problem resolved.

* Php-webdriver version: 1.6.0
* PHP version: 7.0.33
* Selenium server version: 3.5.2 - 3.14.0
* Operating system: Linux / Ubuntu 16.04.6 LTS
* Browser used + version: Safari 12.0 / Mojave

**Comment by OndraM** [comment]
Hi @sergeolkhovik and sorry for late reply. Could you please verify the problem still persist with latest stable php-webdriver (1.7.1) and also with the development version (`composer require facebook/webdriver:^1.8@dev`).

Thanks a lot!

**Comment by OndraM** [comment]
So I dived a bit in this issue. However using the exact same code, even the old version of php-webdrver (as well as the last) and running tests against BrowserStack, I was unable to reproduce the issue - the test works seamlessly.

But if someone is still experiencing this issue on browserstack, let us know (and provide code you use + full error output), we can reopen the issue and have a look.
