### ISSUE TITLE
Headless mode throws NoSuchElementException exception

### ISSUE THREAD

**Issue by andrewgorpenko** [facebook/php-webdriver#631]
### What are you trying to achieve? (Expected behavior)
I want to select the elements in the headless mode

### What do you get instead? (Actual behavior)
The program throws NoSuchElementException exceptions saying "Unable to locate element". If I remove headless option, then everything works fine, but this involves a browser window. I need a headless one.

### How could the issue be reproduced? (Steps to reproduce)
```php
<?php

require 'vendor/autoload.php';

use Facebook\WebDriver\Chrome\ChromeOptions;
use Facebook\WebDriver\Exception\NoSuchElementException;
use Facebook\WebDriver\Exception\TimeOutException;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\WebDriverBy;
use Facebook\WebDriver\WebDriverExpectedCondition;

$host = 'http://localhost:4444/wd/hub';

$options = new ChromeOptions();
$options->addArguments(['--headless', '--disable-gpu', '--window-size=1200,1100', '--no-sandbox']);
$caps = DesiredCapabilities::chrome();
$caps->setCapability(ChromeOptions::CAPABILITY, $options);
$driver = RemoteWebDriver::create($host, $caps);
$driver->get('https://www.olx.ua/obyavlenie/ischu-sozhitelnitsu-IDDW6ub.html');

$driver->wait(10); // This line is ignored by the webdriver, idk why

$driver->findElement(WebDriverBy::cssSelector('.contact-button > span.spoiler'))->click();
// Some job here
$driver->quit();
```

### Details
* Php-webdriver version: 73.0.3683.68
* PHP version: 7.3
* Selenium server version: Selenium build info: version: '3.9.1', revision: '63f7b50'
* Operating system: Windows 10
* Browser used + version: Chrome 73

**Comment by cprn** [comment]
Does `$driver->wait(10);` even work without `->until($condition)`?

**Comment by andrewgorpenko** [comment]
Forgot to close the issue. The target website banned me because of “Headless” user-agent. I’ve replaced the header and everything is working now.

**Comment by cprn** [comment]
Still, according to docs calling `wait()` only constructs an instance of `WebDriverWait` but it does nothing unless you call `until()` on it:

```php
    /**
     * Construct a new WebDriverWait by the current WebDriver instance.
     * Sample usage:
     *
     *   $driver->wait(20, 1000)->until(
     *     WebDriverExpectedCondition::titleIs('WebDriver Page')
     *   );
     *
     * @param int $timeout_in_second
     * @param int $interval_in_millisecond
     * @return WebDriverWait
     */
```
