### ISSUE TITLE
confirm about how to upload file

### ISSUE THREAD

**Issue by shiratsu** [facebook/php-webdriver#635]
### What are you trying to achieve? (Expected behavior)
check whether this way in this page is correct
https://github.com/facebook/php-webdriver/wiki/Upload-a-file

### What do you get instead? (Actual behavior)
i can't upload file based on this way in this page.

### How could the issue be reproduced? (Steps to reproduce)

```php
  // getting the input element
  $fileInput = $driver->findElement(WebDriverBy::id('file_input'));

  // set the file detector
  $fileInput->setFileDetector(new LocalFileDetector());

  // upload the file and submit the form
  $fileInput->sendKeys($filePath)->submit();
```

### Details
i can't upload a file based on the this code is shown below 
```php
  // getting the input element
  $fileInput = $driver->findElement(WebDriverBy::id('file_input'));

  // set the file detector
  $fileInput->setFileDetector(new LocalFileDetector());

  // upload the file and submit the form
  $fileInput->sendKeys($filePath)->submit();
```

however i can upload remove '->submit()'. like this
```php
  // getting the input element
  $fileInput = $driver->findElement(WebDriverBy::id('file_input'));

  // set the file detector
  $fileInput->setFileDetector(new LocalFileDetector());

  // upload the file and submit the form
  $fileInput->sendKeys($filePath);
```

if i want to submit a form immediately, the way in the above page might be correct.
but usually 
web page has other items for input.

how do you guys think about it?

**Comment by OndraM** [comment]
I updated the wiki page a bit, to make the file upload process more clear.

**Comment by eze92** [comment]
Hi, I'm trying to load an image with the example code and it throws me the error
Error: Class 'Test\LocalFileDetector' not found, already  I already have the dependencies included in the test
use PHPUnit\Framework\TestCase;
use Facebook\WebDriver;
require_once('vendor/autoload.php');

**Comment by andrewnicols** [comment]
@eze92 ,

This is a closed issue and not a support channel. It seems as though you are not including the LocalFileDetector somehow, or you are somehow trying to use it directly. Without an actual sample of code, we are unable to tell you what you're doing wrong.

I'd suggest looking at the functional unit tests in tests/functional/FileUploadTest.php for an example of how you might use this.
