### ISSUE TITLE
Start chrome without the selenium standalone server.

### ISSUE THREAD

**Issue by vickyssj7** [facebook/php-webdriver#647]
I've gone through the doc for facebook webdriver, please note I'm using latest version of everything including facebook/webdriver, chromedriver, selenium. This is what written in the doc:

--------------------------------

You can find more information and download ChromeDriver in https://code.google.com/p/selenium/wiki/ChromeDriver. **After downloading the chrome driver, we can start chrome without the selenium standalone server.**

```
   putenv("webdriver.chrome.driver=/path/to/chromedriver");
   $driver = ChromeDriver::start();
```

So I tried using headless mode to run chrome, here is my code:
```

putenv("webdriver.chrome.driver=". __DIR__ ."/chromedriver.exe");
$driver = ChromeDriver::start();
$host = 'http://localhost:4444/wd/hub'; // this is the default
$options = new ChromeOptions();
$options->addArguments(array(
	'--headless',
	'--window-size=1280x800',
	'--disable-gpu',
	'--no-sandbox'
));

$capabilities = DesiredCapabilities::chrome(); 
$capabilities->setCapability(ChromeOptions::CAPABILITY, $options);
$driver = RemoteWebDriver::create($host, $capabilities, 5000);

$driver->get('https://web.testserver.org/');
print_r($driver);
die;
```

as I can see chrome is running in background but then closes by iteself, and error that I'm getting is:

```
Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"firefox","platform":"ANY","firefox_profile":"UEsDBAoAAAAAADVg107f9RXUMgAAADIAAAAHAAAAdXNlci5qc3VzZXJfcHJlZigicmVhZGVyLnBhcnNlLW9uLWxvYWQuZW5hYmxlZCIsIGZhbHNlKTsKUEsBAj8DCgAAAAAANWDXTt\/1FdQyAAAAMgAAAAcAAAAAAAAAAAAAALaBAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAAVwAAAAAA"}}

Failed to connect to localhost port 4444: Connection refused - Line:- 297 File: F:\xamppnew\htdocs\chayenubot\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php
```

I know that you will say that you need to run selenium standalone, but I don't want to run it, as I want to run chrome without selenium to make automation. Please let me know.

**Comment by staudenmeir** [comment]
Use `http://localhost:9515` when you are running ChromeDriver without Selenium:

```php
$host = 'http://localhost:9515';
```

Unfortunately, `ChromeDriver::start()` opens an empty browser window, so the test isn't really "headless".

You can use Symfony's `Process` class instead:

```php
use Symfony\Component\Process\Process;

$process = new Process(__DIR__.'/chromedriver.exe');
$process->start();

$host = 'http://localhost:9515';
$options = new ChromeOptions();
$options->addArguments(array(
    '--headless',
    '--window-size=1280x800',
    '--disable-gpu',
    '--no-sandbox'
));

$capabilities = DesiredCapabilities::chrome();
$capabilities->setCapability(ChromeOptions::CAPABILITY, $options);
$driver = RemoteWebDriver::create($host, $capabilities, 5000);

$driver->get('https://web.chayenu.org/');
$driver->close();

$process->stop();
```

**Comment by vickyssj7** [comment]
Ok I'll check @staudenmeir , also is it possible to run bot on server whether it's linux or windows based server to run bot in headless mode to do the task.

**Comment by vickyssj7** [comment]
I tried chromedriver on ubuntu server but symfony process is not helping as I had to use xvfb to run the chromedriver in order to run the chrome in headless mode and that worked for me to make testing from ubuntu server in order to automate the process.

**Comment by nirmalgoswami** [comment]
i am getting following error while starting web driver using code 

`unknown error: Chrome failed to start: was killed. (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location D:\chromedriver_win32\chromedriver.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)`
