### ISSUE TITLE
Chrome options has changed

### ISSUE THREAD

**Issue by abdrmdn** [facebook/php-webdriver#653]
### What are you trying to achieve? (Expected behavior)
ChromeWebdriver has been updated lately and this repo is out of date.
So I'm supposed to keep using my modules that are depending on this Webdriver without breaking.

### What do you get instead? (Actual behavior)
Modules not working (ex. MobileEmulator https://github.com/nojimage/codeception-mobileemulation/issues/1)

### How could the issue be reproduced? (Steps to reproduce)
Just use mobile emulator

### Details
This [Mobile Emulation Module](https://github.com/nojimage/codeception-mobileemulation) is doing this:

```
$driver->_capabilities(function($currentCapabilities) use ($mobileEmulation) {
            $chromeOptions = new ChromeOptions();
            $chromeOptions->setExperimentalOption('mobileEmulation', $mobileEmulation->toArray());
            $currentCapabilities[ChromeOptions::CAPABILITY] = $chromeOptions->toArray();

            return $currentCapabilities;
        });
```
And because php-webdriver isnt updated with the latest `CAPABILITY` its making it fail.

## Already Created a PR 
https://github.com/facebook/php-webdriver/pull/652

* Php-webdriver version: latest
* PHP version: 7.2
* Selenium server version: selenium/standalone-chrome:3.141.59-radium
* Operating system: Linux mint
* Browser used + version: chrome

**Comment by OndraM** [comment]
See https://github.com/facebook/php-webdriver/pull/652#issuecomment-552188901
