### ISSUE TITLE
Geckodriver 0.24.0 

### ISSUE THREAD

**Issue by luckyraul** [facebook/php-webdriver#654]
### What are you trying to achieve? (Expected behavior)

Test Firefox with Codeception
### What do you get instead? (Actual behavior)

SessionID Is Null
### How could the issue be reproduced? (Steps to reproduce)

Geckodriver 0.24.0, Codeception 3.0.2, facebook/webdriver 1.7.1

### Details Geckodriver logs

```json
1564127990035	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"5492b5ae-cc46-f641-8f9a-4c868cdd608e","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"68.0.1","moz:accessibilityChecks":false,"moz:buildID":"20190717172542","moz:geckodriverVersion":"0.24.0","moz:headless":false,"moz:processID":1115,"moz:profile":"/var/folders/xt/8b1hm05j32vc19t4cc1xnt0m0000gp/T/rust_mozprofile.bOTneERvRiUa","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"mac","platformVersion":"18.6.0","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
```

Here https://github.com/facebook/php-webdriver/blob/community/lib/Remote/HttpCommandExecutor.php#L324 sessionID is returning not as $result['sessionId']. It contains in the $result['value']['sessionId']. 
Then sessionId is still null and  we have ```GET /session//screenshot``` 404

* Php-webdriver version: 1.7.1
* PHP version: 7.1
* Selenium server version: 
* Operating system: OsX
* Browser used + version:  Firefox 68

**Comment by OndraM** [comment]
Geckodriver support was added in #560 and will be part ofnext php-webdriver release (1.8.0).
