### ISSUE TITLE
Fatal error: Uncaught Facebook\WebDriver\Exception\UnknownServerException: Cannot define class using reflection

### ISSUE THREAD

**Issue by awakash** [facebook/php-webdriver#655]
### What are you trying to achieve? (Expected behavior)

php test.php to run successfully

### What do you get instead? (Actual behavior)

Getting the following fatal error when running php test.php:
```
Fatal error: Uncaught Facebook\WebDriver\Exception\UnknownServerException: Cannot define class using reflection in /test/selenium/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:114
Stack trace:
#0 /test/selenium/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php(331): Facebook\WebDriver\Exception\WebDriverException::throwException(13, 'Cannot define c...', Array)
#1 /test/selenium/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(144): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 /test/selenium/test.php(19): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 5000)
#3 {main}
  thrown in /test/selenium/vendor/facebook/webdriver/lib/Exception/WebDriverException.php on line 114
```

### How could the issue be reproduced? (Steps to reproduce)

Chrome 76
ChromeDriver 76.0.3809.68
java -jar selenium-server-standalone-3.9.0.jar

```php
// You can insert your PHP code here (or remove this block if it is not relevant for the issue).
<?php
// An example of using php-webdriver.

namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Chrome\ChromeOptions;

require_once('vendor/autoload.php');

// start Chrome with 5 second timeout
$host = 'http://localhost:4444/wd/hub'; // this is the default
$capabilities = DesiredCapabilities::chrome();
$options = new ChromeOptions();
$options->addArguments(array("--headless","--disable-gpu", "--no-sandbox"));
$capabilities->setCapability(ChromeOptions::CAPABILITY, $options);

$driver = RemoteWebDriver::create($host, $capabilities, 5000);

// navigate to login screen
$driver->get('https://www.google.com');
$driver->quit();
```

### Details

* Php-webdriver version: ChromeDriver 76.0.3809.68
* PHP version: PHP 7.1.23
* Selenium server version: java -jar selenium-server-standalone-3.9.0.jar
* Operating system: MacOS Mojave 10.14.6
* Browser used + version: Chrome 76

**Comment by staudenmeir** [comment]
Did you see https://github.com/SeleniumHQ/selenium/issues/4964?

**Comment by awakash** [comment]
Ah thanks so much for the tip @staudenmeir ! Strange that I was able to use java v11 initially, but after updating the php-webdriver from v75 to v76 it started giving me these errors.

Some more context to folks who run into this, I had this version working initially:
$ java -version
$ java 11.0.4 2019-07-16 LTS

Then installed openjdk8, instructions here:
https://stackoverflow.com/questions/52524112/how-do-i-install-java-on-mac-osx-allowing-version-switching
or via brew 
$ brew cask install adoptopenjdk8

I then deleted java v11, instructions here:
https://docs.oracle.com/javase/8/docs/technotes/guides/install/mac_jdk.html

Now, running 
$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

Was able to run scripts I initially ran.

**Comment by EmanueleCoppola** [comment]
Same error here, it happened when I upgraded from Chromedriver 75 to 76 (and also Chrome), nothing else.

**Comment by OndraM** [comment]
Closing as this is (was) a issue of Selenium server.
