### ISSUE TITLE
Errors in finding elements

### ISSUE THREAD

**Issue by Mr3RF** [facebook/php-webdriver#658]
When I try to find an element using is id or the other attributes I will get this error "Undefined index: ELEMENT in /var/www/html/project/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php on line 208" please help me it's a really important project!

**Comment by XenXenOfficial** [comment]
https://github.com/facebook/php-webdriver/issues/468

**Comment by Mr3RF** [comment]
When I add that parameter I will receive "Execption in thread 'main' com.beust.jcommander.ParameterException: Was passed main parameter '-enablePassThrough' but no main parameter was defined in your arg class ..."

**Comment by XenXenOfficial** [comment]
What's your Selenium version?

**Comment by Mr3RF** [comment]
3.141.59

**Comment by XenXenOfficial** [comment]
Latest is 3.9

**Comment by Mr3RF** [comment]
are you sure? because I found it on selenium's website! could you please send me the download link?

**Comment by TheDutchCoder** [comment]
> Latest is 3.9

Latest is 3.141.59 https://github.com/SeleniumHQ/selenium/releases
