### ISSUE TITLE
Host header or origin header is specified and is not localhost

### ISSUE THREAD

**Issue by vkasharma** [facebook/php-webdriver#662]
The browser gets opens but afterward, I get below error. I am using selenium grid.

If I use host 'http://localhost:4445/wd/hub' all works fine, but I am testing on my other system so I am using 'http://192.168.0.2:4445/wd/hub' host, i am unable to access. Please help.

**Fatal error:** Uncaught Facebook\WebDriver\Exception\WebDriverException: JSON decoding of remote response failed. Error code: 4 The response: 'Host header or origin header is specified and is not localhost.' in D:\xampp\htdocs\auto-test\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php:305 Stack trace: #0 D:\xampp\htdocs\auto-test\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(565): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand)) #1 D:\xampp\htdocs\auto-test\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(244): Facebook\WebDriver\Remote\RemoteWebDriver->execute('get', Array) #2 D:\xampp\htdocs\auto-test\auto-chrome.php(50): Facebook\WebDriver\Remote\RemoteWebDriver->get('https://www.goo...') #3 {main} thrown in D:\xampp\htdocs\auto-test\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php on line 305

I am using below versions,
PHP : 7.3
Facebook WebDriver : 1.7.1
Selenium Jar : selenium-server-standalone-4.0.0-alpha-2.jar
Chrome Driver : 77.0.3865.75

**Comment by OndraM** [comment]
You can try this with latest stable selenium server (3.141.59) and latest chrome+chromedriver. But it does not looks like php-webdriver issue.

However if it still persists, please reopen the issue (or report a new one).

**Comment by sweet-greg** [comment]
I seem to be hitting the same issue.
My host is http://host.docker.internal:9515

PHP: 7.2
Chrome Driver: 80.xxx
php-webdriver: 1.8.1

I seem to be able to run if I add the header 'Host: localhost' on the DEFAULT_HTTP_HEADERS

```
class HttpCommandExecutor implements WebDriverCommandExecutor
{
    const DEFAULT_HTTP_HEADERS = [
        'Content-Type: application/json;charset=UTF-8',
        'Accept: application/json',
        'Host: localhost',
    ];
```

**Comment by sweet-greg** [comment]
I havent been able to find any other way to get this to work tbh.
Changing code on HttpCommandExecuter class is pretty bad of course, any better ideas?
