### ISSUE TITLE
Selecting a non-unique option ignores the select box element

### ISSUE THREAD

**Issue by matt-in-a-hat** [facebook/php-webdriver#668]
### What are you trying to achieve? (Expected behavior)
Select an option from a specific select box (using `selectOption`).

E.g. if you have 2 `<select>` elements and both have an `<option>` with the same value.
```html
<select id="s1"><option value="o1">o1</option></select>
<select id="s2"><option value="o1">o1</option></select>
```
It should let you select o1 within s2 with something like
```php
$driver->selectOption('//*[@id="s2"]', 'o1');
```

### What do you get instead? (Actual behavior)
It selects the **first** option that matches the value, not the option that matches that value AND is within the select box matching the supplied xpath.

As far as I can see the `selectOptionOnElement` function doesn't actually use the `$element` when finding the option.

### Details

* Php-webdriver version: 1.7.1
* PHP version: 7.3.9
* Selenium server version: ? ChromeDriver 77.0.3865.40
* Operating system: macOS 10.14.6
* Browser used + version: Chrome 77.0.3865.120

**Comment by andrewnicols** [comment]
I don't actually see a `selectOptionOnElement` function anywhere, and `selectOption` is a protected function. From what I can tell, all of the functions.

I'm 99% sure that you are reporting a bug against the SilverStripe Mink Driver. I've already raised a pull request against that project (https://github.com/silverstripe/MinkFacebookWebDriver/pull/3) but it's sat untouched by the maintainer for 22 days.

As it happens I have created a new MinkFacebookWebDriver which is a fresh rewrite. I'm currently in the process of getting it ready for prime time and I'm hoping to do a proper release when we release version 1.8.0 of php-webdriver (or possibly v2.0). You can see my WIP work at https://github.com/andrewnicols/MinkFacebookWebDriver/. I apologise for the bizarre versioning. I made the mistake of releasing a 1.0.0 when I thought I'd finally got it all working and then discovered a heap of bugs which @OndraM and I have been working to fix and standardise.

Suggest closing this issue as there is no bug in this project.

**Comment by andrewnicols** [comment]
@OndraM we can close this issue.
