### ISSUE TITLE
Multiple drivers- one quit quits all

### ISSUE THREAD

**Issue by pgamaster** [facebook/php-webdriver#675]
### What are you trying to achieve? (Expected behavior)
I want to initiate multiple drivers but when I quit one, quits everything, even separate scripts that run at the same time. I think the issue is related to putenv
How can I run scripts in parallel?

### What do you get instead? (Actual behavior)
all scripts stop working

### How could the issue be reproduced? (Steps to reproduce)

```php
namespace Facebook\WebDriver;

use Facebook\WebDriver\Chrome\ChromeDriver;

require_once('../vendor/autoload.php');

putenv("webdriver.chrome.driver=../chromedriver.exe"); 


try {

    $driver = ChromeDriver::start();
    $driver2 = ChromeDriver::start();

    $driver->get("https://www.google.com/");
    $driver2->get("https://www.google.com/");

} catch (\Exception $e) {
    echo $e->getMessage();
}


$driver->quit(); // this kills both drivers at the same time
echo "sleeping...";
sleep(5);
$driver2->quit(); // throws error
```

### Details

* Php-webdriver version: 1.7
* PHP version: 7
* Selenium server version: 
* Operating system:  win 10
* Browser used + version: latest chrome

**Comment by OndraM** [comment]
I believe this is because both instances of `ChromeDriver` actually communicate with the same chromedriver.exe. 

To run multiple webdriver instances, I would suggest running tests through Selenium server - its purpose is exactly this, to allow multiple browser instances to be run at one. See [README](https://github.com/facebook/php-webdriver#start-server).

**Comment by pgamaster** [comment]
Thank you, yes it works this way. But in java:
``
System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
WebDriver driver = new ChromeDriver();
WebDriver driver2 = new ChromeDriver();
driver2.get("https://google.com/");
driver2.quit(); // this will close only the current driver2's window
``

Is it possible to fix?
