### ISSUE TITLE
[1.8.0] Illegal key values seen in w3c capabilities: [platform]

### ISSUE THREAD

**Issue by Lctrs** [facebook/php-webdriver#676]
Trying the upcoming `1.8.0` version in my project [`Lctrs/mink-panther-driver`](https://github.com/Lctrs/mink-panther-driver) (https://github.com/Lctrs/mink-panther-driver/pull/31).

All my tests fails with this error.

See for example :
- https://travis-ci.org/Lctrs/mink-panther-driver/jobs/611330582
- https://github.com/Lctrs/mink-panther-driver/runs/300913555

**Comment by OnkelTem** [comment]
Same here.

After quick debugging I found that this 1.8.x addition to `\Facebook\WebDriver\Remote\RemoteWebDriver::create`:

```php
        // W3C
        $parameters = [
            'capabilities' => [
                'firstMatch' => [static::convertCapabilitiesToW3c($desired_capabilities->toArray())],
            ],
        ];

        if ($required_capabilities !== null && $required_capabilities_array = $required_capabilities->toArray()) {
            $parameters['capabilities']['alwaysMatch'] = static::convertCapabilitiesToW3c($required_capabilities_array);
        }
```
is leading to the problem.

So it's probably related to W3C WebDriver protocol.

**Comment by OndraM** [comment]
What version of browser, browser driver and selenium server do you use?

I know why this is happening (the capabilities are indeed not yet W3C compatible), but I don't know why this is not happening to me and to tests on Travis 🤔.

**Comment by Lctrs** [comment]
Chrome 78.0.3904.97
Chromedriver 78.0.3904.70

Took from my travis job.

**Comment by OnkelTem** [comment]
Chrome Version 77.0.3865.75 (Official Build) (64-bit)
Chromedriver ChromeDriver 77.0.3865.40

**Comment by OndraM** [comment]
Oh, I see. Well, we are apparently not sending platform requirements as part of capabilities in tests, while you are - is this correct?

**Comment by Lctrs** [comment]
I am calling the static factories `Facebook\WebDriver\Remote\DesiredCapabilities::(chrome|firefox)` at some point in my test.

**Comment by OndraM** [comment]
Right, so this is the issue, we add the incompatible platform ourselves :speak_no_evil: 
https://github.com/facebook/php-webdriver/blob/ec7ce5b611e3a73eb789c783760487c89b4999a1/lib/Remote/DesiredCapabilities.php#L199

It seems some kind of Capabilities conversion to W3C compatible ones will be needed in the end. I'm on it :rocket:

**Comment by OndraM** [comment]
Ok, the implementation should be ready (see #678).

Could you @Lctrs @OnkelTem please test your projects with branch `w3c-capabilitites`?

```
composer require facebook/webdriver:dev-w3c-capabilitites@dev
```

**Comment by Lctrs** [comment]
@OndraM here is the build : https://travis-ci.org/Lctrs/mink-panther-driver/builds/612038066 (ref PR : https://github.com/Lctrs/mink-panther-driver/pull/31). Much better. I would say that remaining errors are on my side. Good job !

Also, would it be possible to provide a method somewhere that would tells us that the web driver is running in `w3c` mode ? Something like `RemoteWebDriver::isW3cMode() : bool`. That would helps users of the library to make the transition I think.

**Comment by OndraM** [comment]
Didn't check, but are you sure the errors are not related to W3C mode? There seems to be quite a lot of failed buils :).

To see whether you are running W3C mode or not, you can use `isW3cCompliant()` method of RemoteWebDriver, which is already there.

**Comment by Lctrs** [comment]
At first glance, they seem tout be related to things that has been removed in W3C mode. I'm also hitting a bug not related to W3C mode.

Didn't known this one. Thanks :)

**Comment by OnkelTem** [comment]
At first I thought it didn't work, due to this error message in my logs:
```
unknown command: Cannot call non W3C standard command while in W3C mode
```
But then I could nail down what raised this error:
```
$this->driver->manage()->window()->maximize();
```
If I comment this line out, my script does its job.

**Comment by OndraM** [comment]
@OnkelTem I added the missing W3C compatible maximize command (amongst few others) in #679 , so once this is merged, it should start working for you.
