### ISSUE TITLE
Undefined index: ELEMENT when using findElement() functions

### ISSUE THREAD

**Issue by otzy** [facebook/php-webdriver#688]
### What are you trying to achieve? (Expected behavior)

I'm trying to $driver->findElement(), findElements(), or RemoteWebElement->findElement().
All throw an exception

### What do you get instead? (Actual behavior)
I get an error "Undefined index: ELEMENT" on lines that use `$raw_element['ELEMENT']`

var_dump($raw_element) outputs the following structure
```
array(1) {
  'element-6066-11e4-a52e-4f735466cecf' =>
  string(36) "1ba86d2e-0292-9242-b5b3-d90149516cef"
}
```

to fix this I temporary replaced all usages of `$raw_element['ELEMENT']` with `\array_values($raw_element)[0]` and findElement() works now for me.

### Details

* Php-webdriver version: 1.7.1
* PHP version: 7.3
* Selenium server version: 3.141.59
* Operating system: Mac OS X 10.14.6
* Browser used + version: Firefox 70.0.1

**Comment by OndraM** [comment]
See #469 - this fix is merged to community branch and will be part of release 1.8.0.

For now you can use dev version of the branch, see https://github.com/facebook/php-webdriver/issues/469#issuecomment-554979855
