### ISSUE TITLE
Capability platform renamed to platformName in W3C

### ISSUE THREAD

**Issue by andrewnicols** [facebook/php-webdriver#692]
### What are you trying to achieve? (Expected behavior)
Obtain the platform name using `$driver->getCapabilities()->getPlatformName();`

### What do you get instead? (Actual behavior)
An empty string

```
Facebook\WebDriver\Remote\DesiredCapabilities Object
(
    [capabilities:Facebook\WebDriver\Remote\DesiredCapabilities:private] => Array
        (
            [acceptInsecureCerts] =>
            [browserName] => firefox
            [browserVersion] => 70.0.1
            [moz:accessibilityChecks] =>
            [moz:buildID] => 20191030021342
            [moz:geckodriverVersion] => 0.26.0
            [moz:headless] =>
            [moz:processID] => 92026
            [moz:profile] => /var/folders/tj/065fspd94551xb8p70m46tch0000gn/T/rust_mozprofile2LLLVd
            [moz:shutdownTimeout] => 60000
            [moz:useNonSpecCompliantPointerOrigin] =>
            [moz:webdriverClick] => 1
            [pageLoadStrategy] => normal
            [platformName] => mac
            [platformVersion] => 19.0.0
            [rotatable] =>
            [setWindowRect] => 1
            [strictFileInteractability] =>
            [timeouts] => Array
                (
                    [implicit] => 0
                    [pageLoad] => 300000
                    [script] => 30000
                )

            [unhandledPromptBehavior] => dismiss and notify
            [webdriver.remote.sessionid] => 6329ccc8-4de8-9a41-a01c-37dec81991b5
        )

)
```

### How could the issue be reproduced? (Steps to reproduce)
Rerproduced putting this in a unit test for now:

```php
        error_log(print_r($this->driver->getCapabilities()->getPlatform(), true));
        error_log(print_r($this->driver->getCapabilities(), true));
```

**Comment by andrewnicols** [comment]
W3C:
https://www.w3.org/TR/webdriver/#capabilities

| Capability | Key | Value Type | Description |
| -- | -- | -- | -- |
| Platform name | "platformName" | string | Identifies the operating system of the endpoint node.|

JSONWire:
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#capabilities-json-object

|  Key | Type | Description |
| -- | -- | -- |
| platform | string | A key specifying which platform the browser is running on. This value should be one of {WINDOWS\|XP\|VISTA\|MAC\|LINUX\|UNIX}. When requesting a new session, the client may specify ANY to indicate any available platform may be used. } |

**Comment by andrewnicols** [comment]
I've additionally discovered differences between how Chrome + Firefox (and presumably others) report the platform.

### Chrome ###
```
            [platformName] => mac os x
```

### Firefox ###
```
            [platformName] => mac
```

**Comment by OndraM** [comment]
Well, so far we are able to convert user-set capabilities from JsonWire to W3C (#678). However not vice versa (retrieve W3C capabilities after session creation and set them to the DesiredCapabilities object).

I'm thinking how we should resolve this - because implementing full-featured convertor from W3C to JsonWire seems like a lot of work with maybe not so big benefits. 

This will definitely have to be resolved in 2.x (where we will only support W3C), however for now, I suggest maybe implementing conversion just for the platform/platformName, and leave other incompatibilities be with reference to experimental support of W3C in php-webdriver 1.8.

What do you mean, @andrewnicols ?

**Comment by OndraM** [comment]
Ok, so have a look at #695
