### ISSUE TITLE
RemoteKeyboard is not compatible with W3C mode

### ISSUE THREAD

**Issue by Lctrs** [facebook/php-webdriver#698]
### What are you trying to achieve? (Expected behavior)

Using WebDriverAction to send keys to an element.

### What do you get instead? (Actual behavior)

```
 Facebook\WebDriver\Exception\UnknownCommandException: unknown command: Cannot call non W3C standard command while in W3C mode

/home/runner/work/mink-panther-driver/mink-panther-driver/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:150
/home/runner/work/mink-panther-driver/mink-panther-driver/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:385
/home/runner/work/mink-panther-driver/mink-panther-driver/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:593
/home/runner/work/mink-panther-driver/mink-panther-driver/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php:40
/home/runner/work/mink-panther-driver/mink-panther-driver/vendor/facebook/webdriver/lib/Remote/RemoteKeyboard.php:47
/home/runner/work/mink-panther-driver/mink-panther-driver/vendor/facebook/webdriver/lib/Interactions/Internal/WebDriverSendKeysAction.php:49
/home/runner/work/mink-panther-driver/mink-panther-driver/vendor/facebook/webdriver/lib/Interactions/WebDriverCompositeAction.php:59
/home/runner/work/mink-panther-driver/mink-panther-driver/vendor/facebook/webdriver/lib/Interactions/WebDriverActions.php:57
/home/runner/work/mink-panther-driver/mink-panther-driver/src/PantherDriver.php:473
/home/runner/work/mink-panther-driver/mink-panther-driver/vendor/behat/mink/src/Element/NodeElement.php:105
/home/runner/work/mink-panther-driver/mink-panther-driver/vendor/behat/mink/src/Element/TraversableElement.php:160
/home/runner/work/mink-panther-driver/mink-panther-driver/vendor/mink/driver-testsuite/tests/Basic/CookieTest.php:18
```

### Details

It appears that the command `DriverCommand::SEND_KEYS_TO_ACTIVE_ELEMENT` does not exists anymore in W3C mode. Only `DriverCommand::SEND_KEYS_TO_ELEMENT` remains.

* Php-webdriver version: 1.8.0@dev
* PHP version: 7.4
* Operating system: Ubuntu
* Browser used + version: Chrome latest

**Comment by OndraM** [comment]
Yeah, there is no such thing as "send keys to active element" in W3C.

I'm thinking about possible solution:
1. Implement some polyfill for this feature in W3C way - this probably means calling "get active element" first and the respective method like "send keys" pass to the returned element.
1. Mark the whole class deprecated and JsonWire only. I'm not that fan of providing some features in the library, which aren't part of the protocol... But @Lctrs maybe there is some usecase for the RemoteKeyboard class?

**Comment by OndraM** [comment]
This is the workaround for W3C:

Instead of:
```php
$this->driver->getKeyboard()->sendKeys('foo');
```
This should provide the same functionality:
```php
$activeElement = $this->driver->switchTo()->activeElement();
$activeElement->sendKeys('foo');
```

So adding this to `RemoteKeyboard` is not difficult... But I don't know whether we should provide this kind of abstraction in php-webdriver :thinking: .

**Comment by OndraM** [comment]
Here you go: https://github.com/facebook/php-webdriver/pull/699

**Comment by OndraM** [comment]
@Lctrs The fix has been merged to community branch. Could you whether it works for you properly?

**Comment by Lctrs** [comment]
All works for me :+1:

**Comment by Lctrs** [comment]
Thanks !
