### ISSUE TITLE
Update version 1.7.1 on Packagist

### ISSUE THREAD

**Issue by abdounikarim** [facebook/php-webdriver#706]
### What are you trying to achieve? (Expected behavior)
Hello, can you update the repository on packagist so we can use it with Symfony 5 ?
On this file, there is the compatibility with the `symfony/process`component on version `5.0`but not on packagist. 

### What do you get instead? (Actual behavior)
The actual installation doesn't work with this message : 
`Your requirements could not be resolved to an installable set of packages.`

### How could the issue be reproduced? (Steps to reproduce)
Just install a new Symfony 5 project and try to add this library.

### Details
1.7.1

* Php-webdriver version: 1.7.1
* PHP version: 7.4
* Selenium server version: 
* Operating system: Mac OS X
* Browser used + version: 

Cheers 😉

**Comment by OndraM** [comment]
Hi,
version 1.8.x is in progress, see active pull requests. But we don't have ETA when it will be released. But you can already use the dev version of the community branch, which contains the symfony 5.0 support.
`composer require facebook/webdriver:^1.8@dev`

See also https://github.com/facebook/php-webdriver/issues/469#issuecomment-554979855
