### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dmitryuk** [facebook/php-webdriver#710]
When do you plan to make new release? I think it will be help full for us.
For example, I am waiting for PR https://github.com/facebook/php-webdriver/pull/560

**Comment by Bu4ak** [comment]
Same issue

**Comment by andrewnicols** [comment]
I too am waiting for the 1.8.0 release but I know that there are a number of issues still pending. Most of them now have patches up, or are in-progress.

So far it seems that only a couple of people are actively helping with the testing effort. Perhaps you’re both able to help and identify any other issues?

**Comment by OndraM** [comment]
As @andrewnicols wrote. There is lot of changed stuff in upcoming release, so we'd like to make sure there aren't any issues.

Also, you are more than welcome with testing the new release - you can already use it by requiring the development version, see https://github.com/facebook/php-webdriver/issues/469#issuecomment-554979855 .
