### ISSUE TITLE
Facebook\WebDriver\Exception\UnrecognizedExceptionException:invalid arguement

### ISSUE THREAD

**Issue by rannd** [facebook/php-webdriver#711]
### What are you trying to achieve? (Expected behavior)
tried running dusk test case on centos vm

### What do you get instead? (Actual behavior)
It thrown facebook/webdriver exception

### How could the issue be reproduced? (Steps to reproduce)

```php 7.3.12
// You can insert your PHP code here (or remove this block if it is not relevant for the issue).
```

### Details
Seems chrome-driver 78 not supported with new chrome version 79

* Php-webdriver version: 
* PHP version: 
* Selenium server version: 
* Operating system: 
* Browser used + version:

**Comment by andrewnicols** [comment]
We really need a test case here or at the very least a simplified example.

**Comment by andrewnicols** [comment]
You cannot use chromedriver 78 with chrome 79. This is already a known restriction and well documented. See https://chromedriver.chromium.org/downloads/version-selection for more details.

Also see https://github.com/andrewnicols/chromedriver-wrapper as a handy wrapper to automate the process.

**Comment by rannd** [comment]
1) Tests\Browser\loginTest::testLogin
 Facebook\WebDriver\Exception\UnrecognizedExceptionException: invalid argument      (Session info: headless chrome=75.0.3770.100)
   (Driver info: chromedriver=75.0.3770.140 (2d9f97485c7b07dc18a74666574f19176731995c-refs/branch-heads/3770@{#1155}),platform=Linux 3.10.0-1062.9.1.el7.x86_64 x86_64)
 
 /var/www/html/acat-jenkins/acat-phase-2/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:158
 /var/www/html/acat-jenkins/acat-phase-2/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:331

**Comment by rannd** [comment]
It's not working with even another versions

**Comment by OndraM** [comment]
Hi @rannd , when creating an issue, you need to fill properly the whole issue template which was provided to you - including exact steps to reproduce the problem you are facing, code you are trying to run and versions of chrome, php-webdriver etc. Otherwise we are not able to help. 

So once you have those details, please feel free to open a new issue. Thanks 🙂

**Comment by andrewnicols** [comment]
It's also working for me with Chrome 79.

**Comment by rannd** [comment]
Hi @OndraM thanks for suggestion. i have updated the issue above now

**Comment by OndraM** [comment]
Try to use latest chrome (79), chromedriver (79.0.3945.36) and development version of php-webdriver:

```bash
composer require facebook/webdriver:^1.8@dev
```

**Comment by rahu923** [comment]
tried with this solution as well but issue still persists

**Comment by andrewnicols** [comment]
@rahu923, we really need more information still.  Why do you think that this is a facebook/php-webdriver issue and not a dusk issue, or an issue with your code?

Can you please perform some debugging with Dusk, or at least provide a link to your code, but preferably a simplified testcase.

I've just created a new Laravel repo, with Dusk, set up auth, amended your sample test to actually pass, and still have this passing:

https://github.com/andrewnicols/phpwebdriver-711

**Comment by andrewnicols** [comment]
```
2077 711:master> APP_URL=http://localhost:8000 php artisan dusk
PHPUnit 8.5.0 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 2.51 seconds, Memory: 16.00 MB

OK (1 test, 1 assertion)
```

**Comment by alshenetsky** [comment]
I've experienced the same issue. Turned out that I used wrong url (e.g. 'yandex.ru' instead of 'http://yandex.ru' which is incorrect). It was hard to find out the reason so I put this comment here :)
