### ISSUE TITLE
Symfony 5

### ISSUE THREAD

**Issue by michaelKaefer** [facebook/php-webdriver#712]
facebook/webdriver is not compatible with Symfony 5 until now.

<code>facebook/webdriver 1.7.1 requires symfony/process ^2.8 || ^3.1 || ^4.0 -> no matching package found.</code>

**Comment by OndraM** [comment]
Hi, this is already solved by #670 and merged to community branch. The fix will be part of next release 1.8. In the meantime you can use dev-version of upcoming php-webdriver 1.8:

```bash
composer require facebook/webdriver:^1.8@dev
```
