### ISSUE TITLE
Cookies with a `null` `expiry` cause invalid argument: invalid 'expiry'

### ISSUE THREAD

**Issue by CJDennis** [facebook/php-webdriver#723]
### What are you trying to achieve? (Expected behavior)
Set a cookie with a `null` `expiry`.

### What do you get instead? (Actual behavior)
```
  [Facebook\WebDriver\Exception\UnrecognizedExceptionException] invalid argument: invalid 'expiry'
  (Session info: chrome=79.0.3945.88)
  (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Windows NT 10.0.17763 x86_64)
```

### How could the issue be reproduced? (Steps to reproduce)
Using a Codeception acceptance test:
```php
$session_name = 'foobar';
$I->saveSessionSnapshot($session_name);
$I->loadSessionSnapshot($session_name);
```

### Details

* Php-webdriver version: 1.4.1
* PHP version: 5.5.9
* Selenium server version: 3.141.59
* Operating system: Windows 10
* Browser used + version: Chrome 79

I realise this is an old version, but the project is to update PHP to a modern version, and running tests is absolutely essential to ensure nothing breaks. (Jumping from PHP 5.5 to PHP 7.3 breaks the site so badly it won't load.)

As a workaround, I've changed the following method in `vendor/facebook/webdriver/lib/Cookie.php` from:

```php
    /**
     * @return array
     */
    public function toArray()
    {
      return $this->cookie;
    }
```

to:

```php
    /**
     * @return array
     */
    public function toArray()
    {
      $cookie = $this->cookie;
      if ($cookie['expiry'] === null) {
        unset($cookie['expiry']);
      }
      return $cookie;
    }
```

Is there some option I can set that will do the same thing so I don't have to run with changed `vendor` code?

**Comment by OndraM** [comment]
Hi @CJDennis !
This issue was already reported in #626 and fixed in #627 . In order to get the fix, you need to update to newer php-webdriver (the fix is included in 1.7.0). You are right the PHP requirements changed and version 5.5 is no longer supported, but you can still use PHP 5.6 - changes in your code required for this upgrade should be minimal to none.

Other than that, I don't thing there is something else we can do for you, I'm sorry.
