### ISSUE TITLE
Pages randomly don't transition

### ISSUE THREAD

**Issue by TheDutchCoder** [facebook/php-webdriver#728]
### What are you trying to achieve? (Expected behavior)

Sometimes, when clicking a link or button, the page doesn't transition but stays on the current page.

### What do you get instead? (Actual behavior)

The page to transition.

### How could the issue be reproduced? (Steps to reproduce)

This is 100% random. Sometimes it fails, most of the time it doesn't.
It's on random pages and in random tests.

Here's the selenium log that shows the click and then looking for an element on the next page (which it didn't navigate to)...

```
[36mselenium_1                  |[0m 17:09:15.732 DEBUG [WebDriverServlet.lambda$handle$0] - Handler thread for session 6be77b656db2b6b65687664c8fbcffe0 (chrome): Executing POST on /session/6be77b656db2b6b65687664c8fbcffe0/element/b3388adc-8301-4c53-bc2c-78bc4309f833/click (handler: ServicedSession)
[36mselenium_1                  |[0m 17:09:15.732 DEBUG [ReverseProxyHandler.execute] - To upstream: {}
[36mselenium_1                  |[0m 17:09:15.732 DEBUG [HttpURLConnection.writeRequests] - sun.net.www.MessageHeader@2eb5ed0f9 pairs: {POST /session/6be77b656db2b6b65687664c8fbcffe0/element/b3388adc-8301-4c53-bc2c-78bc4309f833/click HTTP/1.1: null}{Accept: application/json}{Content-Type: application/json; charset=utf-8}{Cache-Control: no-cache}{Pragma: no-cache}{User-Agent: Java/1.8.0_222}{Host: localhost:31192}{Connection: keep-alive}{Content-Length: 2}
[36mselenium_1                  |[0m 17:09:16.568 DEBUG [HttpURLConnection.getInputStream0] - sun.net.www.MessageHeader@5be7b7094 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 14}{Content-Type: application/json; charset=utf-8}{cache-control: no-cache}
[36mselenium_1                  |[0m 17:09:16.568 DEBUG [ReverseProxyHandler.execute] - To downstream: {"value":null}
[36mselenium_1                  |[0m 17:09:16.569 DEBUG [WebDriverServlet.handle] - Found handler: 6be77b656db2b6b65687664c8fbcffe0 (org.openqa.selenium.chrome.ChromeDriverService)
[36mselenium_1                  |[0m 17:09:16.570 DEBUG [WebDriverServlet.lambda$handle$0] - Handler thread for session 6be77b656db2b6b65687664c8fbcffe0 (chrome): Executing POST on /session/6be77b656db2b6b65687664c8fbcffe0/element (handler: ServicedSession)
[36mselenium_1                  |[0m 17:09:16.570 DEBUG [ReverseProxyHandler.execute] - To upstream: {"using":"css selector","value":"#pay-method-creditcard"}
```

### Details

* Php-webdriver version: 1.8@dev
* PHP version: 7.3
* Selenium server version: 3.141.59-yttrium
* Operating system: Mac OS X Mojave
* Browser used + version: Chrome 76

**Comment by OndraM** [comment]
Hi @TheDutchCoder , this could be caused by many reasons. You didn't provide the actual webpage which causes the issue nor the code you use, so it is not possible for us to reproduce the issue - without this we cannot help you more. 

But I recommend adding some [wait](https://github.com/facebook/php-webdriver/wiki/HowTo-Wait) before you attempt to click on the button - there could be eg. some Javascript binded for the button, and sometimes it didn't have a time to load.

If it doesn't help, please provide comprehensive steps to reproduce the issue so that we can have a more verbose look - and we will reopen the issue. Thanks!
